<?php 
$lan = array(
  "NoRecord" => "Nie ma takiego rekordu",
  "BackToBList" => "Powrót do listy zwrotów",
  "NotFound" => "Nie znaleziono<br/>",
  "AddedToB" => "Dodano %s do liczby zwrotów dla u¿ytkownika %s<br/>",
  "NotAddedToB" => "Nie mo¿na dodaæ %s do liczby zwrotów dla u¿ytkownika %s<br/>",
  "MadeUnconfirmed" => "Oznaczono u¿ytkownika %s jako niepotwierdzony<br/>",
  "MadeUserRText" => "U¿ytkownikowi %s w³±czono odbieranie wiadomo¶ci tekstowych<br/>",
  "DelUser" => "Usuniêto u¿ytkownika %s<br/>",
  "DeletingB" => "Usuwam zwroty %s .. <br>",
  "DoneAndLoading" => "..Gotowe, ³adujê nastêpny zwrot..",
  "NoSRecord" => "Nie ma takiego rekordu",
  "PossibleActions" => "Mo¿liwe dzia³ania:",
  "ForUser" => "Dla u¿ytkownika o adresie e-mail",
  "IncreaseB" => "Zwiekszenie licznika zwrotów o",
  "IncreaseBNote" => "(u¿yj liczby ujemnej aby zmniejszyæ)",
  "MarkAsUnconfirmed" => "Oznacz u¿ytkownika jako nipotwierdzony",
  "MarkAsUnconfirmedNote" => "(a zatem mo¿esz ponownie wys³aæ pro¶bê o potwiedzenie)",
  "SetReceiveText" => "Wysy³aj u¿ytkownikowi wiadomo¶ci tekstowe zamiast HTML",
  "DelUser1" => "Usuñ u¿ytkownika",
  "DelAndGo" => "Usuñ ten zwrot i przejd¼ do nastêpnego",
  "DoAbove" => "Wykonaj powy¿sze",
  "BounceDetails" => "Detale zwrotu:",
  "ID" => "ID",
  "Date" => "Data",
  "Status" => "Status",
  "Comment" => "Komentarz",
  "Header" => "Nag³ówek",
  "Body" => "Zawarto¶æ",
  
  # new in 2.9.5
  'Regular Expression' => 'Wyra¿enie regularne',
  'Action' => 'Dzia³anie',
  'Memo for this rule' => 'Notatka dla tej regu³y',
  'Add new Rule' => 'Dodaj now± regu³ê',
  'Create New Rule based on this bounce' => 'Utwórz now± regu³ê na podstawie tego zwrotu',
);
?>