<?php

$lan = array(
  'Your database is out of date, please make sure to upgrade' => 'Towja baza danych jest nieaktualna, uaktualnij j± do najnowszej wersji',
  'Your version' => 'Twoja wersja',
  'Latest version' => 'Najnowsza wersja',
  'phplist version' => 'Wersja <a href="http://www.phplist.com">phplist</a>',
  'Database has not been initialised' => 'Baza danych nie zosta³a zainicjowana',
  'go to' => 'id¼ do',
  'Initialise Database' => 'inicjujê bazê danych',
  'to continue' => 'aby kontynuowaæ',
  'A new version of PHPlist is available!' => 'Nowa wersja PHPlist jest dostêpna!',
  'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => 'Nowa wersja mo¿e poprawiæ kwestiê bezpieczeñstwa,<br/>wiêc zalecamy uaktualniæ najszybciej jak to mo¿liwe',
  'View what has changed' => 'Zobacz co zosta³o zmienione',
  'Download' => 'Pobierz',
  'System Functions' => 'Funkcje systemu',
  'Setup ' => 'Ustawienia ',
  'Check Database structure' => 'Sprawd¼ strukturê bazy danych',
  'View the eventlog' => 'Przegl±daj dziennik zdarzeñ',
  'Configuration functions' => 'Funkcje konfiguracji',
  'Configure Attributes' => 'Ustawienia atrybutów',
  'Control values for' => 'Ustawienia warto¶ci dla',
  'Control values for' => 'Ustawienia warto¶ci dla',
  'Control values for' => 'Ustawienia warto¶ci dla',
  'Configure Subscribe pages' => 'Ustawienia stron rejestracji',
  'List and user functions' => 'Funkcje list i u¿ytkownika',
  'List the current lists' => 'Wy¶wietl obecne listy',
  'List all Users' => 'Wy¶wietl wszystkich u¿ytkowników',
  'Reconcile the user database' => 'Operacje na bazach u¿ytkowników',
  'Import Users' => 'Import u¿ytkowników',
  'Export Users' => 'Eksport u¿ytkowników',
  'Administrator functions' => 'Funkcje administratora',
  'Add, edit and remove Administrators' => 'Dodaj, edytuj i usuñ Administratorów',
  'Configure attributes for administrators' => 'Konfiguruj atrybuty Administratorów',
  'Message functions' => 'Funkcje wiadomo¶ci',
  'Configure Templates' => 'Funkcje szablonów',
  'List all Messages' => 'Wy¶wietl wszystkie wiadomo¶ci',
  'Process the Message queue' => 'Przetwarzaj kolejkê wiadomo¶ci',
  'RSS Functions' => 'Funkcje kana³ów RSS',
  'Get RSS feeds' => 'Pobierz kana³y RSS',
  'View RSS items' => 'Wy¶wietla elementy RSS',
  'Plugins' => 'Dodatki',
  'Upgrade' => 'Upgrade',
'Change your details (e.g. password)' => 'Zmieñ swoje ustawienia (np. has³o)',
'You have set TEST in config.php to 1, so it will only show what would be sent' => 'Ustawi³e¶ TEST w config.php na 1, wiêc bêdzie tylko pokazane co zosta³oby wys³ane',

  # added at a later stage
  'setup' => 'ustawienia',
  'upgrade' => 'uaktualnij',
  'dbcheck' => 'baza',
  'eventlog' => 'dziennik zdarzeñ',
  'attributes' => 'atrybuty',
  'spage' => 'strona rejestracji',
  'list' => 'listy',
  'reconcileusers' => 'uzgadnianie u¿ytkowników',
  'import' => 'import',
  'export' => 'eksport',
  'admins' => 'administratorzy',
  'adminattributes' => 'atrybuty admina',
  'send' => 'wy¶lij',
  'templates' => 'szablony',
  'processqueue' => 'kolejka wiadomo¶ci',
  'processbounces' => 'kolejka zwrotów',
  'getrss' => 'pobierz rss',
  'viewrss' => 'zobacz rss',
  'admin' => 'admin',
  'preparesend' => 'przygotuj wysy³kê',
  'sendprepared' => 'wy¶lij przygotowane',


);

?>