<?php
$lan = array(
  "Import emails from IMAP folders" => "Import adresów email z folderów IMAP",
  "No lists available" => "Brak dostêpnych list",
  "Add a list" => "Dodaj listê",
  "personal" => "prywatny",
  "email" => "email",
  "folder" => "folder",
  "date" => "data",
  "can't connect" => "nie mo¿na po³±czyæ siê",
  "Processing" => "Przetwarzanie",
  "messages" => "wiadomo¶ci",
  "done" => "gotowe",
  "imap_getmailboxes failed" => "b³±d imap_getmailboxes",
  "Please enter details of the IMAP account" => "Wprowad¼ detale konta IMAP",
  "Select the headers fields to search" => "Wybierz nag³ówki pól wyszukiwania",
  "Select the lists to add the emails to" => "Wybierz listy, aby dodaæ adresy email",
  "Adding users to list" => "Dodawanie u¿ytkowników do listy",
  "Mark new users as HTML" => "Oznacz nowych u¿ytk. jako HTML",
/* read lines below as sentences: if you check 'overwrite' information about a user... etc. */
  "If you check" => "Je¶li zaznaczysz",
  "Overwrite Existing" => "Nadpisz istniej±ce",
  "information about a user in the database will be replaced by the imported information. Users are matched by email." => "informacje o u¿ytkowniku w bazie danych zostan± zast±pione importowanymi informacjami. U¿ytkownicy s± dopasowywani po adreseie email.",
  "Only use complete addresses" => "Tylko pe³ne adresy",
  "addresses that do not have a real name will be ignored. Otherwise all emails will be imported." => "adresy, które nie posiadaj± prawdziwej nazwy zostan± zignorowane. Je¶li nie zaznaczysz tej opcji wszystkie adresy bêd± importowane.",
  "If you choose" => "Je¶li wybierzesz",
  "send notification email" => "wy¶lij potwierdzenie",
  "the users you are adding will be sent the request for confirmation of subscription to which they will have to reply. This is recommended, because it will identify invalid emails." => "u¿ytkownicy, których dodajesz otrzymaj± pro¶bê o potwierdzenie rejestracji, na które bêd± musieli odpowiedzieæ. Jest to zalecane, bo dziêki temu bêdzie mo¿na zidentyfikowaæ nieprawid³owe adresy email.",
  "Send&nbsp;Notification&nbsp;email&nbsp;" => "Wy¶lij potwierdzenie",
  "Make confirmed immediately" => "Oznacz u¿ytkowników jako potwierdzonych",
  "import3info" => "Istniej± dwie mozliwo¶ci dodania nazw u¿ytkowników:
 albo jeden atrybut dla ca³ej nazwy albo dwa atrybuty, jeden dla imienia i jeden dla nazwiska. 
Je¶li u¿yjesz 'dwóch atrybutów', nazwa zostanie podzielona po pierwszej spacji.",
  "Use one attribute for name" => "U¿yj jednego atrybutu dla nazwy",
  'Use two attributes for the name' => 'U¿yj dwóch atrybutów dla nazwy',
  "Attribute one" => "Pierwszy atrybut",
  "Create Attribute" => "Utwórz atrybut",
  "Attribute two" => "Drugi atrybut",
  "Cannot continue" => "Nie mo¿na kontynuowaæ",
  "ok" => "ok",
  "failed" => "b³±d",
  "Processed" => "Przetworzono",
  "folders and" => "pliki oraz",
  "unique emails found" => "znaleziono pojedyncze adresy email",
  "list" => "lista",
  "lists" => "listy",
  "new email was" => "nowy adres email",
  "new emails were" => "nowe adresy email",
  "email was" => "adres by³",
  "emails were" => "adresów by³o",
  "All the emails already exist in the database and are members of the" => "Wszystkie adresy email istniej± ju¿ w bazie i s± cz³onkami",
  "succesfully imported to the database and added to" => "z sukcesem zaimportowano do bazy i dodano do",
  "subscribed to the" => "zasubskrybowano do",
  "emails already existed in the database" => "adresy email ju¿ istniej± w bazie",
  "Invalid Emails found." => "Znaleziono nieprawid³owe adresy email.",
  "These records were added, but the email has been made up. You can find them by doing a search on" => "Rekordy zosta³y dodane ale adresy email zosta³y wygenerowane. Aby je znale¼æ poszukaj",
  "These records were deleted. Check your source and reimport the data. Duplicates will be identified." => "Rekordy zosta³y usuniête. Sprawd¼ ¼ród³o i zaimportuj dane ponownie. Duplikaty zostan± wykryte.",
  "No emails found" => "Nie znaleziono adresó email",
  "Import some more emails" => "Zaimportuj wiêcej adresów email",
  'Server' => 'Serwer',
  'User' => 'U¿ytkownik',
  'Password' => 'Has³o',
  'Continue' => 'Kontynuuj',
  'Process Selected Folders' => 'Przetwarzaj wybrane foldery',
);
?>