<?php 
$lan = array(

  'add_list' => 'Dodaj listê', //duplicated in import1_text
  'cant_connect' => 'nie mo¿na po³±czyæ siê z baz± danych',
  'no_users_to_copy' => 'Brak u¿ytkowników do skopiowania, czy przedrostek jest prawidowy?',
  'remote_server' => 'Wprowad¼ detale zdalnego serwera',
  'server' => 'Serwer:',
  'user' => 'U¿ytkownik:',
  'passwd' => 'Has³o:',
  'database' => 'Nazwa bazy danych:',
  'table_prefix' => 'Przedrostek tabeli:',
  'usertable_prefix' => 'Przedrostek tabeli u¿ytkownika:',
  'select_lists' => 'Wybierz listy aby dodaæ adresy',
  'copy_lists' => 'Kopiuj listy ze zdalnego serwera (listy s± dopasowywane po nazwie)',
  'users_as_html' => 'Oznacz nowych u¿ytk. jako HTML:',
  'info_overwrite_existing' => 'Je¶li zaznaczysz "Nadpisz istniej±ce", informacje o u¿ytkowniku w bazie danych zostan± zast±pione importowanymi informacjami. U¿ytkownicy s± dopasowywani po adreseie email.',
  'overwrite_existing' => 'Nadpisz istniej±ce:',
  'connecting_remote' => 'Tworzenie po³±czenie ze zdaln± baz± danych',
  'getting_data' => 'Pobieranie danych z ',
  'remote_version' => 'Wersja zdalnej bazy',
  'remote_has' => 'Zdalna baza ma',
  'users' => 'u¿ytkowników',
  'lists' => 'list',
  'copying_lists' => 'Kopiowanie list',
  'list' => 'Lista',
  'exists_locally' => 'istnieje lokalnie',
  'created_locally' => 'utworzono lokalnie',
  'remote_list' => 'Zdalna lista',
  'not_created' => 'nie utworzono',
  'copying_attribs' => 'Kopiowanie atrybutów',
  'attrib' => 'Atrybut',
  'copying_users' => 'Kopiowanie u¿ytkowników',
  'overwrite_local' => 'nadpisywanie danych lokalnych',
  'keep_local' => 'zachowywanie danych lokalnych',
  'new_user' => 'jest nowym u¿ytkownikiem',
  'no_mapped_attrib' => 'B³±d, brak zamapowanych atrybutów dla',
  'no_local_list' => 'B³±d, nie zdefiniowano list lokalnych dla',
  'No lists available' => 'Brak dostêpnych list',
  'Done' => 'Gotowe',
  'new users' => 'nowych u¿ytkowników',
  'and' => 'oraz',
  'existing users' => 'istniej±cych u¿ytkowników',
  'continue' => 'Kontynuuj',

);
?>