<?php
$lan = array(
 'Please select a message to display' => 'Wybierz wiadomo¶æ do wy¶wietlenia',
 'Attachments for this message' => 'Za³±czniki tej wiadomo¶ci',
 'No attachments' => 'Brak za³±czników',
 'Filename' => 'Nazwa pliku',
 'Size' => 'Rozmiar',
 'Mime Type' => 'Typ Mime',
 'Description' => 'Opis',
 'Lists this message has been sent to' => 'Ta wiadomo¶æ zosta³a wys³ana do nast. list',
 'None yet' => 'None yet',
 'Send this (same) message to (a) new list(s)' => 'Wy¶lik t± sam± wiadomo¶æ do kolejnych list',
 'List is Active' => 'Lista jest aktywna',
 'List is not Active' => 'Lista jest nieaktywna',
 '<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the "Requeue" function.' => '<b>Uwaga:</b> ta wiadomo¶c zosta³a ju¿ wys³ana do wszystkich list. Aby wys³aæ j± ponownie do nowych u¿ytkowników u¿yj funkcji "Kolejkuj ponownie"',
 'Resend' => 'Wy¶lij ponownie',
 'id' => 'id',
 'subject' => 'temat',
 'fromfield' => 'pole od',
 'tofield' => 'pole do',
 'replyto' => 'odpowied¼ do',
 'message' => 'wiadomo¶æ',
 'textmessage' => 'wiadomo¶æ tekstowa',
 'footer' => 'stopka',
 'entered' => 'wprowadzono',
 'modified' => 'zmodyfikowano',
 'embargo' => 'ograniczenie do',
 'repeatinterval' => 'interwa³ powtórzeñ',
 'repeatuntil' => 'powtarzaj do',
 'status' => 'status',
 'userselection' => 'wybór u¿ytkownika',
 'sent' => 'wys³ano',
 'htmlformatted' => 'sformatowano w html',
 'sendformat' => 'format wysy³ania',
 'template' => 'szablon',
 'processed' => 'przetworzono',
 'astext' => 'jako tekst',
 'ashtml' => 'jako html',
// 'astextandhtml' => 'as text and html', //obsolete by bug 0009687
 'aspdf' => 'jako pdf',
 'astextandpdf' => 'jako text i pdf',
 'viewed' => 'wy¶wietlano',
 'bouncecount' => 'liczba zwrotów',
 'sendstart' => 'pocz±tek wysy³ania',
 'rsstemplate' => 'szablon RSS',
 'owner' => 'w³a¶ciciel',

 # new in 2.10.1
 'edit this message' => 'Edytuj t± wiadomo¶æ',
);
?>
