<?php 
$lan = array(
  "NoRecord" => "چنین رکوردی وجود ندارد",
  "BackToBList" => "بازگشت به فهرست برگشتی ها",
  "NotFound" => "یافت نشد<br/>",
  "AddedToB" => "%s به شمار برگشتی های کاربر %s افزوده شد<br/>",
  "NotAddedToB" => "نتوانستم %s را به شمار برگشتی های کاربر %s اضافه کنم<br/>",
  "MadeUnconfirmed" => "تایید کاربر %s حذف شد<br/>",
  "MadeUserRText" => "کاربر %s به دریافت متنی تغییر کرد<br/>",
  "DelUser" => "کاربر %s حذف شد<br/>",
  "DeletingB" => "حذف برگشتی %s ..\n",
  "DoneAndLoading" => "..انجام شد, بارگذاری برگشی بعدی..",
  "NoSRecord" => "چنین رکوردی وجود ندارد",
  "PossibleActions" => "کارهای ممکن:",
  "ForUser" => "برای کاربر با ایمیل",
  "IncreaseB" => "افزودن به شمار برگشتی",
  "IncreaseBNote" => "(برای کاهش از اعداد منفی استفاده کنید)",
  "MarkAsUnconfirmed" => "تایید کاربر را بردار",
  "MarkAsUnconfirmedNote" => "(تا بتوان درخواست تایید را دوباره فرستاد)",
  "SetReceiveText" => "تنظیم کاربر برای دریافت متن به جای HTML",
  "DelUser1" => "حذف کاربرr",
  "DelAndGo" => "این برگشت را حذف کن و برو به بعدی",
  "DoAbove" => "کارهای بالا را انجام بده",
  "BounceDetails" => "جزئیات برگشت:",
  "ID" => "شناسه",
  "Date" => "تاریخ",
  "Status" => "وضعیت",
  "Comment" => "دیدگاه",
  "Header" => "سربرگ",
  "Body" => "پیکره",
  
  # new in 2.9.5
  'Regular Expression' => 'عبارت رگولار',
  'Action' => 'عملکرد',
  'Memo for this rule' => 'یادداشت برای این قانون',
  'Add new Rule' => 'افزودن قانون جدید',
  'Create New Rule based on this bounce' => 'ایجاد قانون جدید بر پایه این برگشتی',
);
?>