<?php
$lan = array( 
 'checklist for installation' => 'چکلیست نصب',
 'cannot be empty' => 'نباید خالی باشد',
 'editing' => 'در حال ویرایش',
 'save changes' => 'ذخیره تغییرات',
 'edit' => 'ویرایش',

  # added 24 May 2006
  'delete user' => 'حذف کاربر',
  'unconfirm user' => 'حذف تایید کاربر',
  'blacklist user' => 'قراردادن کاربر در لیست سیاه',
  'delete user and bounce' => 'حذف کاربر و برگشت زدن',
  'unconfirm user and delete bounce' => 'حذف تایید کاربر و حذف برگشت',
  'blacklist user and delete bounce' => 'قراردادن کاربر در لیست سیاه و حذف برگشت',
  'delete bounce' => 'حذف برگشت',
  'Website address (without http://)' => 'نشانی سایت وب (بدون http://&lrm;)&rlm;',
  'Domain Name of your server (for email)' => 'نام دامنه سرور شما (برای ایمیل)',
  'Person in charge of this system (one email address)' => 'شخص مسول این سیستم (یک نشانی ایمیل)',
  'How often do you want to check for a new version of PHPlist (days)' => 'هر چند وقت یکبار میخواهید که وجود ویرایش جدید PHPlist بررسی شود (روز)',
  'List of people to CC in system emails (separate by commas)' => 'فهرست افرادی که ایمیلهای سیستم باید برای آنها CC شود (با کاما از هم جدا کنید)',
  'Who gets the reports (email address, separate multiple emails with a comma)' => 'چه کسی گزارشها را دریافت کند (نشانی ایمیل، در صورتیکه چند نشانی وارد میکنید با کاما از هم جدا کنید)',
  'From email address for system messages' => 'نشانی ایمیل که پیامهای سیستمی از آن ایمیل میشود',
  'What name do system messages appear to come from' => 'نامی که پیامهای سیستمی از آن ایمیل میشود',
  'Reply-to email address for system messages' => 'نشانی ایمیل دریافت پاسخ برای پیامهای سیستمی',
  'if there is only one visible list, should it be hidden in the page and automatically
    subscribe users who sign up (0/1)' => 'اگر تنها یک لیست قابل مشاهده وجود دارد، آیا باید در برگه پنهان باشد و کاربرانی که ثبت نام میکنند به طور خودکار مشترک شوند (0/1)',
  'width of a textline field (numerical)' => 'پهنای کادرهای متنی تک خطی (عددی)',
  'dimensions of a textarea field (rows,columns)' => 'ابعاد کادر متنی چند خطی (ردیف و ستون)',
  'Does the admin get copies of subscribe, update and unsubscribe messages (0/1)' => 'آیا مدیر سیستم کپی پیامهای اشتراک، تغییر و لغو اشتراک را دریافت کند (0/1)',
  'The default subscribe page when there are multiple' => 'برگه اشتراک پیشفرض اگر بیشتر از یکی وجود دارد',
  'The default HTML template to use when sending a message' => 'الگوی HTML پیشفرض که برای فرستادن پیام استفاده میشود',
  'URL where users can subscribe' => 'URL جایی که کاربران میتوانند مشترک شوند',
  'URL where users can unsubscribe' => 'URL جایی که کاربران میتوانند اشتراکشان را لغو کنند',
  'URL where users have to confirm their subscription' => 'URL جایی که کاربران باید اشتراکشان را تایید کنند',
  'URL where users can update their details' => 'URL جایی که کاربران میتوانند جزئیات حسابشان را تغییر دهند',
  'URL where messages can be forwarded' => 'URL جایی که پیامها را بازفرست میکنند',
  'Subject of the message users receive when they subscribe' => 'موضوع پیامی که کاربران هنگام اشتراک دریافت میکنند',
  'Message users receive when they subscribe' => 'پیامی که کاربران هنگام اشتراک دریافت میکنند',
  'Subject of the message users receive when they unsubscribe' => 'موضوع پیامی که کاربران هنگام لغو اشتراک دریافت میکنند',
  'Message users receive when they unsubscribe' => 'پیامی که کاربران هنگام لغو اشتراک دریافت میکنند',
  'Subject of the message users receive after confirming their email address' => 'موضوع پیامی که کاربران پس از تایید نشانی ایمیل خود دریافت میکنند',
  'Message users receive after confirming their email address' => 'پیامی که کاربران پس از تایید نشانی ایمیل خود دریافت میکنند',
  'Subject of the message users receive when they have changed their details' => 'موضوع پیامی که کاربران هنگامی که جزئیات حسابشان را تغییر میدهند دریافت میکنند',
  'Message that is sent when users change their information' => 'پیامی که کاربران هنگام تغییر اطلاعاتشان دریافت میکنند',
  'Part of the message that is sent to their new email address when users change their information, and the email address has changed' => ' قسمتی از پیامی که هنگامی که کاربران اطلاعاتشان را تغییر داده اند و نشانی ایمیلیشان تغییر کرده است به نشانی ایمیل جدیدشان فرستاده میشود',
  'Part of the message that is sent to their old email address when users change their information, and the email address has changed' => ' قسمتی از پیامی که هنگامی که کاربران اطلاعاتشان را تغییر داده اند و نشانی ایمیلیشان تغییر کرده است به نشانی ایمیل قدیمشان فرستاده میشود',
  'Subject of message to send when users request their personal location' => 'موضوع پیامی که کاربران هنگام درخواست لطلاع از نشانی شخصیشان دریافت میکنند',
  'Message to send when they request their personal location' => 'پیامی که کاربران هنگام درخواست لطلاع از نشانی شخصیشان دریافت میکنند',
  'Default footer for sending a message' => 'پابرگی که برای ارسال پیام استفاده میشود',
  'Footer used when a message has been forwarded' => 'پابرگی که هنگام بازفرست یک پیام استفاده میشود',
  'Header of public pages. The header should start with &lt;/head&gt; . You can add header elements, but don\'t add the title or other basic header elements.' => 'سربرگ برگه های عمومی. سربرگ باید با &lt;/head&gt; . میتوانید المانهای سربرگ را اضافه کنید، اما عنوان یا دیگر المانهای پایه ای سربرگ را وارد نکنید.',
  'Footer of public pages' => 'پابرگ برگه های عمومی',
  'Charset for HTML messages' => 'کاراکترست برای پیامهای HTML',
  'Charset for Text messages' => 'کاراکترست برای پیامهای متنی',
  'CSS for HTML messages without a template' => 'CSS برای پیامهای HTML بی الگو',
  'Domains that only accept text emails, one per line' => 'دامنه هایی که فقط ایمیلهای متنی دریافت میکنند، هر کدام در یک خط',
  'Minimum amount of items to send in an RSS feed' => 'دست کم این تعداد مورد در یک خوراک RSS فرستاده شود',
  'Template for text item in RSS feeds' => 'الگوی موارد متنی در خوراک RSS',
  'Template for HTML item in RSS feeds' => 'الگی موارد HTML در خوراک RSS',
  'Maximum amount of items to send in an RSS feed' => 'بیشینه تعداد موارد فرستاده شده در یک خوراک RSS',
  'Template for separator between feeds in RSS feeds (text)' => 'الگوی جداساز بین خوراکها در خوراکهای RSS (متنی)',
  'Template for separator between feeds in RSS feeds (HTML)' => 'الگوی جداساز بین خوارکها در خوراکهای RSS (HTML)',
  'Width in px of FCKeditor Area' => 'پهنای بخش FCKeditor به پیکسل',
  'Height in px of FCKeditor Area' => 'بلندی بخش FCKeditor به پیکسل',
);
?>