<?php

$lan = array(
  'Your database is out of date, please make sure to upgrade' => 'پایگاه داده شما از رده خارج است، لطفا ارتقا دهید',
  'Your version' => 'ویرایش شما',
  'Latest version' => 'آخرین ویرایش',
  'phplist version' => 'ویرایش <a href="http://www.phplist.com">phplist</a>',
  'Database has not been initialised' => 'پایگاه داده راه اندازی اولیه نشده',
  'go to' => 'برو به',
  'Initialise Database' => 'راه انداز اولیه پایگاه داده',
  'to continue' => 'برای ادامه',
  'A new version of PHPlist is available!' => 'ویرایش جدید PHPlist وجود دارد!',
  'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => 'ویرایش جدید ممکن است شامل رفع اشکال موارد امنیتی باشد،<br/>بنابراین پیشنهاد میشود هر چه زودتر ارتقا دهید',
  'View what has changed' => 'تغییرات را ببینید',
  'Download' => 'دریافت',
  'System Functions' => 'عملکردهای سیستمی',
  'Setup ' => 'نصب ',
  'Check Database structure' => 'بررسی ساختار پایگاه داده',
  'View the eventlog' => 'دیدن گزارش رویدادها',
  'Configuration functions' => 'عملکردهای پیکربندی',
  'Configure Attributes' => 'پیکربندی ویژگیها',
  'Control values for' => 'بررسی مقدارها برای',
  'Control values for' => 'بررسی مقدارها برای',
  'Control values for' => 'بررسی مقدارها برای',
  'Configure Subscribe pages' => 'پیکریندی برگه اشتراک',
  'List and user functions' => 'عملکردهای فهرست و کاربر',
  'List the current lists' => 'نمایش فهرستهای موجود',
  'List all Users' => 'نمایش همه کاربرها',
  'Reconcile the user database' => 'همگونسازی پایگاه داده کاربر',
  'Import Users' => 'ورود کاربرها',
  'Export Users' => 'صدور کاربرها',
  'Administrator functions' => 'عملکردهای مدیر',
  'Add, edit and remove Administrators' => 'افزودن، ویرایش و حذف مدیران',
  'Configure attributes for administrators' => 'پیکربندی ویژگیها برای مدیران',
  'Message functions' => 'عملکردهای پیام',
  'Configure Templates' => 'پیکربندی الگوها',
  'List all Messages' => 'نمایش همه پیامها',
  'Process the Message queue' => 'پردازش صف پیام',
  'RSS Functions' => 'عملکردهای RSS',
  'Get RSS feeds' => 'دریافت خوراک RSS',
  'View RSS items' => 'دیدن موارد RSS',
  'Plugins' => 'افزونه ها',
  'Upgrade' => 'ارتقا',
'Change your details (e.g. password)' => 'جزئیات حسابتان را تغییر دهید (مانند گذرواژه)',
'You have set TEST in config.php to 1, so it will only show what would be sent' => 'شما مقدار TEST را در config.php برابر 1 قرار داده اید، بنابراین چیزهایی که باید فرستاده شوند نمایش داده میشود و واقعاُ فرستاده نمیشوند',

  # added at a later stage
  'setup' => 'نصب',
  'upgrade' => 'upgrade',
  'dbcheck' => 'بررسی پایگاه‌داده',
  'eventlog' => 'گزارش رویدادها',
  'attributes' => 'ویژگیها',
  'spage' => 'برگه‌های اشتراک',
  'list' => 'فهرستها',
  'reconcileusers' => 'همگون سازی کاربرها',
  'import' => 'وارد کردن کاربرها',
  'export' => 'صادر کردن کاربرها',
  'admins' => 'مدیران',
  'adminattributes' => 'ویژگیهای مدیران',
  'send' => 'فرستادن',
  'templates' => 'الگوها',
  'processqueue' => 'پردازش صف',
  'processbounces' => 'پردازش برگشتیها',
  'getrss' => 'getrss',
  'viewrss' => 'viewrss',
  'admin' => 'admin',
  'preparesend' => 'preparesend',
  'sendprepared' => 'sendprepared',


);

?>