<?php
$lan = array(
  "Import emails from IMAP folders" => "ورود ایمیلها از پوشه های IMAP",
  "No lists available" => "فهرستی موجود نیست",
  "Add a list" => "افزودن یک فهرست",
  "personal" => "شخصی",
  "email" => "ایمیل",
  "folder" => "پوشه",
  "date" => "تاریخ",
  "can't connect" => "نمیتوانم متصل شوم",
  "Processing" => "در حال پردازش",
  "messages" => "پیام ها",
  "done" => "انجام شد",
  "imap_getmailboxes failed" => "imap_getmailboxes ناموفق بود",
  "Please enter details of the IMAP account" => "لطفا جزئیات حساب IMAP را وارد کنید",
  "Select the headers fields to search" => "فیلدهای سربرگ را برای جستجو انتخاب کنید",
  "Select the lists to add the emails to" => "فهرستها را برای افزودن ایمیلها به آنها انتخاب کنید",
  "Adding users to list" => "افزودن کاربرها به فهرست",
  "Mark new users as HTML" => "کاربرهای جدید را برای HTML علامت بزن",
/* read lines below as sentences: if you check 'overwrite' information about a user... etc. */
  "If you check" => "اگر شما",
  "Overwrite Existing" => "بازنویسی را علامت بزنید",
  "information about a user in the database will be replaced by the imported information. Users are matched by email." => "اطلاعات کاربری که از پیش در پایگاه داده هست با اطلاعات ورودی جایگزین میشود. کاربرها با ایمیل تطبیق داده میشوند.",
  "Only use complete addresses" => " را علامت بزنید تنها نشانیهای کامل را به کار ببر",
  "addresses that do not have a real name will be ignored. Otherwise all emails will be imported." => "نشانیهای که نام واقعی نداشته باشند نادیده گرفته میشوند. بقیه ایمیلها وارد میشوند.",
  "If you choose" => "اگر شما",
  "send notification email" => "فرستادن ایمیل تایید را انتخاب کنید",
  "the users you are adding will be sent the request for confirmation of subscription to which they will have to reply. This is recommended, because it will identify invalid emails." => "کاربرانی که شما اضافه میکنید یک درخواست تایید اشتراک دریافت میکنند که باید به آن پاسخ دهند. این روش توصیه میشود، چون موجب شناسایی نشانیهای نامعتبر میشود.",
  "Send&nbsp;Notification&nbsp;email&nbsp;" => "فرستادن&nbsp;ایمیل&nbsp;تایید&nbsp;",
  "Make confirmed immediately" => "تایید فوری",
  "import3info" => "دو راه برای وارد کردن نام کاربران وجود دارد.
یک ویژگی برای نام کامل یا دو ویژگی، یکی برای نام و دیگری برای نام خانوادگی به کار گرفته شود.
اگر از دو ویژگی استفاده میکنید، نام بعد از اولین علامت فاصله بخش میشود.",
  "Use one attribute for name" => "یک ویژگی برای نام کامل",
  'Use two attributes for the name' => 'دو ویژگی برای نام و نام خانوادگی',
  "Attribute one" => "ویژگی یک",
  "Create Attribute" => "ایجاد ویژگی",
  "Attribute two" => "ویژگی دو",
  "Cannot continue" => "نمیتوانم ادامه دهم",
  "ok" => "ok",
  "failed" => "موفق نبود",
  "Processed" => "پردازش شد",
  "folders and" => "پوشه و",
  "unique emails found" => "ایمیلهای یکتا پیدا شد",
  "list" => "فهرست",
  "lists" => "فهرستها",
  "new email was" => "ایمیل جدید",
  "new emails were" => "ایمیلهای جدید",
  "email was" => "ایمیل قبلی",
  "emails were" => "ایمیلهای قبلی",
  "All the emails already exist in the database and are members of the" => "همه ایمیلها از پیش در پایگاه داده بودند و عضو فهرست",
  "succesfully imported to the database and added to" => "با موفقیت به پایگاه داده وارد شد و اضافه شد به",
  "subscribed to the" => "مشترک شد به",
  "emails already existed in the database" => "ایمیلها از پیش در پایگاه داده بودند",
  "Invalid Emails found." => "ایمیلهای نامعتبر پیدا شد.",
  "These records were added, but the email has been made up. You can find them by doing a search on" => "این رکوردها افزوده شدند، اما ایمیلهایشان ساختگی است. برای پیدا کردنشان جستجو کنید",
  "These records were deleted. Check your source and reimport the data. Duplicates will be identified." => "این رکوردها حذف شدند. منبعتان را بررسی کنید و داده ها را دوباره وارد کنید. تکراریها شناسایی خواهند شد.",
  "No emails found" => "ایمیلی پیدا نشد",
  "Import some more emails" => "ایمیلهای بیشتری وارد کنید",
  'Server' => 'سرور',
  'User' => 'کاربر',
  'Password' => 'گذرواژه',
  'Continue' => 'ادامه',
  'Process Selected Folders' => 'پردازش پوشه های انتخاب شده',
);
?>