<?php
$lan = array(
  'You do not have enough priviliges to view this page' => 'شما برای دیدن این برگه مجوزهای لازم را ندارید',
  'Add a user' => 'افزودن یک کاربر',
  'add user' => 'افزودن کاربر',
  'Members of' => 'عضو',
  'Tag all users in this page' => 'همه کاربرها در این برگه را نشانگذاری کن',
  'back to this list' => 'بازگشت به این فهرست',
  'Download users on this list as a CSV file' => 'کاربرهای این فهرست را به صورت یک پرونده CSV دریافت کنید',
  'Please enter a listid' => 'لطفا یک شناسه فهرست وارد کنید',
  'Processing' => 'پردازش',
  'users were moved to' => 'کاربرها برده شدند به',
  'users were copied to' => 'کاربرها کپی شدند به',
  'users were deleted from this list' => 'کاربرها از این لیست حذف شدند',
  'Users found, click add to add this user' => 'کاربرها پیدا شدند، افزودن را کلیک کنید تا این کاربر افزوده شود',
  'Add' => 'افزودن',
  'No user found with that email' => 'کاربری با آن ایمیل پیدا نشد',
  'Inserting user' => 'درج کاربر',
  'User added' => 'کاربر افزوده شد',
  'Deleting' => 'حذف',
  'Done' => 'انجام شد',
  'Users on this list' => 'کاربرهای این فهرست',
  'Listing user' => 'نمایش کاربر',
  'to' => 'تا',//in sentence 'listing user 1  to  50'
  'Listing user 1 to 50' => 'نمایش کاربر 1 تا 50',
  'Members' => 'اعضا',
  'confirmed' => 'تایید شد',
  'tag' => 'نشانگذاری',
  'del' => 'حذف',
  'Delete'=>'حذف',
  '# msgs' => '# پیام',
  '# rss' => '# rss',
  'rss freq' => 'فراوانی rss',
  'last sent' => 'آخرین فرستاده',
  'What to do with "Tagged" users' => 'با کاربرهای نشاندار شده چه کنم',
  'This will only process the users in this page that have the "Tag" checkbox checked' => 'این تنها کاربرهای این برگه که نشاندار شده اند را پردازش میکند.',
  'delete' => 'حذف',
  'move' => 'جابجایی',
  'copy' => 'کپی',
  'nothing' => 'هیچ',
  'to' => 'به', # as in destination
  'from this list' => 'از این فهرست',
  'What to do with all users' => 'با همه کاربران چه کنمWhat to do with all users',
  'This will process all users on this list' => 'این همه کاربران این فهرست را پردازش میکند',
  'do it' => 'انجام بده',
  
  
);
?>