<?php
$lan = array(
 'Please select a message to display' => 'لطفا پیامی را برای نمایش انتخاب کنید',
 'Attachments for this message' => 'پیوست های این پیام',
 'No attachments' => 'پیوست ندارد',
 'Filename' => 'نام پرونده',
 'Size' => 'اندازه',
 'Mime Type' => 'نوع پرونده',
 'Description' => 'شرح',
 'Lists this message has been sent to' => 'فهرستهایی که این پیام برایشان فرستاده شده',
 'None yet' => 'هنوز هیچ',
 'Send this (same) message to (a) new list(s)' => 'این (همان) پیام را برای فهرست (های) جدید بفرست',
 'List is Active' => 'فهرست فعال است',
 'List is not Active' => 'فهرست فعال نیست',
 '<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the "Requeue" function.' => '<b>توجه:</b> این پیام برای همه فهرستها فرستاده شده است. برای فرستادن دوباره آن به کاربرهای جدید عملکرد "بازصف" را به کار ببرید.',
 'Resend' => 'دوباره بفرست',
 'id' => 'id',
 'subject' => 'subject',
 'fromfield' => 'from field',
 'tofield' => 'to field',
 'replyto' => 'reply to',
 'message' => 'message',
 'textmessage' => 'textmessage',
 'footer' => 'footer',
 'entered' => 'entered',
 'modified' => 'modified',
 'embargo' => 'embargo',
 'repeatinterval' => 'repearinterval',
 'repeatuntil' => 'repeatuntil',
 'status' => 'status',
 'userselection' => 'userselection',
 'sent' => 'sent',
 'htmlformatted' => 'htmlformatted',
 'sendformat' => 'sendformat',
 'template' => 'template',
 'processed' => 'processed',
 'astext' => 'به صورت متن',
 'ashtml' => 'به صورت html',
// 'astextandhtml' => 'as text and html', //obsolete by bug 0009687
 'aspdf' => 'به صورت pdf',
 'astextandpdf' => 'as text and pdf',
 'viewed' => 'دیده شده',
 'bouncecount' => 'شمار بازگشتیها',
 'sendstart' => 'send start',
 'rsstemplate' => 'الگوی RSS',
 'owner' => 'صاحب',

 # new in 2.10.1
 'edit this message' => 'این پیام را ویرایش کن',
);
?>
