<?php

$lan = array(
'Running in testmode, no emails will be sent. Check your config file.' => 'اجرا در مد آزمایشی، ایمیلی فرستاده نخواهد شد. پرونده پیکربندی را بررسی کنید.',
'The following restrictions have been set by your ISP:' => 'محدودیتهای زیر توسط میزبان شما تعیین شده اند:',
'Script stage' => 'مرحله اسکریپت',
'Finished, Nothing to do' => 'پایان، کاری برای انجام نیست',
'messages sent in' => 'پیام فرستاده شد در',
'seconds' => 'ثانیه',
'invalid emails' => 'ایمیلهای نامعتبر',
'emails failed (will retry later)' => 'ایمیلهای ناموفق (بعداً دوباره سعی میشود)',
'emails unconfirmed (not sent)' => 'ایمیلهای تایید نشده (فرستاده نشد)',
'Warning: script never reached stage 5' => 'هشدار: اسکریپت به مرحله 5 نرسید',
'This may be caused by a too slow or too busy server' => 'شاید به خاطر کندی شدید یا شلوغی بیش از اندازه سرور باشد',


'In safe mode, batches are set to a maximum of 100' => 'در حالت امن، تنظیم دسته ها به بیشینه 100 تایی',
'Running in safe mode' => 'اجرا در حالت امن',
'msgs/hr' => 'پیام/ساعت',
'Reload required' => 'بارگذاری مجدد لازم است',
'Finished, All done' => 'پایان، همه انجام شد',
'Script finished, but not all messages have been sent yet.' => 'اسکریپت پایان یافت ولی هنوز همه پیامها فرستاده نشدند.',
'Finished this run' => 'این اجرا پایان یافت',
'(test)' => '(آزمایش)',
'Would have sent' => 'فرستاده شده',
'(test)' => '(آزمایش)',
'Would have sent' => 'فرستاده شده',
'Started' => 'آغاز شده',
'Processing has been suspended by your ISP, please try again later' => 'پردازش توسط میزبان شما متوقف شده است، لطفا بعداً دوباره سعی کنی',
'Sending in batches of' => 'فرستادن در دسته های',
'emails' => 'تایی',
'This batch will be' => 'این دسته',
'emails, because in the last' => 'تایی خواهد بود، چودن در دسته آخر ',
'emails were sent' => 'ایمیل فرستاده شد',
'Sending in batches of' => 'فرستادن در دسته های',
'emails' => 'تایی',
'In the last' => 'در آخری',
'seconds more emails were sent' => 'ثانیه ایمیلهای بیشتری فرستاده شد',
'than is currently allowed per batch' => 'از آنچه در هر دسته مجاز است',
'Sent in last run' => 'در آخرین اجرا فرستاده شد',
'Skipped in last run' => 'در آخرین اجرا رد شد',
'Processing has started,' => 'پردازش آغاز شد،',
'message(s) to process.' => 'پیام برای پردازش مانده است.',
'It is safe to click your stop button now, report will be sent by email to' => 'اگر اکنون دکمه "توقف" را بزنید مشکلی ایجاد نخواهد شد، گزارش ایمیل میشود به',
'Your webserver is running in safe_mode. Please keep this window open. It may reload several times to make sure all messages are sent.' => 'سرور وب شما در حالت "safe_mode" است. لطفا این پنجره را باز نگه دارید. ممکن است چند بار بارگذاری شود تا اطمینان حاصل شود که همه پیامها فرستاده شده اند.',
'Reports will be sent by email to' => 'گزارشها ایمیل میشوند به',
'Processing message' => 'پردازش پیام',
'Message' => 'پیام',
'is an RSS feed for' => 'یک خوراک RSS است برای',
'Looking for users' => 'جستجوی کاربرها',
'users apply for attributes, now checking lists' => 'کاربرها برای ویژگی اعما ل شده اند، اکنون بررسی فهرستها',
'No users apply for attributes' => 'کاربری برای ویژگیها اعمال نکرده است',
'looking for users who can be excluded from this mailing' => 'جستجوی کاربرهایی که میتوان از این صف پردازش کنار گذاشته شوند.',
'Process Killed by other process' => 'پردازش توسط پردازش دیگری متوقف شد',
'Found them' => 'پیدا شد',
'to process' => 'برای پردازش',
'No users to process for this batch' => 'کاربری برای پردازش در این دسته وجود ندارد',
'batch limit reached' => 'بیشینه تعداد دسته',
'Process Killed by other process' => 'پردازش توسط پردازش دیگری متوقف شد',
'Message I was working on has disappeared' => 'پیامی که بر رویش کار میکردم ناپدید شده است',
'Sending' => 'در حال فرستادن',
'It took' => 'فرستادن',
'seconds to send' => 'ثانیه طول کشید',
'Failed sending to' => 'فرستادن ناموفق بود برای',
'Unconfirmed user' => 'کاربر تایید نشده',
'Not sending to' => 'فرستاده نمیشود برای',
'already sent' => 'قبلا فرستاده شده',
'Processed' => 'پردازش شد',
'out of' => 'از',
'Hmmm, No users found to send to' => 'کاربری پیدا نشد تا برایش فرستاده شود',
'It took' => 'فرستادن این پیام',
'to send this message' => 'طول کشید',
'waiting for' => 'در حال انتظار برای',
'to make sure we don\'t exceed our limit of' => 'برای اطمینان از نگذشتن از محدوده',
'messages in' => 'پیام در',

### new in 2.9.5
'Message Sending has started' => 'فرستادن پیام آغاز شد',
'phplist has started sending the message with subject %s' => 'phplist فرستادن پیام با موضوع %s را آغاز کرده است',
'to view the progress of this message, go to %s' => 'برای دیدن میزان پیشرفت این پیام بروید به  %s',
'There have been more than 10 attempts to send to %s that have been blocked for domain throttling.' => 'تا کنون بیش از 10 بار سعی شده است تا برای %s فرستاده شود ولی به دلیل وجود گلوگاه دامنه بسته شده است.',
'Introducing extra delay to decrease throttle failures' => 'افزودن تاخیر اضافی برای کاهش اشکال گلوگاهی',
'%s is currently over throttle limit of %d per %d seconds' => 'هم اکنون %s بیشتر از حد گلوگاهی %d بر %d ثانیه است',
'not sending to ' => 'عدم ارسال برای ',
'Message Sending has finished' => 'فرستادن پیام پایان یافت',
'phplist has finished sending the message with subject %s' => 'phplist فرستادن پیام با موضوع %s را به پایان رساند',

'Sending of this message has been suspended' => 'فرستادن این پیام متوقف شده است',

# new in 2.10.1
'Less than batch size were sent, so reloading imminently' => 'تعداد فرستاده شده ها کمتر از اندازه دسته است، بنابراین فوراً دوباره بارگذاری میشود',
'Waiting for %d seconds before reloading' => 'پیش از بارگذاری دوباره، %d صبر میکنم',
'Please leave this window open. You have batch processing enabled, so it will reload several times to send the messages. Reports will be sent by email to' => 'لطفا این پنجره را باز بگذارید. شما پردازش دسته ای را فعال کرده اید، بنابراین این پنجره چند بار بارگذاری مجدد میشود تا پیامها را بفرستد. گزارش کار ایمیل میشود به',

);

?>