<?php
$lan = array(
  "This page can only be called from the commandline" => "این برگه را تنها از خط فرمان میتوان باز نمود",
  "Bounce processing error" => "خطای پردازش برگشتی",
  "Bounce Processing info" => "اطلاعات پردازش برگشتی",
  "error" => "خطا",
  "info" => "اطلاعات",
  "system message bounced, user marked unconfirmed" => "پیام سیستم برگشت خورد، کاربر نشان عدم تایید گرفت",
  "Bounced system message" => "پیام سیستم برگشت شد",
  "User marked unconfirmed" => "کاربر نشان عدم تایید گرفت",
  "View Bounce" => "دیدن برگشت",
  "Cannot create POP3 connection to" => "نمیتوانم اتصال POP3 بسازم",
  "Cannot open mailbox file" => "نمیتوان پرونده صندوق پستی را بازکنم",
  "bounces to fetch from the mailbox" => "دریافت برگشتی ها از صندوق پستی",
  "Please do not interrupt this process" => "لطفا این پردازش را متوقف نکنید",
  "bounces to process" => "برگشت پردازش میشود",
  "Processing first" => "پردازش نخستین",
  "bounces" => "برگشتیها",
  "Running in test mode, not deleting messages from mailbox" => "اجرا در حالت آزمایشی، پیامها از صندوق پستی حذف نمیشوند",
  "Processed messages will be deleted from mailbox" => "پیامهای پردازش شده از صندوق پستی حذف میشوند",
  "Deleting message" => "حذف پیام",
  "Closing mailbox, and purging messages" => "بستن صندوق پستی و پاکسازی پیامها",
  "IMAP is not included in your PHP installation, cannot continue" => "IMAP در  PHP فعال نشده، ادامه امکان پذیر نیست",
  "Check out" => "بررسی",// or 'go look', 'consult', etc.
  "Bounce mechanism not properly configured" => "مکانیزم برگشت به درستی پیکربندی نشده",
  "bounce_protocol not supported" => "bounce_protocol پشتیبانی نشده",
  "Identifying consecutive bounces" => "شناسایی برگشتهای پیاپی",
  "Nothing to do" => "کاری برای انجام نیست",
  "Process Killed by other process" => "پردازش توسط پردازش دیگری متوقف شد",
// 3 lines below = one sentence
  "User" => "کاربر",
  "has consecutive bounces" => "دارای",
  "over threshold, user marked unconfirmed" => "برگشتی پیاپی است، کاربر نشان عدم تایید گرفت",
  "Auto Unsubscribed" => "لغو اشتراک خودکار",
// 2 lines below = one sentence
  "User auto unsubscribed for" => "کاربر به دلیل",
  "consecutive bounces" => "برگشتی پیاپی لغو اشتراک خودکار شد",
// 3 lines below = one sentence
  "Identifying consecutive bounces" => "شناسایی برگشتی های پیاپی",
  "of" => "از",
  "users processed" => "کاربر پردازش شد",
  'processing first' => 'پردازش نخستین',
  'Report:' => 'گزارش:',
  'Below are users who have been marked unconfirmed. The number in [] is their userid, the number in () is the number of consecutive bounces' => 'کاربرهای زیر نشان عدم تایید گرفتند. شماره ای که در [] آمده شناسه کاربری است، شماره ای که در () آمده شمار برگشتیهای پیاپی است',
  
  ## new in 2.9.5
  'Processing bounces based on active bounce rules' => 'پردازش برگشتی ها بر پایه قانونهای برگشت فعال',
  'Auto Blacklisted' => 'به صورت خودکار وارد لیست سیاه شد',
  'User auto blacklisted for' => 'دلیل ورود خودکار کاربر به لیست سیاه',
  'bounce rule' => 'قانون برگشت',
  'system message bounced, but unknown user' => 'پیام سیستم برگشت شده، اما کاربر نامعلوم است',
  'bounces processed by advanced processing' => 'برگشتیها توسط پردازش پیشرفته پردازش شدند',
  'bounces were not matched by advanced processing rules' => 'برگشتی با قانونهای پردازش پیشرفته همخوانی نداشتند',
  'Report of advanced bounce processing:' => 'گزارش پردازی برگشتی پیشرفته:',
);
?>