<?php 
$lan = array(
  "NoRecord" => "Ingen record",
  "BackToBList" => "Tilbage til bounce-listen",
  "NotFound" => "Ikke fundet<br/>",
  "AddedToB" => "Tilf&oslash;jet %s til bouncet&aelig;ller for bruger %s<br/>",
  "NotAddedToB" => "Kunne ikke tilf&oslash;je add %s til bouncet&aelig;ller for bruger %s<br/>",
  "MadeUnconfirmed" => "Gjort bruger %s ikke-bekr&aelig;ftet<br/>",
  "MadeUserRText" => "Bruger %s kan nu modtage tekst<br/>",
  "DelUser" => "Slettet bruger %s<br/>",
  "DeletingB" => "Sletter bounce %s ..\n",
  "DoneAndLoading" => "... Udf&oslash;rt, henter n&aelig;ste bounce ...",
  "NoSRecord" => "Ingen record",
  "PossibleActions" => "Mulige handlinger:",
  "ForUser" => "For bruger med email",
  "IncreaseB" => "For&oslash;g bouncet&aelig;ller med",
  "IncreaseBNote" => "(anvend negative tal for at formindske)",
  "MarkAsUnconfirmed" => "Marker bruger som ikke-bekr&aelig;ftet",
  "MarkAsUnconfirmedNote" => "(s&aring; du kan eftersende bekr&aelig;ftelses foresp&oslash;rgslen)",
  "SetReceiveText" => "S&aelig;t bruger til at modtage tekst i stedet for HTML",
  "DelUser1" => "Slet bruger",
  "DelAndGo" => "Slet denne bounce og forts&aelig;t til den n&aelig;ste",
  "DoAbove" => "Udf&oslash;r ovenst&aring;ende",
  "BounceDetails" => "Bounce detaljer:",
  "ID" => "ID",
  "Date" => "Dato",
  "Status" => "Status",
  "Comment" => "Kommentar",
  "Header" => "Hoved",
  "Body" => "Indhold",
  
  # new in 2.9.5
  'Regular Expression' => 'Regul&aelig;rt udtryk',
  'Action' => 'Handling',
  'Memo for this rule' => 'Memo til denne regel',
  'Add new Rule' => 'Tilf&oslash;j ny regel',
  'Create New Rule based on this bounce' => 'Opret ny regel ud fra denne bounce',
);
?>