<?php
$lan = array( 
 'checklist for installation' => 'Tjekliste til installation',
 'cannot be empty' => 'kan ikke v&aelig;re tom',
 'editing' => 'Redigering',
 'save changes' => 'Gem &aelig;ndringer',
 'edit' => 'rediger',

  # added 24 May 2006
  'delete user' => 'slet bruger',
  'unconfirm user' => 'g&oslash;r bruger ikke-bekr&aelig;ftet',
  'blacklist user' => 'udeluk bruger',
  'delete user and bounce' => 'slet bruger og bounce',
  'unconfirm user and delete bounce' => 'g&oslash;r bruger ikke-bekr&aelig;ftet og slet bounce',
  'blacklist user and delete bounce' => 'udeluk bruger og slet bounce',
  'delete bounce' => 'slet bounce',
  'Website address (without http://)' => 'Hjemmeside adresse (uden http://)',
  'Domain Name of your server (for email)' => 'Dom&aelig;nenavn p&aring; din server (til email)',
  'Person in charge of this system (one email address)' => 'Person, der styrer dette system (en email adresse)',
  'How often do you want to check for a new version of PHPlist (days)' => 'Hvor ofte vil du tjekke for nye versioner af PHPlist (dage)',
  'List of people to CC in system emails (separate by commas)' => 'Liste over folk der skal have CC i system emails (adskil med komma)',
  'Who gets the reports (email address, separate multiple emails with a comma)' => 'Hvem modtager rapporterne (email adresse, adskil flere emails med komma)',
  'From email address for system messages' => 'Fra email adresse til system beskeder',
  'What name do system messages appear to come from' => 'Hvilket navn skal system beskeder foregive at komme fra',
  'Reply-to email address for system messages' => 'Svar-til email adresse til system beskeder',
  'if there is only one visible list, should it be hidden in the page and automatically
    subscribe users who sign up (0/1)' => 'hvis der kun er en synlig liste, skal den s&aring; v&aelig;re skjult p&aring; siden og automatisk
    tilf&oslash;je brugere der tilmelder sig (0/1)',
  'width of a textline field (numerical)' => 'bredde af tekstlinje feltet (nummerisk)',
  'dimensions of a textarea field (rows,columns)' => 'dimensioner p&aring; tekstfeltet (r&aelig;kker,kolonner)',
  'Does the admin get copies of subscribe, update and unsubscribe messages (0/1)' => 'Modtager admin kopier af tilmeldings-, opdaterings- og afmeldingsbeskeder (0/1)',
  'The default subscribe page when there are multiple' => 'Standard tilmeldings side n&aring;r der er flere',
  'The default HTML template to use when sending a message' => 'Standard HTML skabelon til brug ved afsendelse af en besked',
  'URL where users can subscribe' => 'URL, hvor brugere kan tilmelde sig',
  'URL where users can unsubscribe' => 'URL, hvor brugere kan afmelde sig',
  'URL where users have to confirm their subscription' => 'URL, hvor brugere skal bekr&aelig;fte deres tilmelding',
  'URL where users can update their details' => 'URL, hvor brugere kan opdatere deres detaljer',
  'URL where messages can be forwarded' => 'URL, hvor beskeder kan videresendes',
  'Subject of the message users receive when they subscribe' => 'Emne i den besked brugere modtager, n&aring;r der tilmeldes',
  'Message users receive when they subscribe' => 'Besked som brugere modtager, n&aring;r de tilmeldes',
  'Subject of the message users receive when they unsubscribe' => 'Emne i den besked brugere modtager, n&aring;r de afmeldes',
  'Message users receive when they unsubscribe' => 'Besked som brugere modtager, n&aring;r de afmeldes',
  'Subject of the message users receive after confirming their email address' => 'Emne i den besked brugere modtager efter bekr&aelig;ftelse af deres email adresse',
  'Message users receive after confirming their email address' => 'Besked brugere modtager efter bekr&aelig;ftelse af deres email adresse',
  'Subject of the message users receive when they have changed their details' => 'Emne i den besked brugere modtager, n&aring;r de har &aelig;ndret deres detaljer',
  'Message that is sent when users change their information' => 'Besked der sendes n&aring;r brugere &aelig;ndrer deres information',
  'Part of the message that is sent to their new email address when users change their information, and the email address has changed' => 'Del af beskeden der sendes til deres nye email adresse, n&aring;r brugere &aelig;ndrer deres information, og n&aring;r email adressen er blevet &aelig;ndret',
  'Part of the message that is sent to their old email address when users change their information, and the email address has changed' => 'Del af beskeden der sendes til deres gamle email adresse, n&aring;r brugere &aelig;ndrer deres information, og n&aring;r email adressen er blevet &aelig;ndret',
  'Subject of message to send when users request their personal location' => 'Emne i besked, n&aring;r brugere foresp&oslash;rger deres personlige sted',
  'Message to send when they request their personal location' => 'Besked der sendes, n&aring;r brugere foresp&oslash;rger deres personlige sted',
  'Default footer for sending a message' => 'Standard footer ved afsendelse af besked',
  'Footer used when a message has been forwarded' => 'Footer, der benyttes n&aring;r en besked er videresendt',
  'Header of public pages. The header should start with &lt;/head&gt; . You can add header elements, but don\'t add the title or other basic header elements.' => 'Header p&aring; offentlige sider. Headeren b&oslash;r starte med &lt;/head&gt; . Du kan tilf&oslash;je header elementer, men undlad at tilf&oslash;je titlen eller andre basale header elementer.',
  'Footer of public pages' => 'Footer p&aring; offentlige sider',
  'Charset for HTML messages' => 'Karakters&aelig;t til HTML beskeder',
  'Charset for Text messages' => 'Karakters&aelig;t til Tekst beskeder',
  'CSS for HTML messages without a template' => 'CSS til HTML beskeder uden en skabelon',
  'Domains that only accept text emails, one per line' => 'Dom&aelig;ner der kun accepterer tekst emails, en per linje',
  'Minimum amount of items to send in an RSS feed' => 'Minimum antal emner i en RSS feed',
  'Template for text item in RSS feeds' => 'Skabelon til tekst emne i RSS feeds',
  'Template for HTML item in RSS feeds' => 'Skabelon til HTML emne i RSS feeds',
  'Maximum amount of items to send in an RSS feed' => 'Maksimum antal emner i en RSS feed',
  'Template for separator between feeds in RSS feeds (text)' => 'Skabelon til adskiller mellem feeds i RSS feeds (tekst)',
  'Template for separator between feeds in RSS feeds (HTML)' => 'Skabelon til adskiller mellem feeds i RSS feeds (HTML)',
  'Width in px of FCKeditor Area' => 'Bredde i px p&aring; FCKeditor Area',
  'Height in px of FCKeditor Area' => 'H&oslash;jde i px p&aring; FCKeditor Area',
);
?>