<?php

$lan = array(
  'Your database is out of date, please make sure to upgrade' => 'Din database er ikke den nyeste version, venligst opgrader den',
  'Your version' => 'Din version',
  'Latest version' => 'Nyeste version',
  'phplist version' => '<a href="http://www.phplist.com">phplist</a> version',
  'Database has not been initialised' => 'Databasen er ikke blevet initialiseret',
  'go to' => 'g&aring; til',
  'Initialise Database' => 'Initialiser database',
  'to continue' => 'for at forts&aelig;tte',
  'A new version of PHPlist is available!' => 'En ny version af PHPlist er tilg&aelig;ngelig!',
  'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => 'Den nye version kan m&aring;ske have f&aring;et ordnet sikkerheds sp&oslash;rgsm&aring;l,<br/>s&aring; det anbefales at opgradere s&aring; hurtigt som muligt',
  'View what has changed' => 'Se &aelig;ndringer',
  'Download' => 'Download',
  'System Functions' => 'System funktioner',
  'Setup ' => 'Ops&aelig;tning ',
  'Check Database structure' => 'Unders&oslash;g database struktur',
  'View the eventlog' => 'Se h&aelig;ndelses loggen',
  'Configuration functions' => 'Konfigurations funktioner',
  'Configure Attributes' => 'Konfigurer attributter',
  'Control values for' => 'Kontrol v&aelig;rdier til',
  'Control values for' => 'Kontrol v&aelig;rdier til',
  'Control values for' => 'Kontrol v&aelig;rdier til',
  'Configure Subscribe pages' => 'Konfigurer tilmeldings sider',
  'List and user functions' => 'Visnings og bruger funktioner',
  'List the current lists' => 'Vis de nuv&aelig;rende lister',
  'List all Users' => 'Vis alle brugere',
  'Reconcile the user database' => 'Genopbyg bruger databasen',
  'Import Users' => 'Importer brugere',
  'Export Users' => 'Eksporter brugere',
  'Administrator functions' => 'Administrator funktioner',
  'Add, edit and remove Administrators' => 'Tilf&oslash;j, rediger og fjern administratorer',
  'Configure attributes for administrators' => 'Konfigurer attributter for administratorer',
  'Message functions' => 'Besked funktioner',
  'Configure Templates' => 'Konfigurer skabeloner',
  'List all Messages' => 'Vis alle beskeder',
  'Process the Message queue' => 'Behandl besked k&oslash;en',
  'RSS Functions' => 'RSS funktioner',
  'Get RSS feeds' => 'Hent RSS feeds',
  'View RSS items' => 'Se RSS emner',
  'Plugins' => 'Plugins',
  'Upgrade' => 'Opgrader',
'Change your details (e.g. password)' => 'Rediger dine detaljer (fx kodeord)',
'You have set TEST in config.php to 1, so it will only show what would be sent' => 'Du har sat TEST i config.php til 1, s&aring; der vises kun hvad der ville blive sendt',

  # added at a later stage
  'setup' => 'ops&aelig;tning',
  'upgrade' => 'opgrader',
  'dbcheck' => 'db-tjek',
  'eventlog' => 'h&aelig;ndelses log',
  'attributes' => 'attributter',
  'spage' => 'tilmeldings side',
  'list' => 'vis',
  'reconcileusers' => 'genopbyg brugere',
  'import' => 'import',
  'export' => 'eksport',
  'admins' => 'admins',
  'adminattributes' => 'admin attributter',
  'send' => 'send',
  'templates' => 'skabeloner',
  'processqueue' => 'behandlings kø',
  'processbounces' => 'behandl bounces',
  'getrss' => 'hent rss',
  'viewrss' => 'se rss',
  'admin' => 'admin',
  'preparesend' => 'forbered send',
  'sendprepared' => 'send forberedt',


);

?>