<?php 
$lan = array(

  'add_list' => 'Tilf&oslash;j liste', //duplicated in import1_text
  'cant_connect' => 'kan ikke forbinde til remote database',
  'no_users_to_copy' => 'Ingen brugere at kopiere, er pr&aelig;fikset korrekt?',
  'remote_server' => 'Venligst indtast info om remote server',
  'server' => 'Server:',
  'user' => 'Bruger:',
  'passwd' => 'Kodeord:',
  'database' => 'Database navn:',
  'table_prefix' => 'Tabel pr&aelig;efiks:',
  'usertable_prefix' => 'Brugertabel pr&aelig;fiks:',
  'select_lists' => 'V&aelig;lg den liste, der skal tilf&oslash;jes emails til',
  'copy_lists' => 'Kopier lister fra remote server (lister matches efter navn)',
  'users_as_html' => 'Marker nye brugere som HTML:',
  'info_overwrite_existing' => 'Hvis du v&aelig;lger "Overskriv eksisterende", vil information om en bruger blive erstattet af den importerede information. Brugere matches efter email.',
  'overwrite_existing' => 'Overskriv eksisterende:',
  'connecting_remote' => 'Opretter forbindelse til remote database',
  'getting_data' => 'Henter data fra ',
  'remote_version' => 'Remote version er',
  'remote_has' => 'Remote version har',
  'users' => 'brugere',
  'lists' => 'lister',
  'copying_lists' => 'Kopierer lister',
  'list' => 'Liste',
  'exists_locally' => 'findes lokalt',
  'created_locally' => 'oprettet lokalt',
  'remote_list' => 'Remote liste',
  'not_created' => 'ikke oprettet',
  'copying_attribs' => 'Kopierer attributter',
  'attrib' => 'Attribut',
  'copying_users' => 'Kopierer brugere',
  'overwrite_local' => 'overskriver lokal data',
  'keep_local' => 'bevarer lokal data',
  'new_user' => 'er ny bruger',
  'no_mapped_attrib' => 'Fejl, ingen attribut mappet til',
  'no_local_list' => 'Fejl, ingen lokal liste defineret til',
  'No lists available' => 'Ingen lister tilg&aelig;ngelige',
  'Done' => 'Udf&oslash;rt',
  'new users' => 'nye brugere',
  'and' => 'og',
  'existing users' => 'eksisterende brugere',
  'continue' => 'Forts&aelig;t',

);
?>