<?php
$lan = array(
  "Import emails from IMAP folders" => "Importer emails fra IMAP foldere",
  "No lists available" => "Ingen lsiter tilg&aelig;ngelige",
  "Add a list" => "Tilf&oslash;j liste",
  "personal" => "personlig",
  "email" => "email",
  "folder" => "folder",
  "date" => "dato",
  "can't connect" => "kan ikke tilslutte",
  "Processing" => "Behandler",
  "messages" => "beskeder",
  "done" => "udf&oslash;rt",
  "imap_getmailboxes failed" => "imap_getmailboxes fejlede",
  "Please enter details of the IMAP account" => "Venligst indtast detaljer om IMAP kontoen",
  "Select the headers fields to search" => "V&aelig;lg headers felterne til s&oslash;gning",
  "Select the lists to add the emails to" => "V&aelig;lg listerne, der skal have tilf&oslash;jet emails",
  "Adding users to list" => "Tilf&oslash;jer brugere til liste",
  "Mark new users as HTML" => "Marker nye brugere som HTML",
/* read lines below as sentences: if you check 'overwrite' information about a user... etc. */
  "If you check" => "Hvis du v&aelig;lger",
  "Overwrite Existing" => "Overskriv eksisterende",
  "information about a user in the database will be replaced by the imported information. Users are matched by email." => "information om en bruger i databasen vil blive erstattet med den importerede information. Brugere matches efter email.",
  "Only use complete addresses" => "Anvend kun hele adresser",
  "addresses that do not have a real name will be ignored. Otherwise all emails will be imported." => "adresser, der ikke har et rigtigt navn, vil blive ignoreret. Ellers vil alle emails blive importeret.",
  "If you choose" => "Hvis du v&aelig;lger",
  "send notification email" => "send besked email",
  "the users you are adding will be sent the request for confirmation of subscription to which they will have to reply. This is recommended, because it will identify invalid emails." => "brugerne du tilf&oslash;jer vil f&aring; tilsendt en bekr&aelig;ftelse p&aring; tilmelding, som de skal besvare. Det anbefales, fordi det vil afsl&oslash;re ugyldige emails.",
  "Send&nbsp;Notification&nbsp;email&nbsp;" => "Send&nbsp;besked&nbsp;email&nbsp;",
  "Make confirmed immediately" => "G&oslash;r bekr&aelig;ftet straks",
  "import3info" => "Der er to m&aring;der brugernes navne kan tilf&oslash;jes p&aring;,
 enten med en attribut for hele navnet eller to attributte, en til fornavn og en til efternavn.
Hvis du v&aelig;lger 'to attributter', vil navnet blive delt efter det f&oslash;rste mellemrum.",
  "Use one attribute for name" => "Benyt en attribut til navn",
  'Use two attributes for the name' => 'Benyt to attributter til navnet',
  "Attribute one" => "Attribut en",
  "Create Attribute" => "Opret attribut",
  "Attribute two" => "Attribut to",
  "Cannot continue" => "Kan ikke forts&aelig;tte",
  "ok" => "OK",
  "failed" => "fejlede",
  "Processed" => "Behandlede",
  "folders and" => "foldere og",
  "unique emails found" => "unikke emails fundet",
  "list" => "liste",
  "lists" => "lister",
  "new email was" => "ny email var",
  "new emails were" => "nye emails var",
  "email was" => "email var",
  "emails were" => "emails var",
  "All the emails already exist in the database and are members of the" => "Alle emails findes allerede i databasen og er medlemmer af",
  "succesfully imported to the database and added to" => "er blevet importeret i databasen og tilf&oslash;jet til",
  "subscribed to the" => "tilmeldt til",
  "emails already existed in the database" => "emails findes allerede i databasen",
  "Invalid Emails found." => "Ugyldige emails fundet.",
  "These records were added, but the email has been made up. You can find them by doing a search on" => "Disse records blev tilf&oslash;jet, men email adressen er opfundet. Du kan finde dem ved at s&oslash;ge efter",
  "These records were deleted. Check your source and reimport the data. Duplicates will be identified." => "Disse records blev slettet. Tjek din kilde og importer data igen. Dobbelte forekomster vil blive identificeret.",
  "No emails found" => "Ingen emails fundet",
  "Import some more emails" => "Importer flere emails",
  'Server' => 'Server',
  'User' => 'Bruger',
  'Password' => 'Kodeord',
  'Continue' => 'Forts&aelig;t',
  'Process Selected Folders' => 'Behandl valgte foldere',
);
?>