<?php
$lan = array(
  'You do not have enough priviliges to view this page' => 'Du har ikke tilladelse til at se denne side',
  'Add a user' => 'Tilf&oslash;j en bruger',
  'add user' => 'Tilf&oslash;j bruger',
  'Members of' => 'Medlem af',
  'Tag all users in this page' => 'Marker alle brugere p&aring; denne side',
  'back to this list' => 'tilbage til denne liste',
  'Download users on this list as a CSV file' => 'Download brugere fra denne liste som CSV fil',
  'Please enter a listid' => 'Venligst indtast liste id',
  'Processing' => 'Behandler',
  'users were moved to' => 'brugere blev flyttet til',
  'users were copied to' => 'brugere blev kopieret til',
  'users were deleted from this list' => 'brugere blev slettet fra denne liste',
  'Users found, click add to add this user' => 'Brugere fundet, klik tilf&oslash;j for at tilf&oslash;je denne bruger',
  'Add' => 'Tilf&oslash;j',
  'No user found with that email' => 'Ingen bruger fundet med denne emal',
  'Inserting user' => 'Inds&aelig;tter bruger',
  'User added' => 'Bruger tilf&oslash;jet',
  'Deleting' => 'Sletter',
  'Done' => 'Udf&oslash;rt',
  'Users on this list' => 'Brugere p&aring; denne liste',
  'Listing user' => 'Viser bruger',
  'to' => 'til',//in sentence 'listing user 1  to  50'
  'Listing user 1 to 50' => 'Viser bruger 1 til 50',
  'Members' => 'Medlemmer',
  'confirmed' => 'bekr&aelig;ftet',
  'tag' => 'marker',
  'del' => 'slet',
  'Delete'=>'Slet',
  '# msgs' => '# msgs',
  '# rss' => '# rss',
  'rss freq' => 'rss frekvens',
  'last sent' => 'senest sendt',
  'What to do with "Tagged" users' => 'Hvad skal der ske med "markerede" brugere',
  'This will only process the users in this page that have the "Tag" checkbox checked' => 'Det vil kun p&aring;virke de brugere p&aring; denne side, der er markeret med "markeret"',
  'delete' => 'Slet',
  'move' => 'Flyt',
  'copy' => 'Kopier',
  'nothing' => 'Ingenting',
  'to' => 'til', # as in destination
  'from this list' => 'fra denne liste',
  'What to do with all users' => 'Hvad skal der ske med alle brugere',
  'This will process all users on this list' => 'Det vil p&aring;virke alle brugere p&aring; denne liste',
  'do it' => 'g&oslash;r det',
  
  
);
?>