<?php
$lan = array(
 'Please select a message to display' => 'Venligst v&aelig;lg en besked til visning',
 'Attachments for this message' => 'Vedh&aelig;ftelser til denne besked',
 'No attachments' => 'Ingen vedh&aelig;ftelser',
 'Filename' => 'Fil navn',
 'Size' => 'St&oslash;rrelse',
 'Mime Type' => 'Mime type',
 'Description' => 'Beskrivelse',
 'Lists this message has been sent to' => 'Lister denne besked er blevet sendt til',
 'None yet' => 'Ingen endnu',
 'Send this (same) message to (a) new list(s)' => 'Send denne (samme) besked til (en) ny(e) liste(r)',
 'List is Active' => 'Liste er aktiv',
 'List is not Active' => 'Liste er ikke aktiv',
 '<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the "Requeue" function.' => '<b>Note:</b> denne besked er allerede blevet sendt til alle lister. For at eftersende den til nye brugere benyt da "S&aelig;t i k&oslash; igen" funktionen.',
 'Resend' => 'Eftersend',
 'id' => 'id',
 'subject' => 'emne',
 'fromfield' => 'fra felt',
 'tofield' => 'til felt',
 'replyto' => 'svar til',
 'message' => 'besked',
 'textmessage' => 'tekst besked',
 'footer' => 'footer',
 'entered' => 'oprettet',
 'modified' => 'redigeret',
 'embargo' => 'embargo',
 'repeatinterval' => 'gentagelses interval',
 'repeatuntil' => 'gentag indtil',
 'status' => 'status',
 'userselection' => 'bruger valg',
 'sent' => 'sendt',
 'htmlformatted' => 'html formatteret',
 'sendformat' => 'send format',
 'template' => 'skabelon',
 'processed' => 'behandlet',
 'astext' => 'som TEKST',
 'ashtml' => 'som HTML',
// 'astextandhtml' => 'as text and html', //obsolete by bug 0009687
 'aspdf' => 'som PDF',
 'astextandpdf' => 'som TEKST og PDF',
 'viewed' => 'visninger',
 'bouncecount' => 'bounce t&aelig;ller',
 'sendstart' => 'send start',
 'rsstemplate' => 'RSS skabelon',
 'owner' => 'ejer',

 # new in 2.10.1
 'edit this message' => 'Rediger denne besked',
);
?>
