<?php

$lan = array(
'Running in testmode, no emails will be sent. Check your config file.' => 'K&oslash;rer i testmode, ingen emails vil blive sendt. Tjek din config fil.',
'The following restrictions have been set by your ISP:' => 'F&oslash;lgende restriktioner er sat af din ISP:',
'Script stage' => 'Script trin',
'Finished, Nothing to do' => 'F&aelig;rdig, ingenting at g&oslash;re',
'messages sent in' => 'beskeder sendt i',
'seconds' => 'sekunder',
'invalid emails' => 'ugyldige emails',
'emails failed (will retry later)' => 'emails fejlede (vil fors&oslash;ge senere)',
'emails unconfirmed (not sent)' => 'emails ikke-bekr&aelig;ftet (ikke sendt)',
'Warning: script never reached stage 5' => 'Advarsel: script n&aring;ede aldrig trin 5',
'This may be caused by a too slow or too busy server' => 'Det kan skyldes en meget langsom eller optaget server',


'In safe mode, batches are set to a maximum of 100' => 'I safe mode s&aelig;ttes batches til et maksimum p&aring; 100',
'Running in safe mode' => 'K&oslash;rer i safe mode',
'msgs/hr' => 'besk./t',
'Reload required' => 'Genopfrisk p&aring;kr&aelig;vet',
'Finished, All done' => 'Gennemf&oslash;rt, alle udf&oslash;rt',
'Script finished, but not all messages have been sent yet.' => 'Script afsluttedes, men alle beskeder er endnu ikke blevet afsendt.',
'Finished this run' => 'F&aelig;rdiggjorde denne k&oslash;rsel',
'(test)' => '(test)',
'Would have sent' => 'Ville have sendt',
'(test)' => '(test)',
'Would have sent' => 'Ville have sendt',
'Started' => 'P&aring;begyndt',
'Processing has been suspended by your ISP, please try again later' => 'Behandling er suspenderet af din ISP, fors&oslash;g igen senere',
'Sending in batches of' => 'Sender i batches p&aring;',
'emails' => 'emails',
'This batch will be' => 'Denne batch vil v&aelig;re',
'emails, because in the last' => 'emails, fordi i den seneste',
'emails were sent' => 'emails blev afsendt',
'Sending in batches of' => 'Sender i batches p&aring;',
'emails' => 'emails',
'In the last' => 'I den seneste',
'seconds more emails were sent' => 'sekunder vil flere emails blive sendt',
'than is currently allowed per batch' => 'end det i &oslash;jeblikket er tilladt per batch',
'Sent in last run' => 'Sendt i den seneste k&oslash;rsel',
'Skipped in last run' => 'Hoppet over i den seneste k&oslash;rsel',
'Processing has started,' => 'Behandling er startet,',
'message(s) to process.' => 'besked(er) at behandle.',
'It is safe to click your stop button now, report will be sent by email to' => 'Det er sikkert at klikke din "stop" knap nu, en rapport vil blive sendt til',
'Your webserver is running in safe_mode. Please keep this window open. It may reload several times to make sure all messages are sent.' => 'Din webserver k&oslash;rer i "safe_mode". Venligst hold dette vindue &aring;ben. Det vil m&aring;ske genopfriske adskillige gange for at v&aelig;re sikker p&aring; at alle beskeder er blevet sendt.',
'Reports will be sent by email to' => 'Rapporter vil blive sendt via email til',
'Processing message' => 'Behandler besked',
'Message' => 'Besked',
'is an RSS feed for' => 'er en RSS feed til',
'Looking for users' => 'S&oslash;ger efter brugere',
'users apply for attributes, now checking lists' => 'brugere passer til attributter, tjekker nu lister',
'No users apply for attributes' => 'Ingen brugere passer til attributter',
'looking for users who can be excluded from this mailing' => 's&oslash;ger efter brugere, der kan ekskluderes fra denne k&oslash;rsel',
'Process Killed by other process' => 'Behandling stoppet af anden proces',
'Found them' => 'Fandt dem',
'to process' => 'at behandle',
'No users to process for this batch' => 'Ingen brugere at behandle i denne batch',
'batch limit reached' => 'batch gr&aelig;nse n&aring;et',
'Process Killed by other process' => 'Behandling stoppet af anden proces',
'Message I was working on has disappeared' => 'Beskeden jeg arbejdede med er forsvundet',
'Sending' => 'Sender',
'It took' => 'Det tog',
'seconds to send' => 'sekunder at sende',
'Failed sending to' => 'Fejlede forsendelse til',
'Unconfirmed user' => 'Ikke-bekr&aelig;ftet bruger',
'Not sending to' => 'Sender ikke til',
'already sent' => 'allerede sendt',
'Processed' => 'Behandlet',
'out of' => 'ud af',
'Hmmm, No users found to send to' => 'Hov, ingen brugere fundet at sende til',
'It took' => 'Det tog',
'to send this message' => 'at sende denne besked',
'waiting for' => 'venter p&aring;',
'to make sure we don\'t exceed our limit of' => 'for at sikre os at vi ikke overskrider vores gr&aelig;nse p&aring;',
'messages in' => 'beskeder i',

### new in 2.9.5
'Message Sending has started' => 'Besked afsendelse er begyndt',
'phplist has started sending the message with subject %s' => 'phplist har begyndt afsendelsen af beskeden med emnet %s',
'to view the progress of this message, go to %s' => 'for at se denne beskeds udvikling, g&aring; til %s',
'There have been more than 10 attempts to send to %s that have been blocked for domain throttling.' => 'Der har v&aelig;ret flere end 10 fors&oslash;g p&aring; at sende til %s, som er blevet blokeret for dom&aelig;ne throttling.',
'Introducing extra delay to decrease throttle failures' => 'Introducerer ekstra forsinkelse for at mindske throttle fejl',
'%s is currently over throttle limit of %d per %d seconds' => '%s er i &oslash;jeblikket over throttle gr&aelig;nsen p&aring; %d per %d sekunder',
'not sending to ' => 'sender ikke til ',
'Message Sending has finished' => 'Besked afsendelse er gennemf&oslash;rt',
'phplist has finished sending the message with subject %s' => 'phplist har gennemf&oslash;rt afsendelsen af beskeden med emnet %s',

'Sending of this message has been suspended' => 'Afsendelse af denne besked er blevet suspenderet',

# new in 2.10.1
'Less than batch size were sent, so reloading imminently' => 'Mindre end batch st&oslash;rrelsen blev sendt, s&aring; der reloades med det samme',
'Waiting for %d seconds before reloading' => 'Venter i %d sekunder f&oslash;r der reloades',
'Please leave this window open. You have batch processing enabled, so it will reload several times to send the messages. Reports will be sent by email to' => 'Venligst lad dette vindue forblive &aring;ben. Du har batch k&oslash;rsler i gang, s&aring; der vil blive reloadet flere gange for at sende beskederne. Rapport vil blive sendt til',

);

?>