<?php 
$lan = array(
  "NoRecord" => "Nessun record",
  "BackToBList" => "Torna alla lista dei rimbalzi",
  "NotFound" => "Non trovato<br/>",
  "AddedToB" => "Aggiunto %s al conteggio dei rimbalzi per utente%s<br/>",
  "NotAddedToB" => "Impossibile aggiungere %s al conteggio dei rimbalzi per utente %s<br/>",
  "MadeUnconfirmed" => "Rendi l'utente %s non confermato<br/>",
  "MadeUserRText" => "Abilita la ricezione di testo per questo utente<br/>",
  "DelUser" => "Cancella utente %s<br/>",
  "DeletingB" => "Cancellazione rimbalzo %s ..\n",
  "DoneAndLoading" => "..Fatto, richiamo il rimbalzo successivo..",
  "NoSRecord" => "Nessun record",
  "PossibleActions" => "Azioni possibili:",
  "ForUser" => "Per utente con email",
  "IncreaseB" => "Incrementare il conteggio dei rimbalzi con",
  "IncreaseBNote" => "(usa numeri negativi a decrescere)",
  "MarkAsUnconfirmed" => "Segna l\'utente come non confermato",
  "MarkAsUnconfirmedNote" => "(in modo da poter reinviare la richiesta di conferma)",
  "SetReceiveText" => "Imposta la ricezione di testo anzich&eacuto; HTML",
  "DelUser1" => "Cancella utente",
  "DelAndGo" => "Cancella questo rimbalzo e vai al successivo",
  "DoAbove" => "Esegui superiore",
  "BounceDetails" => "Dettagli rimbalzo:",
  "ID" => "ID",
  "Date" => "Data",
  "Status" => "Status",
  "Comment" => "Commento",
  "Header" => "Intestazione",
  "Body" => "Body",
  
  # new in 2.9.5
  'Regular Expression' => 'Espressione regolare',
  'Action' => 'Azione',
  'Memo for this rule' => 'Memo per questa regola',
  'Add new Rule' => 'Aggiungi nuova regola',
  'Create New Rule based on this bounce' => 'Crea una nuova regola basata su questo rimbalzo',
);
?>
