<?php
$lan = array( 
 'checklist for installation' => 'Checklist per l\'installazione',
 'cannot be empty' => 'non pu&ograve; essere lasciato vuoto',
 'editing' => 'Modificando...',
 'save changes' => 'Salva le modifiche',
 'edit' => 'modifica',

  # added 24 May 2006
  'delete user' => 'elimina utente',
  'unconfirm user' => 'utente non confermato',
  'blacklist user' => 'utente in blacklist',
  'delete user and bounce' => 'elimina utente e rimbalzo',
  'unconfirm user and delete bounce' => 'de-conferma l\'utente ed elimina rimbalzo',
  'blacklist user and delete bounce' => 'aggiungi l\'utente alla blacklist ed elimina rimbalzo',
  'delete bounce' => 'elimina rimbalzo',
  'Website address (without http://)' => 'Indirizzo internet (senza http://)',
  'Domain Name of your server (for email)' => 'Nome di dominio del tuo server (per email)',
  'Person in charge of this system (one email address)' => 'Amministratore del server (un solo indirizzo email)',
  'Ogni quanto vuoi controllare la tua versione di phplist (in giorni)' => 'Ogni quanto tempo vuoi controllare la tua versione di phplist (giorni)',
  'List of people to CC in system emails (separate by commas)' => 'Lista delle persone che riceveranno in CC le email di sistema (separate da virgole)',
  'Who gets the reports (email address, separate multiple emails with a comma)' => 'Chi riceve i report (indirizzo email, separa i vari indirizzi email con una virgola)',
  'From email address for system messages' => 'Indirizzo mittente delle email di sistema',
  'What name do system messages appear to come from' => 'Nome mittente delle email di sistema',
  'Reply-to email address for system messages' => 'Indirizzo di risposta alle email di sistema',
  'if there is only one visible list, should it be hidden in the page and automatically
    subscribe users who sign up (0/1)' => 'se c\'&egrave; solo un elenco visibile, essa dovrebbe essere nascosta nella pagina, ed iscrivere automaticamente gli utenti che si registrano (0/1)',
  'width of a textline field (numerical)' => 'larghezza del campo di testo (numerico)',
  'dimensions of a textarea field (rows,columns)' => 'dimensioni del campo di testo (righe,colonne)',
  'Does the admin get copies of subscribe, update and unsubscribe messages (0/1)' => 'L\'amministratore riceve copie delle iscrizioni, degli aggiornamenti e delle cancellazioni delle iscrizioni (0/1)',
  'The default subscribe page when there are multiple' => 'Pagina di iscrizione predefinita, nel caso ce ne siano multiple',
  'The default HTML template to use when sending a message' => 'Template HTML predefinito per inviare email',
  'URL where users can subscribe' => 'URL dove gli utenti possono iscriversi',
  'URL where users can unsubscribe' => 'URL dove gli utenti possono cancellare l\'iscrizione',
  'URL where users have to confirm their subscription' => 'URL dove gli utenti possono confermare la loro iscrizione',
  'URL where users can update their details' => 'URL dove gli utenti possono inserire i propri dettagli',
  'URL where messages can be forwarded' => 'URL a cui i messaggi possono essere inoltrati',
  'Subject of the message users receive when they subscribe' => 'Oggetto del messaggio che gli utenti ricevono all\'iscrizione',
  'Message users receive when they subscribe' => 'Testo del messaggio che gli utenti ricevono all\'iscrizione',
  'Subject of the message users receive when they unsubscribe' => 'Oggetto del messaggio che gli utenti ricevono quando cancellano l\'iscrizione',
  'Message users receive when they unsubscribe' => 'Testo del messaggio che gli utenti ricevono quando cancellano l\'iscrizione',
  'Subject of the message users receive after confirming their email address' => 'Oggetto del messagio che gli utenti ricevono una volta confermato il loro indirizzo email',
  'Message users receive after confirming their email address' => 'Testo del messaggio che gli utenti ricevono dopo aver confermato il loro indirizzo email',
  'Subject of the message users receive when they have changed their details' => 'Oggetto del messaggio che gli utenti ricevono dopo aver modificato i loro dettagli',
  'Message that is sent when users change their information' => 'Messaggio inviato quando gli utenti modificano le loro informazioni',
  'Part of the message that is sent to their new email address when users change their information, and the email address has changed' => 'Parte del messaggio inviato al nuovo indirizzo email quando gli utenti modificano le loro informazioni e l\'indirizzo email &egrave; cambiato',
  'Part of the message that is sent to their old email address when users change their information, and the email address has changed' => 'Parte del messaggio inviato al vecchio indirizzo email quando gli utenti modificano le loro informazioni e l\'indirizzo email &egrave; cambiato',
  'Subject of message to send when users request their personal location' => 'Oggetto del messaggio da inviare quando gli utenti richiedono la loro località',
  'Message to send when they request their personal location' => 'Messaggio da inviare quando gli utenti richiedono la loro località',
  'Default footer for sending a message' => 'Footer predefinito per i messaggi email',
  'Footer used when a message has been forwarded' => 'Footer utilizzato quando un messaggio viene inoltrato',
  'Header of public pages. The header should start with &lt;/head&gt; . You can add header elements, but don\'t add the title or other basic header elements.' => 'Titolo delle pagine pubbliche. Il titolo dovrebbe iniziare con &lt;/head&gt;. &Egrave possibile aggiungere elementi all\'intestazione, ma non il titolo o altri elementi di base del titolo.',
  'Footer of public pages' => 'Footer delle pagine pubbliche',
  'Charset for HTML messages' => 'Charset per messaggi HTML',
  'Charset for Text messages' => 'Charset per messaggi di testo',
  'CSS for HTML messages without a template' => 'CSS per messaggi HTML senza template',
  'Domains that only accept text emails, one per line' => 'Domini che accettano solo email di testo, uno per riga',
  'Minimum amount of items to send in an RSS feed' => 'Numero minimo di elementi da inviare in un feed RSS',
  'Template for text item in RSS feeds' => 'Template per gli elementi di testo nei feed RSS',
  'Template for HTML item in RSS feeds' => 'Template per gli elementi HTML nei feed RSS',
  'Maximum amount of items to send in an RSS feed' => 'Numero massimo di elementi da inviare in un feed RSS',
  'Template for separator between feeds in RSS feeds (text)' => 'Template per il separatore tra feed RSS (testo)',
  'Template for separator between feeds in RSS feeds (HTML)' => 'Template per il separatore tra feed RSS (HTML)',
  'Width in px of FCKeditor Area' => 'Larghezza in in px dell\'area FCKeditor',
  'Height in px of FCKeditor Area' => 'Altezza in px dell\'area FCKeditor',
);
?>
