<?php

$lan = array(
'Your database is out of date, please make sure to upgrade' => 'Il tuo database &egrave obsoleto, per favore effettua l\'upgrade',
  'Your version' => 'Versione corrente',
  'Latest version' => 'Ultima versione',
  'phplist version' => 'Versione <a href="http://www.phplist.com">phplist</a> ',
  'Database has not been initialised' => 'Il database non &egrave; stato inizializzato',
  'go to' => 'vai a',
  'Initialise Database' => 'Inizializza Database',
  'to continue' => 'per continuare',
  'A new version of PHPlist is available!' => '&Egrave; disponibile una nuova versione di PHPlist!',
    'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => 'La nuova versione potrebbe risolvere alcuni problemi di sicurezza,<br/>&egrave; consigliabile effettuare l\'upgrade quanto prima',
  'View what has changed' => 'Visualizza le modifiche',
  'Download' => 'Download',
  'System Functions' => 'Funzioni di sistema',
  'Setup ' => 'Impostazioni',
  'Check Database structure' => 'Visualizza la struttura del database',
  'View the eventlog' => 'Visualizza il log degli eventi',
  'Configuration functions' => 'Funzioni di configurazione',
  'Configure Attributes' => 'Attributi di configurazione',
  'Control values for' => 'Valori di controllo per',
  'Control values for' => 'Valori di controllo per',
  'Control values for' => 'Valori di controllo per',
  'Configure Subscribe pages' => 'Configura pagina di iscrizione',
  'List and user functions' => 'Lista e funzioni utente',
  'List the current lists' => 'Elenco delle correnti liste',
  'List all Users' => 'Elenca tutti gli utenti',
  'Reconcile the user database' => 'Riconcilia il database degli utenti',
  'Import Users' => 'Importa utenti',
  'Export Users' => 'Esporta utenti',
  'Administrator functions' => 'Funzioni amministratore',
  'Add, edit and remove Administrators' => 'Aggiungi, modifica e cancella amministratori',
  'Configure attributes for administrators' => 'Configura gli attributi degli amministratori',
  'Message functions' => 'Funzioni messaggio',
  'Configure Templates' => 'Configura templates',
  'List all Messages' => 'Elenca tutti i messaggi',
  'Process the Message queue' => 'Processa la coda dei messaggi',
  'RSS Functions' => 'Funzioni RSS',
  'Get RSS feeds' => 'Ricevi feed RSS',
  'View RSS items' => 'Visualizza elementi RSS',
  'Plugins' => 'Plugins',
  'Upgrade' => 'Upgrade',
'Change your details (e.g. password)' => 'Cambia i tuoi dettagli (ad esempio la password)',
'You have set TEST in config.php to 1, so it will only show what would be sent' => 'Hai impostato TEST in config.php a 1, perci&ograve; ti sar&agrave; mostrato solo quello che dovrebbe essere spedito',

  # added at a later stage
  'setup' => 'Setup',
  'upgrade' => 'Upgrade',
  'dbcheck' => 'Controlla db',
  'eventlog' => 'Log eventi',
  'attributes' => 'Attributi',
  'spage' => 'Pag iscrizione',
  'list' => 'Lista',
  'reconcileusers' => 'Riconcilia utenti',
  'import' => 'Importa',
  'export' => 'Esporta',
  'admins' => 'Amministratori',
  'adminattributes' => 'Attributi amministratore',
  'send' => 'Spedisci',
  'templates' => 'Templates',
  'processqueue' => 'Coda processi',
  'processbounces' => 'Processa rimbalzi',
  'getrss' => 'Ricevi rss',
  'viewrss' => 'Visualizza rss',
  'admin' => 'Amministratore',
  'preparesend' => 'Predefinisci spedizione',
  'sendprepared' => 'Spedisci messaggi predefiniti',


);

?>
