<?php 
$lan = array(

  'add_list' => 'Aggiungi una lista', //duplicated in import1_text
  'cant_connect' => 'impossibile connettersi al database remoto',
  'no_users_to_copy' => 'Nessun utente da copiare, il prefisso &egrave; corretto?',
  'remote_server' => 'Per favore immetti i dati del server remoto',
  'server' => 'Server:',
  'user' => 'Utente:',
  'passwd' => 'Password:',
  'database' => 'Nome database:',
  'table_prefix' => 'Prefisso tabella:',
  'usertable_prefix' => 'Prefisso utente tabella:',
  'select_lists' => 'Seleziona le liste a cui aggiungere le email',
  'copy_lists' => 'Copia le liste da server remoto (le liste saranno abbinate per nome)',
  'users_as_html' => 'Imposta i nuovi utenti per HTML:',
  'info_overwrite_existing' => 'Se imposti "Sovrascrivi esistente", le informazioni dell\'utente presenti nel database saranno sostituite da quelle importate. Gli utenti sono abbinati per email.',
  'overwrite_existing' => 'Sovrascrivi esistente:',
  'connecting_remote' => 'Connessione al database remoto',
  'getting_data' => 'Ottenendo dati da',
  'remote_version' => 'La versione remota &egrave;',
  'remote_has' => 'la versione remota ha',
  'users' => 'utenti',
  'lists' => 'liste',
  'copying_lists' => 'Copiando le liste',
  'list' => 'Lista',
  'exists_locally' => 'esiste in locale',
  'created_locally' => 'creato in locale',
  'remote_list' => 'Lista remota',
  'not_created' => 'non creato',
  'copying_attribs' => 'Copiando gli attributi',
  'attrib' => 'Attributo',
  'copying_users' => 'Copiando gli utenti',
  'overwrite_local' => 'sovrascrivendo dati locali',
  'keep_local' => 'salvando dati locali',
  'new_user' => '&egrave; un nuovo utente',
  'no_mapped_attrib' => 'Errore, attributi non rilevati per',
  'no_local_list' => 'Errore, nessuna lista lcoale definita per',
  'No lists available' => 'Nessuna lista disponibile',
  'Done' => 'Fatto',
  'new users' => 'nuovi utenti',
  'and' => 'e',
  'existing users' => 'utenti esistenti',
  'continue' => 'Continua',

);
?>
