<?php
$lan = array(
  'You do not have enough priviliges to view this page' => 'Non hai privilegi sufficienti per visualizzare questa pagina',
  'Add a user' => 'Aggiungi un utente',
  'add user' => 'Aggiungi utente',
  'Members of' => 'Membri di',
  'Tag all users in this page' => 'Tagga tutti gli utenti in questa pagina',
  'back to this list' => 'torna alla lista',
  'Download users on this list as a CSV file' => 'Scarica gli utenti di questa lista come un file CSV',
  'Please enter a listid' => 'Per favore inserisci un listid',
  'Processing' => 'Processo',
  'users were moved to' => 'gli utenti sono stati spostati in',
  'users were copied to' => 'gli utenti sono stati copiati in',
  'users were deleted from this list' => 'utenti eliminati da questa lista',
  'Users found, click add to add this user' => 'Utenti trovati, clicca su "aggiungi" per aggiungere questo utente',
  'Add' => 'Aggiungi',
  'No user found with that email' => 'Nessun utente trovato con questa mail',
  'Inserting user' => 'Inserisco utente',
  'User added' => 'Utente aggiunto',
  'Deleting' => 'Elimino',
  'Done' => 'Fatto',
  'Users on this list' => 'Utenti su questa lista',
  'Listing user' => 'Elenco utenti',
  'to' => 'a',//in sentence 'listing user 1  to  50'
  'Listing user 1 to 50' => 'Elenco utenti da 1 a 50',
  'Members' => 'Membri',
  'confirmed' => 'confermato',
  'tag' => 'tag',
  'del' => 'canc',
  'Delete'=>'Cancella',
  '# msgs' => '# msgs',
  '# rss' => '# rss',
  'rss freq' => 'rss freq',
  'last sent' => 'ultimo inviato',
  'What to do with "Tagged" users' => 'Cosa fare con gli utenti "Taggati"',
  'This will only process the users in this page that have the "Tag" checkbox checked' => 'Questo processer&agrave; solo gli utenti in questa pagina che hanno la spunta "tag" selezionata',
  'delete' => 'Elimina',
  'move' => 'Sposta',
  'copy' => 'Copia',
  'nothing' => 'Niente',
  'to' => 'in', # as in destination
  'from this list' => 'da questa lista',
  'What to do with all users' => 'Cosa fare con tutti gli utenti',
  'This will process all users on this list' => 'Questo processer&agrave; tutti gli utenti su questa lista',
  'do it' => 'do it',
  
  
);
?>