<?php
$lan = array(
 'Please select a message to display' => 'Prego selezionare un messagio da visualizzare',
 'Attachments for this message' => 'Allegati per questo messaggio',
 'No attachments' => 'Nessun Allegato',
 'Filename' => 'Filename',
 'Size' => 'Dimensione',
 'Mime Type' => 'Mime Type',
 'Description' => 'Descrizione',
 'Lists this message has been sent to' => 'Liste a cui questo messaggio &egrave; stato inviato',
 'None yet' => 'Ancora nessuno',
 'Send this (same) message to (a) new list(s)' => 'Invia questo (stesso) messaggio a (una) nuova lista/e',
 'List is Active' => 'Lista Attiva',
 'List is not Active' => 'Lista non Attiva',
 '<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the "Requeue" function.' => '<b>Nota:</b> questo messaggio &egrave; gi&agrave; stato inviato a tutte le liste. Per inviarlo ai nuovi utenti usa la funzione "rimetti in coda"',
 'Resend' => 'Invia di nuovo',
 'id' => 'id',
 'subject' => 'oggetto',
 'fromfield' => 'mittente',
 'tofield' => 'destinatario',
 'replyto' => 'rispondi a',
 'message' => 'messaggio',
 'textmessage' => 'messaggio di testo',
 'footer' => 'footer',
 'entered' => 'immesso',
 'modified' => 'modificato',
 'embargo' => 'blocco',
 'repeatinterval' => 'intervallo di ripetizione',
 'repeatuntil' => 'ripeti fino a',
 'status' => 'status',
 'userselection' => 'selezione utente',
 'sent' => 'inviato',
 'htmlformatted' => 'html formattato',
 'sendformat' => 'formato di invio',
 'template' => 'template',
 'processed' => 'processato',
 'astext' => 'come testo',
 'ashtml' => 'come html',
// 'astextandhtml' => 'as text and html', //obsolete by bug 0009687
 'aspdf' => 'come pdf',
 'astextandpdf' => 'come testo e pdf',
 'viewed' => 'visualizzato',
 'bouncecount' => 'conteggio rimbalzo',
 'sendstart' => 'inizio invio',
 'rsstemplate' => 'RSS template',
 'owner' => 'proprietario',

 # new in 2.10.1
 'edit this message' => 'Modifica questo messaggio',
);
?>
