<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'ISO-8859-1';
$strName                = 'ÇáÇÓã';
$strAddress             = 'ÇáÚäæÇä';
$strEmail               = 'ÇáÈÑíÏ ÇáÅáßÊÑæäí';
$strTown                = 'ÇáãÏíäÉ';
$strPostcode            = 'ÇáÑãÒ ÇáÈÑíÏí';
$strSubscribeInfo       = 'ÇÔÑÊß ÈŞÇÆãÉ ÃæÚÏÉ ŞæÇÆã ãä ÎáÇá ÇáÍŞá ÃÏäÇå';
$strRequired            = 'ÍŞá ãØáæÈ';
$strSubscribeTitle      = 'ÔÊÑß ÈŞÇÆãÊäÇ ÇáÈÑíÏíÉ';
$strPleaseSelect        = 'ÍÏÏ ÇáŞÇÆãÉ ÇáÊí ÊÑíÏ ÇáÇÔÊÑÇß ÈåÇ';
$strSubmit              = 'ÇáÇÔÊÑß ÈÇáŞÇÆãÉ ÇáãÍÏÏÉ';
$strNotAvailable        = 'ÚĞÑÇğ áÇíæÌÏ ÍÇáíÇğ ŞæÇÆã';
$strEnterName           = 'ÇáÑÌÇÁ ÅÏÎÇá ÇáÇÓã';
$strEnterEmail          = 'ÇáÑÌÇÁ ÅÏÎÇá ÈÑíÏ ÅáßÊÑæäí ÍŞíŞí';
$strConfirmEmail        = 'ÊÃßíÏ ÈÑíÏß ÇáÅáßÊÑæäí';
$strInvalidHostInEmail  = 'ÚĞÑÇğ, ÇáÅÑÓÇá áåĞÇ ÇáÚäæÇä ãÊÚĞÑ, ÇáÑÌÇÁ ÇáÊÃßÏ ãä ÇáÈÑíÏ ÇáÅáßÊÑæäí';
$strEnterList           = 'ÇáÑÌÇÁ ÊÍÏíÏ ŞÇÆãÉ ááÇÔÊÑÇß ÈåÇ';
$strPleaseEnter         = 'ÇáÑÌÇÁ ÅÏÎÇá';
# the thanks message can contain placeholders
#$strThanks              = 'ÍÖÑÉ [FIRST NAME], <br/>ÔßÑÇğ áß áÇÔÊÑÇßß ÈŞÇÆãÊäÇ ÇáÈÑíÏíÉ.';
$strThanks              = 'ÔßÑÇğ áß áÇÔÊÑÇßß ÈŞÇÆãÊäÇ ÇáÈÑíÏíÉ.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'ÈÑíÏß ÇáÅáßÊÑæäí [email] ÊãÊ ÅÖÇİÊå áäÙÇãäÇ. ÓÊÊã ãÑÇÓáÊß ÈÚÏ Şáíá ÈÑÇÈØ ÊÃßíÏ ÇáÇÔÊÑÇß ááŞæÇÆã ÇáÊí ÇÔÊÑßÊ ÈåÇ.';
$strEmailConfirmation   = 'ÊãÊ ÅÖÇİÉ ÚäæÇäß ÇáÈÑíÏí áäÙÇãäÇ. ÓÊÊã ãÇÑÓáÊß ÈÚÏ Şáíá ãÚ ØáÈ ÊÃßíÏ ÇáÇÔÊÑÇß. ÇáÑÌÇÁ ÊÃßíÏ ÇáÇÔÊÑÇß ÚÈÑ ÇáÖÛÙ Úáì ÇáÑÇÈØ İí Êáß ÇáÑÓÇáÉ';
$strEmailFailed          = 'ÚĞÑÇğ, ÅÑÓÇá ÑÓÇáÉ ÊÃßíÏ ÇáÇÔÊÑÇß İÔáÊ, ÇáÑÌÇÁ ÇáÖÛØ Úáì "ÊÌÏíÏ" ááãÍÇæáÉ ãä ÌÏíÏ. ÅĞÇ ÈŞíÊ áÇ ÊÚãá, İÑÈãÇ ÈÓÈÈ æÖÚß Úáì "ÇáŞÇÆãÉ ÇáÓæÏÇÁ", æåĞÇ íÚäí Ãäå áÇíãßäß ÇÓÊŞÈÇá ÈÑíÏäÇ. İí åĞå ÇáÍÇáÉ, ÑÇÓá ÇáÅÏÇÑÉ.';
$strUnsubscribeTitle    = 'ÅáÛÇÁ ÇáÇÔÊÑß ÈŞÇÆãÊäÇ ÇáÈÑíÏíÉ';
$strUnsubscribeDone     = 'áŞÏ Êã ÅáÛÇÁ ÇÔÊÑÇßß ãä ŞÇÆãÊäÇ ÇáÈÑíÏíÉ æÓæİ íÊã ÅÑÓÇá ÇáÊÃßíÏ ÈÚÏ Şáíá.';
$strBack                = 'ÚæÏÉ';
$strUnsubscribeInfo     = 'ÅáÛÇÁ ÇáÇÔÊÑÇß ÈŞÇÆãÊäÇ ÇáÈÑíÏíÉ';
$strContinue            = 'ÇÓÊãÑÇÑ';
$strUnsubscribeSelect   = 'ÇáÑÌÇÁ ÇÎÊíÇÑ ÇáŞÇÆãÉ ÇáÊí ÊÑíÏ ÅáÛÇÁ ÇáÇÔÊÑÇß ãäåÇ';
$strAllLists            = 'ÌãíÚ ÇáŞæÇÆã';
$strNoLists             = 'æáÇ æÇÍÏÉ';
$strUnsubscribeRequestForReason = 'äÚÊĞÑ áæÌæÏß ÛíÑ ÑÇÛÈ ÈÇÓÊãÑÇÑ ÇÔÊÑÇßß ãÚäÇ. áãÓÇÚÏÊäÇ Úáì ÊÍÓíÊ ÎÏãÇÊäÇ, Óäßæä ããÊäíä áãÚÑİÉ ÇáÓÈÈ:';
$strUnsubscribeFinalInfo = '<br/><b>ÇáÑÌÇÁ ãáÇÍÙÉ</b>: åĞå ÇáÕİÍÉ áÅíŞÇİ ÅÑÓÇá ÇáÑÓÇÆá ãä äÙÇãäÇ <b>äåÇÆíÇğ</b>. ÅĞÇ ÃÑÏÊ ÊÛííÑ ÚäæÇä ÈÑíÏß ÇáÅáßÊÑæäí, Ãæ ÅĞÇ ÃÑÏÊ ÊÛííÑ ÇáŞÇÆãÉ ÇáãÔÊÑß ÈåÇ, ÇáÑÌÇÁ <a href="[PREFERENCESURL]">ÊÍÏíË ãÚáæãÇÊß</a> ÈÏáÇğ';
$strNoListsFound        = 'ÚĞÑÇğ, ÃäÊ ÛíÑ ãÔÊÑß ÈÃí ŞÇÆãÉ ãä åĞÇ ÇáÈÑíÏ ÇáÅáßÊÑæäí';
$strResubmit            = 'ÅÚÇÏÉ ÅÑÓÇá ÇáÑÓÇáÉ';
$strUnsubscribeSubmit   = 'ÅáÛÇÁ ÇáÇÔÊÑÇß ãä ÇáŞæÇÆã ÇáãÍÏÏÉ';
$strValuesMissing       = 'ÇáŞíã ÇáÊÇáíÉ ÛíÑ ãÍÏÏÉ';
$strConfirmInfo         = 'ÔßÑÇğ áÊÃßíÏ ÇÔÊÑÇßß ÈŞæÇÆãäÇ. ÇáŞæÇÆã ÇáãÔÊÑß ÈåÇ ãÓÑæÏÉ ÃÏäÇå';
$strConfirmTitle        = 'PHPlist ÕİÍÉ ÊÃßíÏ ÚÖæíÉ';
$strUserNotFound        = 'ÇáãÓÊÎÏã ÛíÑ ãæÌæÏ';
$strUserAlreadyInitialised = 'ÚĞÑÇğ, ßáãÉ ÇáÓÑ ŞÏ Êã ÅÑÓÇáåÇ';
$strConfirmFailInfo     = 'ÚĞÑÇğ, ØáÈ ÊÃßíÏ ÇáÇÔÊÑÇß ÛíÑ ãæÌæÏ. ÇáÑÌÇÁ ÇáÊÃßÏ ãä ÇÓÊÎÏÇã Úä ÇáÚäæÇä ßÇãáÇğ ßãÇ Êã æÖÚå ÈÇáÑÓÇáÉ ÇáÊí ÃõÑÓáÊ áß. ÃÍíÇäÇğ åĞÇ ÇáÚäæÇä íÊßÈ Úáì ÚÏÉ ÃÓØÑ.';
$strPreferHTMLEmail     = 'ÃİÖá ÇÓÊŞÈÇá ÇáÑÓÇáÆá ÈÕíÛÉ HTML';
$strPreferTextEmail     = 'ÃİÖá ÇÓÊŞÈÇá ÇáÑÓÇáÆá ÈÕíÛÉ äÕ';
$strPreferredFormat      = 'ÇáÕíÛÉ ÇáãİÖáÉ ááÑÓÇÆá:';
$strText                 = 'äÕ';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'ÊÍÏíË ÇáÅÚÏÇÏÇÊ';
$strPreferencesInfo     = 'ÇáÑÌÇÁ ÇáÊÃßÏ ãä ÇáãÚáæãÇÊ ÃÏäÇå æÇáÖÛØ Úáì ÒÑ "ÊÍÏíË"';
$strUpdatePreferences   = 'ÊÍÏíË';
$strPreferencesEmailChanged = 'ÈÑíÏß ÇáÅáßÊÑæäí Êã ÊÛííÑå. ÇáÑÌÇÁ ÇáÖÛØ Úáì ÇáÑÇÈØ İí ÇáÑÓÇáÉ ÇáÊí ÃÑÓáÊ áÊÃßíÏ ÚäæÇä ÈÑíÏß ÇáÅáßÊÑæäí ÇáÌÏíÏ';
$strYouAreBlacklisted = 'ÈÑíÏß ÇáÅáßÊÑæäí ãæÌæÏ İí "ÇáŞÇÆãÉ ÇáÓæÏÇÁ", Ãí Ãäß áä Êßæä ŞÇÏÑÇğ Úáì ØáÈ ÅÑÓÇá ÑÓÇÆá ãä äÙÇãäÇ. <br/>
áÇÓÊŞÈÇá ÇáÑÓÇÆá ãä ÌÏíÏ, íÌÈ ÇáÊÚÏíá íÏæíÇğ ãä ŞÈá ÇáãÏíÑ. ÇáÑÌÇÁ ãÑÇÓáÊäÇ ãæÖÍÇğ ÑÛÈÊß İí ÇÓÊŞÈÇá ÇáÑÓÇÆá ãä ÌÏíÏ, æÓäŞæã ÈÅÒÇáÉ ÈÑíÏß ãä ÇáŞÇÆãÉ ÇáÓæÏÇÁ. ';
$strPreferencesNotificationSent = 'ÓíÊã ãÑÇÓáÊß áÅÚáÇãß ÈÇáÊÛííÑÇÊ';
$strPreferencesUpdated = 'ÔßÑÇğ. áŞÏ Êã ÊÚÏíá ÇáãÚáæãÇÊ.';
$strClickHere          = 'ÇÖÛØ åäÇ';
$strThisLink           = 'åĞÇ ÇáÑÇÈØ';
$strToUnsubscribe      = 'İí ÍÇá ÚÏã ÑÛÈÊß İí ÇÓÊŞÈÇá ÇáãÒíÏ ãä ÇáÑÓÇÆá, ';
$strToUpdate           = 'áÊÍÏíË ãÚáæãÇÊß æáÅáÛÇÁ ÇáÇÔÊÑÇß Şã ÈÒíÇÑÉ';
$strSendHTML           = 'ÅÑÓÇá ÑÓÇáÉ HTML';
$strYes                = 'äÚã';
$strNo                 = 'áÇ';
$strUnsubscribe        = 'ÅáÛÇÁ ÇáÇÔÊÑÇß';
$strAllMailinglists    = 'ÌãíÚ ÇáŞæÇÆã ÇáÈÑíÏíÉ';
$strAttachmentIntro     = 'åĞå ÇáÑÓÇáÉ ÊÍÊæí Úáì ãÑİŞÇÊ ÊÓÊØíÚ ãÔÇåÏÊåÇ ÈÇáãÊÕİÍ:';
$strLocation           = 'ÇáãßÇä';
$strFrequency           = 'ãÇåí ÇáãÏÉ ÇáÊí ÊæÏ İíåÇ ÇÓÊŞÈÇá ÑÓÇÆáäÇ';
$strHourly             = 'ÈÇáÓÇÚÉ';
$strDaily               = 'ÈÇáíæã';
$strWeekly             = 'ÈÇáÃÓÈæÚ';
$strMonthly             = 'ÈÇáÔåÑ';
$strChoosePassword      = 'ÇáÑÌÇÁ ßÊÇÈÉ ßáãÉ ÇáÓÑ';
$strConfirmPassword    = 'ÊÃßíÏ ßáãÉ ÇáÓÑ';
$strEnterPassword       = 'ÇáÑÌÇÁ ÅÏÎÇá ßáãÉ ÇáÓÑ';
$strForgotPassword     = 'äÓíÊ ßáãÉ ÇáÓÑ';
$strPassword           = 'ßáãÉ ÇáÓÑ';
$strPassword2           = 'ÊÃßíÏ ßáãÉ ÇáÓÑ';
$strPasswordsNoMatch    = 'ßáãÊÇ ÇáÓÑ áíÓÊÇ ãÊØÇÈŞÊíä';
$strEmailsNoMatch     = 'ÇáÈÑíÏ ÇáÅáßÊÑæäí ÇáĞí ÃÏÎáÊå áíÓ ãÊØÇÈŞ';
$strInvalidPassword     = 'ÎØÃ: İí ÇáÈÑíÏ ÇáÅáßÊÑæäí Ãæ ßáãÉ ÇáÓÑ';
$strPasswordSent        = 'ßáãÉ ÇáÓÑ ÃÑÓáÊ Åáíß ÚÈÑ ÇáÈÑíÏ ÇáÅáßÊÑæäí. ÓíÊã ÊæÕíáåÇ áÕäÏæŞ ÈÑíÏß ÎáÇá ÏŞÇÆŞ';
$strPasswordRemindSubject = 'ßáãÉ ÇáÓÑ ááŞÇÆãÉ ÇáÈÑíÏíÉ';
$strPasswordRemindMessage = 'ßáãÉ ÇáÓÑ åí ';
$strPasswordRemindInfo = 'áÊæÕíá ßáãÉ ÇáÓÑ ÚÈÑ ÇáÈÑíÏ ÇáÅáßÊÑæäí, ÃÏÎá ÚäÇæä ÈÑíÏß ÇáÅáßÊÑæäí æÇÖÛØ Úáì ÒÑ "'.$strForgotPassword.'".';
$strLogin               = 'ÇáÏÎæá';
$strLoginTitle          = 'ÇáÑÌÇÁ ÅÏÎÇá ÚäæÇä ÈÑíÏß ÇáÅáßÊÑæäí æßáãÉ ÇáÓÑ';
$strLoginInfo           = 'åĞå ÇáÕİÍÉ ãÍãíÉ ÈßáãÉ ÓÑ. ÇáÑÌÇÁ ÅÏÎÇá ÚäæÇä ÈÑíÏß ÇáÅáßÊÑæäí æßáãÉ ÇáÓÑ';
$strPersonalLocationInfo = '
  <p>åĞå ÇáÕİÍÉ ÊÊØáÈ ÅËÈÇÊ ÇáåæíÉ æÇáÊí ÊæÌÏ Úáì ÌãíÚ ÇáÑÓÇÆá ÇáÊí äÑÓáåÇ áß.<br/>
  ÅĞÇ ÖÛØÊ Úáì åĞÇ ÇáãßÇä, æÍÕáÊ Úáì åĞÇ ÇáÎØÃ, ÇáÑÌÇÁ ÇáÊÃßÏ ãä áÕŞ ßÇãá ÇáÓØÑ İí ÍŞá ÇáÚäæÇä áãÊÕİÍß. ÃÍíÇäÇğ ÇáÚäæÇä íßÊÈ Úáì ÚÏÉ ÃÓØÑ.</p>
  <p>ÅĞÇ áã ÊÚÑİ ÇáÚäæÇä, ÈÅãßÇäß ØáÈ ÑÓÇáÉ ÊÍÊæí Úáì ÇáÚäæÇä.
  ÇáÑÌÇÁ ÅÏÎÇá ÚäæÇä ÈÑíÏß ÇáÅáßÊÑæäí İí ÇáÍŞá æÇáÖÛØ Úáì "ÇÓÊãÑÇÑ"
';
$strPersonalLocationSent = '<h1>ÇäÊåíäÇ! ÓÊÕáß ÑÓÇáÉ ÊÍÊæí Úáì ãÚáæãÇÊß ÇáÔÎÕíÉ ÈÚÏ Şáíá</h1>';
$strUserExists   = '<br/>íæÌÏ ãÓÊÎÏã ÈäİÓ ÇáÚäæÇä ÇáÈÑíÏí, æÓÌáÇÊäÇ ÊÍÊæí Úáì ßáãÉ ÓÑ ãÛÇíÑÉ';
$strUserExistsExplanationStart = '<br/>ááÍÕæá Úáì ßáãÉ ÇáÓÑ, ÇÖÛØ ';
$strUserExistsExplanationLink = 'åäÇ';
$strUserExistsExplanationEnd = ' ááĞåÇÈ Åáì ÕİÍÉ ØáÈ ÇáãÚáæãÇÊ ÇáÔÎÕíÉ';
$strForwardTitle = 'ÊãÑíÑ ÇáÑÓÇáÉ áÔÎÕ ãÇ';
$strForwardSubtitle = 'ÊãÑíÑ ÇáÑÓÇáÉ ãÚ ÚäæÇä ÇáÑÓÇáÉ ';
$strForwardEnterEmail = 'ÇáÑÌÇÁ ÅÏÎÇá ÚäæÇä ÈÑíÏí ÕÍíÍ ááÊãÑíÑ áå';
$strForwardSuccessInfo ='Êã ÊãÑíÑ ÇáÑÓÇáÉ';
$strForwardFailInfo = 'İÔáÊ ÚãáíÉ ÊãÑíÑ ÇáÑÓÇáÉ';
$strForwardAlreadyDone = 'åĞå ÇáÑÓÇáÉ Êã ÈÇáİÚá ÅÑÓÇáåÇ áĞáß ÇáÚäæÇä';
$strForwardFooter = 'åĞå ÇáÑÓÇáÉ Êã ÊãÑíÑåÇ áß ãä ŞÈá [FORWARDEDBY].
  áã íÊã ÇÔÊÑÇßß ÈÔßá Ãáí İí ŞÇÆãÊäÇ ÇáÈÑíÏíÉ.
  ááÇÔÊÑÇß İí ŞÇÆãÊäÇ ÅĞåÈ Åáì';
$strForward = 'ÊãÑíÑ';
$strFwd = 'ÊãÑíÑ'; # short version of forward for email subject
?>