<?php

# language dependent text used in the interface for users (not admin)
# original translation by Gijsbert Rochat, update by Mike Rijken, 18/11/2002, review by Rudi Van Overloop, ruda@skynet.be 27/2/2004
# 
# Changed to current phplist version by SaWey 25/02/2007
# 

$strCharSet             = 'ISO-8859-1';
$strName                = 'Naam';
$strAddress             = 'Adres';
$strEmail               = 'Email';
$strTown                = 'Plaats';
$strPostcode            = 'Postcode';
$strSubscribeInfo       = 'Meld u aan voor een van onze nieuwsbrieven door onderstaand formulier in te vullen';
$strRequired            = 'verplicht veld';
$strSubscribeTitle      = 'Meld u aan voor een nieuwsbrief';
$strPleaseSelect        = 'Selecteer de nieuwsbrief waarvoor u zich wilt aanmelden';
$strSubmit              = 'Aanmelden bij de geselecteerde nieuwsbrieven';
$strNotAvailable        = 'Er zijn momenteel geen nieuwsbrieven beschikbaar';
$strEnterName           = 'Vul uw naam in';
$strEnterEmail          = 'Vul een geldig e-mailadres in';
$strConfirmEmail        = 'Bevestig uw emailadres';
$strInvalidHostInEmail  = 'Sorry, email naar dat domain kan niet worden verzonden, controleer aub of u het juiste email adres heeft ingevuld';
$strEnterList           = 'Selecteer een nieuwsbrief om aan te melden';
$strPleaseEnter         = 'Vul het volgende in';
# the thanks message can contain placeholders
#$strThanks             = 'Beste [FIRST NAME], <br/>Bedankt om je in te schrijven bij onze lijst.';
$strThanks              = 'Bedankt om je in te schrijven bij onze lijst.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation  = 'Uw email [email] is toegevoegd in ons systeem. U ontvangt binnen enkele ogenblikken een e-mailbericht ter bevestiging van uw aanmelding.';
$strEmailConfirmation   = 'U ontvangt binnen enkele ogenblikken een e-mailbericht ter bevestiging van uw aanmelding. Zorg ervoor dat u op de link klikt in het bericht om je inschrijving te bevestigen.';
$strEmailFailed         = 'Sorry, het verzenden van de bevestigingsmail is mislukt, klik aub op "Reload" om opnieuw te proberen. Als het nog niet lukt, dan kan het zijn dat u op de "Black List" staat, wat betekent dat u geen mails van onze nieuwsbrief kunt ontvangen. In dat geval, contacteer de administrator.';
$strUnsubscribeTitle    = 'Afmelden op onze nieuwsbrief';
$strUnsubscribeDone     = 'U bent afgemeld op de geselecteerde nieuwsbrief en u ontvangt binnen enkele ogenblikken een e-mailbericht ter bevestiging.';
$strBack                = 'Terug';
$strUnsubscribeInfo     = 'Afmelden op een van onze nieuwsbrieven';
$strContinue            = 'Volgende';
$strUnsubscribeSelect   = 'Selecteer de nieuwsbrief waarop u zich wilt afmelden.';
$strAllLists            = 'Alle nieuwsbrieven';
$strNoLists             = 'Geen enkele nieuwsbrief';
$strUnsubscribeRequestForReason = 'Het spijt ons dat u niet langer onze nieuwsbrief wilt ontvangen. Om onze diensten te helpen verbeteren zouden we heet dankbaar zijn als u ons wilt vertellen waarom:';
$strUnsubscribeFinalInfo = '<br/><b>Opgepast</b>: deze pagina dient om <b>nooit</b> meer onze nieuwsbrief te ontvangen. Als u uw email wilt wijzigen of als je een andere nieuwsbrief wilt ontvaneg, klik dan aub <a href="[PREFERENCESURL]">hier</a> om uw persoonlijke instellingen te wijzigen';
$strNoListsFound        = 'Sorry, u heeft met dit e-mailadres geen abonnement op een van onze nieuwsbrieven.';
$strResubmit            = 'Nogmaals e-mailadres';
$strUnsubscribeSubmit   = 'Afmelden op de geselecteerde nieuwsbrieven';
$strValuesMissing       = 'De volgende verplichte velden zijn niet ingevuld';
$strConfirmInfo         = 'Dank u voor het bevestigen van uw aanmelding. De nieuwsbrief waarop u bent geabonneerd wordt hieronder weergegeven';
$strConfirmTitle        = 'Bevestiging';
$strUserNotFound        = 'Gebruiker niet gevonden';
$strUserAlreadyInitialised = 'Sorry, uw wachtwoord is al ingestels';
$strConfirmFailInfo     = 'Sorry, uw bevestiging werd niet herkend. Zorg er aub voor dat u het volledige web adres volgt als vermeld in de email die u heeft ontvangen. Soms zit deze URL vervat in meerdere lijnen.';
$strPreferHTMLEmail     = 'Ik geef de voorkeur aan het ontvangen van emails in HTML formaat.';
$strPreferTextEmail     = 'Ik geef de voorkeur aan het ontvangen van emails in Tekst formaat.';
$strPreferredFormat      = 'Formaat van uw voorkeur voor emails:';
$strText                 = 'Tekst';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Vernieuw uw instellingen';
$strPreferencesInfo     = 'Als de informatie hieronder correct is kunt u gewoon op de "wijzig" knop klikken om te bewaren';
$strUpdatePreferences   = 'wijzig';
$strPreferencesEmailChanged = 'Uw email is gewijzigd. Klik op de link in de email die u zo meteen ontvangt om de wijziging te bevestigen.';
$strYouAreBlacklisted = 'Uw email staat op onze "Black List", dit betekent dat u ons gevraagd heeft nooit meer een nieuwsbrief op te sturen. <br/>
Om opieuw emails te ontvangen is manuele tussenkomst van de administrator vereist. Contacteer ons waarbij u vermeld dat u zeker bent dat u onze nieuwsbrief opnieuw wilt ontvangen
en wij zullen u dan van onze black list halen. ';
$strPreferencesNotificationSent = 'u ontvangt een email met de wijzigingen';
$strPreferencesUpdated = 'Wij hebben uw instellingen vernieuwd';
$strClickHere          = 'Klik hier';
$strThisLink           = 'deze link';
$strToUnsubscribe      = 'Om u van deze nieuwsbrief af te melden bezoek';
$strToUpdate           = 'Om uw voorkeuren te wijzigen bezoek';
$strSendHTML           = 'Verstuur HTML email';
$strYes                = 'Ja';
$strNo                 = 'Nee';
$strUnsubscribe        = 'Afmelden';
$strAllMailinglists    = 'Alle nieuwsbrieven';
$strAttachmentIntro     = 'Dit bericht bevat bijlagen die in een webbrowser kunnen worden weergegeven:';
$strLocation           = 'Locatie';
$strFrequency           = 'Hoe vaak zenden wij u berichten';
$strHourly             = 'Uurlijks';
$strDaily               = 'Dagelijks';
$strWeekly             = 'Weekelijks';
$strMonthly             = 'Maandelijks';
$strChoosePassword      = 'Kies aub een wachtwoord';
$strConfirmPassword    = 'Bevestig uw wachtwoord';
$strEnterPassword       = 'Voer aub uw wachtwoord in';
$strForgotPassword     = 'Wachtwoord Vergeten';
$strPassword           = 'Wachtwoor';
$strPassword2       = 'Bevestig wachtwoord';
$strPasswordsNoMatch   = 'Wachtwoorden komen niet overeen';
$strEmailsNoMatch     = 'Email Addresses you entered do not match';
$strInvalidPassword     = 'FOUT: ongeldig e-mail of paswoord';
$strPasswordSent      = 'Uw paswoord is naar uw e-mail verzonden. U zal het over enkele ogenblikken ontvangen';
$strPasswordRemindSubject = 'Uw wachtwoord voor onze nieuwsbrief';
$strPasswordRemindMessage = 'Uw wachtwoord is';
$strPasswordRemindInfo = 'Om uw wachtwoord per mail te ontvangen, geef aub uw email en klik op de "'.$strForgotPassword.'" knop.';
$strLogin               = 'Inloggen';
$strLoginTitle         = 'Vul Uw e-mail adres en wachtwoord in aub';
$strLoginInfo        = 'Deze pagina vereist een wachtwoord. Vul Uw e-mail adres en paswoord in aub';
$strPersonalLocationInfo = '
  <p>Deze pagina vereist een persoonlijke identificatie dewelke u kan terugvinden in elke e-mail dat we u sturen.<br/>
  Kijk nog eens goed de juiste URL in je browser na wanneer u een foutmelding ontvangt.
  De URL kan soms over 2 tekstlijnen verdeeld zijn.</p>
  <p>Wanneer U de URL niet kan terugvinden, kan je deze eenvoudig per e-mail aanvragen.
  Vul je e-mail adres in aub en klik op "Continue"';
$strPersonalLocationSent = '<h1>Gefeliciteerd! U zal kortelings een bericht ontvangen met een overzicht van Uw persoonlijke instellingen.</h1>';
$strUserExists   = '<br/>Een gebruiker met deze email bestaat reeds en onze bestanden bevatten een verschillend wachtwoord';
$strUserExistsExplanationStart = '<br/>Om uw wachtwoord te verkrijgen, klik';
$strUserExistsExplanationLink = 'hier';
$strUserExistsExplanationEnd = ' om naar de pagina te gaan waar u uw persoonlijke locatie kunt aanvragen';
$strExplainBlacklist = 'De email die u hier invult wordt vastgelegd in onze database met als enig doel het blokkeren van verder emails naar dit adres.';
$strForwardTitle = 'Stuur een bericht door aan iemand';
$strForwardSubtitle = 'Bericht wordt doorgestuurd met volgend onderwerp';
$strForwardEnterEmail = 'Geef aub een geldig email adres om het bericht naar door te sturen';
$strForwardSuccessInfo ='Het bericht is doorgestuurd';
$strForwardFailInfo = 'Het doorsturen van het bericht is mislukt';
$strForwardBlacklistedEmail = 'Ontvanger heeft verzocht geen mail te ontvangen van dit systeem.';
$strForwardAlreadyDone = 'Dit bericht is al met succes doorgestuurd naar dat adres';
$strForwardFooter = 'Dit bericht is doorgestuurd naar u door [FORWARDEDBY].
  U bent niet automatisch toegevoegd aan onze nieuwsbrief.
  Om je in te schrijven voor deze nieuwsbrief, ga naar';
$strForward = 'Stuur door';
$strFwd = 'Fwd'; # short version of forward for email subject
?>
