<?php
# language dependent text used in the interface for users (not admin)
# translation by Gijsbert Rochat, updated by Jean-Luc Picard
$strCharSet             = 'ISO-8859-1';
$strName                = 'Nom';
$strAddress             = 'Adresse';
$strEmail               = 'Courriel';
$strTown                = 'Ville';
$strPostcode            = 'Code postal';
$strSubscribeInfo       = 'S\'abonner à une ou plusieurs listes en utilisant ce formulaire';
$strRequired            = 'Champ requis';
$strSubscribeTitle      = 'S\'abonner à nos listes';
$strPleaseSelect        = 'Veuillez sélectionner les listes auxquelles vous désirez vous abonner ';
$strSubmit              = 'S\'abonner aux listes sélectionnées';
$strNotAvailable        = 'Désolé, aucune nouvelle liste n\'est disponible pour le moment';
$strEnterName           = 'Entrez votre nom ';
$strEnterEmail          = 'Entrez votre adresse de courriel ';
$strInvalidHostInEmail  = 'Désolé, aucun hôte n\'a été trouvé pour envoyer votre courriel. Veuillez vérifier votre adresse de courriel';
$strEnterList           = 'Veuillez sélectionner une liste pour vous abonner';
$strPleaseEnter         = 'Veuillez entrer votre';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Merci de vous être abonné(e) à nos listes.';
# the EmailConfirmation message can contain placeholders
$strEmailConfirmation   = 'Votre courriel [email] est enregistré. Vous allez recevoir un courriel pour confirmer votre abonnement. Veuillez confirmer votre abonnement en cliquant sur le lien contenu dans ce message.';
$strEmailFailed    = 'Désolé, l\'envoi du courriel de confirmation a échoué. Veuillez actualiser la page pour réessayer.';
$strUnsubscribeTitle    = 'Se désabonner de nos listes';
$strUnsubscribeDone     = 'Vous avez été désabonné(e) des listes choisies. Vous recevrez un courriel de confirmation.';
$strBack                = 'Retour';
$strUnsubscribeInfo     = 'Se désabonner d\'une ou de plusieurs de nos listes';
$strContinue            = 'Continuer';
$strUnsubscribeSelect   = 'Sélectionnez les listes auxquelles vous désirez vous désabonner';
$strAllLists            = 'Toutes les listes';
$strNoLists             = 'Aucune liste';
$strUnsubscribeRequestForReason = 'nous sommes désolé de constater que vous ne souhaitez plus recevoir nos lettres. Afin de nous aider a améliorer nos services, pouvez vous nous en préciser les raisons:';
$strUnsubscribeFinalInfo = '<br/><b>Note</b>: Cette page est une page de déinscription <b>définitive</b> de nos listes. Si vous désirez changer votre adresse Couriel ou modifier les listes auquels vous souscrivez, S.V.P. utilisez le lien <a href="[PREFERENCESURL]">Mise à jour</a>';
$strNoListsFound        = 'Désolé, votre courriel ne correspond à aucun abonnement.';
$strResubmit            = 'Re-envoyer le courriel';
$strUnsubscribeSubmit   = 'Se désabonner des listes sélectionnées';
$strValuesMissing       = 'Les entrées requises suivantes manquent';
$strConfirmInfo         = 'Merci de vous être abonné(e) à nos listes. Les listes auxquelles vous vous êtes abonné(e) sont listées ci-dessous';
$strConfirmTitle        = 'Page de confirmation pour membres de PHPlist';
$strUserNotFound        = 'Utilisateur introuvable';
$strUserAlreadyInitialised = 'Désolé, votre mot de passe a déjà été mis';
$strConfirmFailInfo     = 'Désolé, une erreur est survenue en essayant de confirmer votre abonnement. Votre demande de confirmation n\'a pas été validée. Veuillez vérifier que vous utilisez bien l\'adresse complète du lien contenu dans le courriel que vous avez reçu. Parfois, cette adresse tient sur plusieurs lignes.';
$strPreferHTMLEmail     = 'Je préfère recevoir les courriels en mode HTML';
$strPreferTextEmail     = 'Je préfère recevoir les courriels en mode texte';
$strPreferredFormat  = 'Format préféré pour les courriels :';
$strText     = 'Texte';
$strHTML    = 'HTML';
$strPreferencesTitle    = 'Mettre à jour vos préférences';
$strPreferencesInfo     = 'Vérifiez si les informations ci-dessous sont correctes et cliquez sur le bouton "'.$strUpdatePreferences.'"';
$strUpdatePreferences   = 'Mettre à jour';
$strPreferencesEmailChanged = 'Votre adresse de courriel a changé. Veuillez cliquer sur le lien dans le courriel que vous allez recevoir pour confimer ce changement d\'adresse';
$strYouAreBlacklisted = '<br>Votre compte est dans notre "Black List", vous avez demandé à ne plus recevoir d"information de notre part. <br/>
Pour recevoir de nouveau nos courriels notre administrateur doit éffectuer une intervention manuelle. Contacter le afin qu"il vous retire de notre "Black List", vous pourrez alors vous abonner de nouveau';
$strPreferencesNotificationSent = 'Vous allez recevoir un courriel avec vos modifications.';
$strPreferencesUpdated = 'Vos informations ont été mises à jour. Merci de votre Visite.';
$strClickHere          = 'Cliquez ici';
$strThisLink           = 'ce lien';
$strToUnsubscribe      = 'Pour vous désabonner à cette liste, visitez';
$strToUpdate           = 'Pour mettre vos préférences à jour, visitez';
$strSendHTML           = 'Envoyer un courriel au format HTML';
$strYes                = 'Oui';
$strNo                 = 'Non';
$strUnsubscribe        = 'Se désabonner';
$strAllMailinglists    = 'Toutes les Listes';
$strAttachmentIntro  = 'Ce message contient des pièces jointes qui peuvent être ouvertes avec un navigateur :';
$strLocation    = 'Localisation';
$strFrequency    = 'Fréquence d\'envoi de nos messages';
$strHourly    = 'Chaque heure';
$strDaily    = 'Journalière';
$strWeekly    = 'Hebdomadaire';
$strMonthly    = 'Mensuelle';
$strChoosePassword   = 'Veuillez choisir un mot de passe';
$strConfirmPassword   = 'Confirmez votre mot de passe';
$strEnterPassword  = 'Veuillez entrer votre mot de passe';
$strForgotPassword  = 'Mot de passe oublié';
$strPassword    = 'Mot de passe';
$strPassword2    = 'Confirmation du mot de passe';
$strPasswordsNoMatch   = 'Les mots de passe ne sont pas identiques';
$strEmailsNoMatch     = 'les Adresse Email ne correspondent pas';
$strInvalidPassword  = 'Erreur : courriel ou mot de passe invalide';
$strPasswordSent   = 'Le mot de passe vient d\'être envoyé par courriel';
$strPasswordRemindSubject = 'Votre mot de passe pour nos listes';
$strPasswordRemindMessage = 'Votre mot de passe est ';
$strPasswordRemindInfo = 'Pour recevoir votre mot de passe par courriel, veuillez entrer votre courriel et cliquer sur le bouton "'.$strForgotPassword.'".';
$strLogin    = 'Connexion';
$strLoginTitle     = 'Veuillez entrer votre adresse de courriel et votre mot de passe';
$strLoginInfo    = 'Cette page nécessite un mot de passe. Veuillez entrer votre adresse de courriel et votre mot de passe';
$strPersonalLocationInfo = '<p>Cette page nécessite une authentification personnalisée qui peut être
 trouvée sur chaque courriel précédemment envoyé.<br> Si vous avez cliqué à partir d\'un lien pour
 obtenir cette page et que vous obtenez cette erreur, veuillez copier l\'adresse complète du lien,
 même si celle-ci tient sur plusieurs lignes, et la coller ensuite dans le champ correspondant de
 votre navigateur.</p>
<p>Si vous ne connaissez pas sa localisation, vous pouvez demander un courriel qui vous la fera
 parvenir. Veuillez entrer votre adresse de courriel dans le champ et cliquer sur "Continuer"';
$strPersonalLocationSent = '<h1>Bravo ! vous allez recevoir un courriel avec vos indications personnalisées</h1>';

$strUserExists   = '<br/>un utilisateur cet EMail existe déja dans nos base , mais le pot de passe ne correspond pas';
$strUserExistsExplanationStart = '<br/>Afin d\'obtenir votre mot de passe cliquez ';
$strUserExistsExplanationLink = 'ici';
$strUserExistsExplanationEnd = ' pour aller à la page ou vous trouverez vos informations personelles';
$strForwardTitle = 'Faire suivre un message a quelqun';
$strForwardSubtitle = 'Faire suivre le message ayant pour sujet';
$strForwardEnterEmail = 'SVP entrez une adresse EMail valide auquel on fera suivre le courier';
$strForwardSuccessInfo ='Le méssage a été transféré';
$strForwardFailInfo = 'le Transfert du message a échoué';
$strForwardAlreadyDone = 'Ce message a déja été transféré avec succes à cette adresse EMail';
$strForwardFooter = 'Ce message vous a été transféré par  [FORWARDEDBY].
  Vous n\'avez pas été incrit automatiquement sur cette liste de diffusion.
  our vous y inscrire allez à ';
$strForward = 'Faire Suivre';
$strFwd = 'Tfr'; # short version of forward for email subject

?>

