<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'ISO-8859-1';
$strName                = 'Name';
$strAddress             = 'Adresse';
$strEmail               = 'E-Mail';
$strTown                = 'Wohnort';
$strPostcode            = 'Postfach';
$strSubscribeInfo       = 'Zum Anmelden bei einer oder mehreren unserer Mailinglisten ben&uuml;tzen Sie das nachfolgende Formular!';
$strRequired            = 'Ben&ouml;tigte Felder in rot';
$strSubscribeTitle      = 'Anmelden bei der Mailingliste';
$strPleaseSelect        = 'Bitte w&auml;hlen Sie eine oder mehrere Listen, bei denen Sie sich anmelden wollen';
$strSubmit              = 'Anmelden bei den ausgew&auml;hlten Mailinglisten';
$strNotAvailable        = 'Derzeit sind keine Listen verf&uuml;gbar';
$strEnterName           = 'Bitte geben Sie ihren Namen ein';
$strEnterEmail          = 'Bitte geben Sie ihre E-Mail Adresse ein';
$strConfirmEmail        = 'E-Mail best&auml;tigen';
$strInvalidHostInEmail  = 'Entschuldigung, aber E-Mail an diese Adresse ist unzustellbar. Bitte pr&uuml;fen Sie Ihre Adresse erneut.';
$strEnterList           = 'Bitte w&auml;hlen Sie ein Liste aus, bei der Sie sich anmelden wollen';
$strPleaseEnter         = 'Bitte geben Sie ein';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Danke f&uuml;r die Anmeldung bei unseren Listen.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   = 'Sie erhalten in k&uuml;rze eine E-Mail mit der Best&auml;tigung der Listen bei denen Sie sich angemeldet haben.';
$strEmailFailed	        = 'Entschuldigung, aber die E-Mail mit der Best&auml;tigungsanfrage wurde nicht versandt, bitte dr&uuml;cken Sie Aktualisieren und versuchen Sie es nochmals.';
$strUnsubscribeTitle    = 'Abmelden von unseren Mailinglisten';
$strUnsubscribeDone     = 'Sie wurden von den Mailinglisten, die Sie ausgew&auml;hlt haben, abgemeldet - eine Best&auml;tigung erhalten Sie in k&uuml;rze per E-Mail.';
$strBack                = 'Zur&uuml;ck';
$strUnsubscribeInfo     = 'Abmelden von einer oder mehreren unserer Mailinglisten';
$strContinue            = 'Weiter';
$strUnsubscribeSelect   = 'Bitte w&auml;hlen Sie die Listen von denen Sie sich abmelden wollen';
$strAllLists            = 'Alle Listen';
$strNoLists             = 'Keine von diesen';
$strUnsubscribeRequestForReason = 'Wir bedauern die Abmeldung unseres Newsletters. Es w&uuml;rde uns helfen, wenn Sie den Grund angeben k&ouml;nnten:';
$strUnsubscribeFinalInfo = '<br/><b>Bitte beachten</b>: diese Seite dient dazu, unseren Newsletter <b>endg&uuml;tig</b> abzumelden. Falls Sie Ihre E-Mail Adresse oder die Auswahl des Newsletters &auml;ndern m&ouml;chten, &auml;ndern Sie bitte Ihre <a href="[PREFERENCESURL]">Voreinstellungen</a>';
$strNoListsFound        = 'Sie wurden mit dieser E-Mail bei keiner unserer Mailinglisten angemeldet';
$strResubmit            = 'Erneut versuchen';
$strUnsubscribeSubmit   = 'Abmelden von den gew&auml;hlten Mailinglisten';
$strValuesMissing       = 'Die folgenden ben&ouml;tigten Felder fehlen';
$strConfirmInfo         = 'Danke f&uuml;r die Best&auml;tigung. Sie wurden auf folgenden Listen eingeschrieben:';
$strConfirmTitle        = 'Best&auml;tigungsseite';
$strUserNotFound        = 'User nicht gefunden';
$strUserAlreadyInitialised = 'Ihre Passwort wurde bereits verschickt';
$strConfirmFailInfo     = 'Es trat ein Fehler auf. Details:';
$strPreferHTMLEmail     = 'Ich bevorzuge E-Mails im HTML-Format';
$strPreferTextEmail     = 'Ich bevorzuge E-Mails im Text-Format';
$strPreferredFormat     = 'Bevorzugtes Format f&uuml;r E-Mails:';
$strText                = 'Text';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Einstellungen &auml;ndern';
$strPreferencesInfo     = 'Bitte best&auml;tigen Sie, da&szlig; die folgenden Informationen korrekt sind und dr&uuml;cken Sie den Update-Button';
$strUpdatePreferences   = 'Update';
$strPreferencesEmailChanged = 'Ihre E-Mail wurde ge&auml;ndert. Bitte besuchen Sie den Link, welcher in der  E-Mail genannt wird, die Sie an Ihre neue Adresse erhalten.';
$strYouAreBlacklisted  = 'Ihre E-Mail Adresse ist in unserer "Black List" - das hei&szlig;t Sie m&ouml;chten keine Newsletters mehr. <br/>
Um wieder Newsletter E-Mails zu empfangen, mu&szlig; der Administrator manuell eingreifen. Bitte kontaktieren Sie den Webmaster explizit mit der Anfrage, den Newsletter
wieder zu empfangen, und Sie werden von der "Black List" entfernt.';
$strPreferencesNotificationSent = 'Sie werden eine E-Mail mit den &Auml;nderungen erhalten';
$strPreferencesUpdated = 'Danke f&uuml;r Ihre &Auml;nderungen. Wir haben Ihre Informationen aktualisiert.';
$strClickHere          = 'Dr&uuml;cken Sie hier';
$strThisLink           = 'dieser Link';
$strToUnsubscribe      = 'Um sich aus der Liste auszutragen, besuchen Sie';
$strToUpdate           = 'Um Ihre Einstellungen zu &auml;ndern, besuchen Sie';
$strSendHTML           = 'Sende HTML E-Mail';
$strYes                = 'Ja';
$strNo                 = 'Nein';
$strUnsubscribe        = 'Abmelden';
$strAllMailinglists    = 'Alle Mailinglisten';
$strAttachmentIntro    = 'Diese Nachricht beinhaltet Anh&auml;nge, die mit einem Webbrowser betrachtet werden k&ouml;nnen:';
$strLocation           = 'Ort';
$strFrequency          = 'Wie oft d&uuml;rfen wir Ihnen Nachrichten senden';
$strHourly             = 'St&uuml;ndlich';
$strDaily              = 'T&auml;glich';
$strWeeklym            = 'W&ouml;chentlich';
$strMonthly            = 'Monatlich';
$strChoosePassword     = 'Bitte w&auml;hlen Sie ein Pa&szlig;wort';
$strConfirmPassword    = 'Bitte best&auml;tigen Sie Ihr Pa&szlig;wort';
$strEnterPassword      = 'Bitte geben Sie Ihr Pa&szlig;wort ein';
$strForgotPassword     = 'Pa&szlig;wort vergessen';
$strPassword           = 'Pa&szlig;wort';
$strPassword2          = 'Pa&szlig;wort best&auml;tigen';
$strPasswordsNoMatch   = 'Die Pa&szlig;w&ouml;rter stimmen nicht &uuml;berein';
$strEmailsNoMatch      = 'Die E-Mail Adressen stimmen nicht &uuml;berein';
$strInvalidPassword    = 'Fehler: ung&uuml;ltige E-Mail oder Pa&szlig;wort';
$strPasswordSent       = 'Ihre Pa&szlig;wort wurde Ihnen per E-Mail zugesendet. Sie sollten es innerhalb der n&auml;chsten Minuten erhalten.';
$strPasswordRemindSubject = 'Ihr Pa&szlig;wort f&uuml;r unsere Listen';
$strPasswordRemindMessage = 'Ihr Pa&szlig;wort lautet ';
$strPasswordRemindInfo = 'Um Ihr Pa&szlig;wort per E-Mail zu erhalten, geben Sie bitte Ihre E-Mail-Adresse ein und dr&uuml;cken den "'.$strForgotPassword.'" Knopf.';
$strLogin              = 'Login';
$strLoginTitle         = 'Bitte geben Sie Ihre E-Mail-Adresse und Ihr Pa&szlig;wort ein';
$strLoginInfo          = 'Diese Seite ben&ouml;tigt ein Pa&szlig;wort. Bitte geben Sie Ihre E-Mail-Adresse und Ihr Pa&szlig;wort ein';
$strPersonalLocationInfo = '
  <p>Diese Seite ben&ouml;tigt eine pers&ouml;nliche Identifikation, welche auf jeder von uns an Sie gesendeten E-Mail angegeben ist.<br/>
  Wenn Sie diesen Bereich angeklickt haben und diesen Fehler erhalten, vergewissern Sie sich, da&szlig; Sie die vollst&auml;ndige Linie in die 
  Adressezeile Ihres Browsers eigetragen haben. Manchmal ist die Adresse &uuml;ber mehrere Zeilen umgebrochen.</p>
  <p>Wenn Sie den Bereich nicht kennen, k&ouml;nnen Sie Ihn per E-Mail erfragen.
  Bitte geben Sie dazu Ihre E-Mail-Adresse ein und klicken Sie auf Weiter
';
$strPersonalLocationSent       = '<h1>Erfolg! Sie sollten eine Nachricht mit Ihrem pers&ouml;nlichen Bereich in K&uuml;rze erhalten</h1>';
$strUserExists                 = '<br/>Ein Benutzer mit dieser E-Mail-Adresse existiert bereit und hat ein anderes Pa&szlig;wort';
$strUserExistsExplanationStart = '<br/>Um Ihr Pa&szlig;wort zu erhalten, klicken Sie';
$strUserExistsExplanationLink  = 'hier';
$strUserExistsExplanationEnd   = ' um zu der Seite zu gelangen, wo Sie Ihren pers&ouml;nlichen Bereich anfordern k&ouml;nnen';

$strExplainBlacklist        = 'Die E-Mail Adresse wird ausschlie&szlig;lich zum Blockieren auf diesem System verwendet.';
$strForwardTitle            = 'Nachricht weiterleiten';
$strForwardSubtitle         = 'Weiterleiten mit Betreff ';
$strForwardEnterEmail       = 'Bitte eine g&uuml;ltige E-Mail f&uuml;r die Weiterleitung angeben';
$strForwardInvalidEmail     = '%s ist keine g&uuml;ltige E-Mail Adresse';
$strForwardBlacklistedEmail = 'Empf&auml;ger lehnt E-Mails von diesem System ab.';
$strForwardEnterEmails      = 'Bitte tragen Sie eine maximale Anzahl von %s g&uuml;tigen E-Mail Adressen zur Weiterleitung in diese Feld ein (eine pro Zeile)';
$strForwardPersonalNote     = 'Sie k&ouml;nnen eine Textnachricht (maximal %d Zeichen) eingeben, die der weitergeleiteten E-Mail vorangestellt werden';
$strForwardSuccessInfo      = 'Diese Nachricht wurde weitergeleitet';
$strForwardFailInfo         = 'Diese Nachricht konnte nicht weitergeleitet werden';
$strForwardAlreadyDone      = 'Diese Nachricht wurde schon erfolgreich an diese E-Mail Adresse weitergeleitet';
$strForwardCountReached     = 'Maximale Anzahl von Weiterleitungen erreicht';
$strForwardNoteLimitReached = 'Maximale L&auml;nge der personalisierten Nachricht erreicht';
$strForwardFooter           = 'Diese Nachricht wurde an Sie weitergeleitet durch [FORWARDEDBY].
  Sie sind nicht automatisch bei diesem Newsletter angemeldet.
  Zum Abonnieren dieses Newsletters gehen Sie bitte hierhin';
$strForward = 'Weiterleiten';
$strFwd = 'Fwd';
?>