<?php

# language dependent text used in the interface for users (not admin)

$strDirection               = 'rtl';
// for archive.php - start
$strArchiveTitle               = 'צפייה בארכיון';
$strArchiveList               = 'אנא ביחרו רשימה כדי לראות את הארכיון שלה';
$strArchiveNoItem               = 'אין מידע לפריט זה';
$strViewLists                     = 'רשימת רשימות התפוצה';
$strFirst                            = 'הראשון';
$strLast                            = 'האחרון';
$strNext                           = 'הבא';
$strPrev                           = 'הקודם';
$NoActiveLists                 = 'לא נמצאו רשימות תפוצה פעילות';
$EmptyArchive                 = 'לא נמצאו פריטים במאגר';
$InvalidMessage               = 'חלה שגיאה בהצגת ההודעה שנבחרה';
$database_unselected      = 'חלה שגיאה בבחירת מאגר המידע';
$database_unconnected   = 'חלה שגיאה בהתחברות למאגר המידע';
// for archive.php - end
$strCharSet             = 'UTF-8';
$strName                = 'שם';
$strAddress             = 'כתובת';
$strEmail               = 'אימייל';
$strTown                = 'עיר';
$strPostcode            = 'מיקוד';
$strSubscribeInfo       = 'להצטרפות לרשימת תפוצה אחת או יותר יש להשתמש בטופס שלהלן';
$strRequired            = 'שדה נדרש';
$strSubscribeTitle      = 'להצטרפות לרשימת התפוצה שלנו';
$strPleaseSelect        = 'אנא בחר/י את רשימות התפוצה אליהן ברצונך להצטרף';
$strSubmit              = 'צרפוני לרשימה שסומנה';
$strNotAvailable        = 'צר לנו, אך אין כרגע רשימות תפוצה זמינות';
$strEnterName           = 'אנא הזן/הזיני את שמך';
$strEnterEmail          = 'אנא ציין/צייני את כתובת האימייל שלך';
$strConfirmEmail        = 'אמת/י את כתובת האימייל שלך';
$strInvalidHostInEmail  = 'צר לנו, אך דואר אלקטרוני זה אינו קיים. אנא בדוק/בדקי אם לא נפלה טעות בהקלדה';
$strEnterList           = 'אנא בחר/י רשימת תפוצה אליה ברצונך להצטרף';
$strPleaseEnter         = 'אנא הזן/הזיני';
# the thanks message can contain placeholders
#$strThanks              = 'שלום [FIRST NAME], <br/>תודה שהצטרפת לרשימת התפוצה שלנו.';
$strThanks              = 'תודה שהצטרפת לרשימת התפוצה שלנו.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'כתובת האימייל [email] נרשמה במערכת. בקרוב תקבל/י אימייל ובו תתבקש/תתבקשי לאשר הצטרפות לרשימת.';
$strEmailConfirmation   = 'כתובת האימייל שלך נרשמה במערכת. בקרוב תקבל/י אימייל ובו תתבקש/תתבקשי לאשר הצטרפות לרשימת. אנא לחצ/י על הקישור על מנת לוודא את הרשמתך.';
$strEmailFailed          = 'צר לנו, אך לא הצלחנו לשלוח אליך אימייל לאישור ההצטרפת, אנא רענן/רענני את הדף ונסי שנית.';
$strUnsubscribeTitle    = 'הסרה מרשימת התפוצה';
$strUnsubscribeDone     = '<span dir="' . $strDirection . '">הוסרת מרשימת התפוצה ובקרוב תקבל/י אימייל לאישור.</span>';
$strBack                = 'חזרה';
$strUnsubscribeInfo     = 'הסרה מרשימת תפוצה אחת או יתר';
$strContinue            = 'המשך';
$strUnsubscribeSelect   = 'אנא בחר/י את רשימת התפוצה שברצונך לבטל ההרשמה אליה';
$strAllLists            = 'כל הרשימות';
$strNoLists             = 'אף רשימה';
$strUnsubscribeRequestForReason = 'אנו מצטערים לגלות שאינכם מעוניינים יותר בעלון התפוצה שלנו. כדי לעזור לנו לשפר את שירותנו, נודה לכם אם תוכלו לספר לנו למה:';
$strUnsubscribeFinalInfo = '<br/><b>אנא שימו לב</b>: עמוד זה נועד להפסקת קבלת הודעות אימייל ממערכת התפוצה שלנו <b>לתמיד</b>. אם תרצו לשנות את כתובת האימייל שלכם, או את הקביעה לאילו עלוני תפוצה אתם מקבלים, אנא <a href="[PREFERENCESURL]">עדכנו את העדפותיכם</a> במקום';
$strNoListsFound        = '<span dir="' . $strDirection . '">צר לנו, אך אינך רשום לאף רשימה עם כתובת האימייל הזו.</span>';
$strResubmit            = 'שלח/י בשנית את האימייל';
$strUnsubscribeSubmit   = 'הסרה מרשימות התפוצה שסומנו';
$strValuesMissing       = 'השדות שלהלן לא מולאו';
$strConfirmInfo         = 'תודה שאישרת את ההצטרפות לרשימת התפוצה שלנו. להלן הרשימות אליהן את/ה רשומ/ה.';
$strConfirmTitle        = 'דף אישור הרשמה ל-PHPlist';
$strUserNotFound        = 'המשתמש/ת לא נמצא/ה';
$strUserAlreadyInitialised = 'צר לנו, אך בחרת כבר סיסמה';
$strConfirmFailInfo     = 'צר לנו, אך נפלה שגיאה באישור ההרשמה. אנא וודא/י כי הקלדת את כל הקישור שהופיע באימייל שנשלח אליך. קישור זה לעתים גולש למספר שורות.';
$strPreferHTMLEmail     = '<span dir="' . $strDirection . '">אנא שילחו לי אימיילים בפורמט HTML<br/>(<b>שימו לב:</b><br/> ביטול אפשרות זו משמעותו בין היתר החלפת קבצים/מסמכים מצורפים <b>בקישורים חיצוניים</b>!)</span>';
$strPreferTextEmail     = 'אנא שלחו לי אימייל בפורמט טקסט בלבד';
$strPreferredFormat      = 'פורמט מועדף לקבלת אימיילים:';
$strText                 = 'טקסט';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'עידכון ההעדפות שלך';
$strPreferencesInfo     = 'אנא ודא/י כי האינפורמציה שלהלן נכונה ולחצ/י על "עדכון".';
$strUpdatePreferences   = 'עדכון';
$strPreferencesEmailChanged = 'כתובת האימייל שלך שונתה. אנא לחצ/י על הקישור המופיע באימייל שזה עתה נשלח לכתובת זו על מנת לאשרה.';
$strYouAreBlacklisted = 'כתובת האימייל שלכם רשומה ב"רשימה השחורה" שלנו, כלומר ביקשתם מאיתנו לא לשלוח לכם עוד הודעות תפוצה. <br/>
כדי לקבל מאיתנו שוב הודעות אימייל, דרושה התערבות ידנית ממנהלינו. אנא צרו עמנו קשר והצהירו במפורש שברצונכם לקבל שוב הודעות תפוצה, ואנו נסירכם מהרשימה השחורה שלנו. ';
$strPreferencesNotificationSent = 'את/ה תקבלי אימייל לאישור השינויים';
$strPreferencesUpdated = 'תודה על האישור. עדכנו את הנתונים החדשים.';
$strClickHere          = 'לחצ/י כאן';
$strThisLink           = 'קישור זה';
$strToUnsubscribe      = 'להסרה מרשימת התפוצה';
$strToUpdate           = 'לעדכון ההעדפות האישיות לחצ/י על הקישור';
$strSendHTML           = 'שלח אימייל בפורמט HTML';
$strYes                = 'כן';
$strNo                 = 'לא';
$strUnsubscribe        = 'הסרה מהרשימה';
$strAllMailinglists    = 'כל הרשימות';
$strAttachmentIntro     = 'הודעה זו כוללת קבצים בהם ניתן לצפות בדפדפן:';
$strLocation           = 'מיקום';
$strFrequency           = 'באיזו תכיפות את/ה רוצה שנשלח אליך הודעות';
$strHourly             = 'מדי שעה';
$strDaily               = 'מדי יום';
$strWeekly             = 'מדי שבוע';
$strMonthly             = 'מדי חודש';
$strChoosePassword      = 'אנא בחר/י סיסמה';
$strConfirmPassword    = 'אנא הקלד/הקלידי שנית את הסיסמה לאישור';
$strEnterPassword       = 'אנא הזן/הזיני את הסיסמה';
$strForgotPassword     = 'שכחתי את הסיסמה שלי';
$strPassword           = 'סיסמה';
$strPassword2           = 'אישור סיסמה';
$strPasswordsNoMatch    = 'הסיסמאות שהזנת אינן זהות';
$strEmailsNoMatch     = 'כתובות האימייל שהכנסתם לא תואמות';
$strInvalidPassword     = 'שגיאה: כתובת אימייל או סיסמה שגויה';
$strPasswordSent        = 'הסיסמה נשלחה אליך באימייל. תקבל/י אותה בעוד מספר דקות.';
$strPasswordRemindSubject = 'הסיסמה שלך לרשימות התפוצה שלנו';
$strPasswordRemindMessage = 'הסיסמה שלך היא ';
$strPasswordRemindInfo = 'לקבלת הסיסמה באימייל אנא הזינו את כתובתכם וליחצו על  "'.$strForgotPassword.'".';
$strLogin               = 'כניסה למערכת';
$strLoginTitle          = 'אנא הזן/הזיני כתובת אימייל וסיסמה';
$strLoginInfo           = 'לצפייה בדף זה יש צורך להיכנס למערכת. אנא הזן/הזיני שם וסיסמה';
$strPersonalLocationInfo = '
  <p dir="' . $strDirection . '"> הצפיה בדף זה מתאפשרת באמצעות סימן זיהוי שמצא באימייל ששלחנו אליך.<BR>
  אם לחצת על הקישור באימייל שנשלח אליך, וקיבלת הודעת שגיאה זאת אנא וודא/י כי הקלדת או הדבקת את כל הכתובת לדפדפן. לעתים הכתובת גולשת על מספר שורות.</P>
  <p>אם אינכם יודעים את המיקום, אתם יכולים לבקש כי יישלח אליכם אימייל ובו הכתובת. אנא הזינו את כתובת האימייל שלכם וליחצו על "המשך"
';
$strPersonalLocationSent = '<h1>הפעולה בוצעה בהצלחה! בקרוב תקבלו אימייל ובו הפרטים שמילאתם</h1>';
$strUserExists   = '<br/>כבר קיים משתמש עם כתובת אימייל זו, והרשומות שלנו מכילות סיסמה אחרת';
$strUserExistsExplanationStart = '<br/>כדי לקבל את סיסמתכם, ליחצו ';
$strUserExistsExplanationLink = 'כאן';
$strUserExistsExplanationEnd = ' כדי להגיע לעמוד שבו תוכלו לבקש את מיקומכם האישי';
$strExplainBlacklist = 'כתובת האימייל שתכניסו כאן תתועד במאגר המידע שלנו למען המטרה היחידה של חסימת כל הודעה שתישלח ממערכת זו.';
$strForwardTitle = 'הפנו הודעה למישהו';
$strForwardSubtitle = 'הפניית ההודעה עם נושא ';
$strForwardEnterEmail = 'אנא הכניסו כתובת אימייל תקינה להפנות אליה';
$strForwardInvalidEmail = '%s אינה כתובת אימייל תקינה';
$strForwardBlacklistedEmail = 'הנמען ביקש לא לקבל הודעות אימייל ממערכת זו.';
$strForwardEnterEmails = 'אנא הכניסו בתיבה זו מקסימום של %s כתובות אימייל תקינות להפנות אליהן, אחת בכל שורה';
$strForwardPersonalNote = 'תוכלו להכניס הודעת טקסט פשוטה (מקסימום %d תווים) שתצורף לתחילת הודעת אימייל המופנה';
$strForwardSuccessInfo ='ההודעה הופנתה';
$strForwardFailInfo = 'הפניית ההודעה נכשלה';
$strForwardAlreadyDone = 'הודעה זו הופנתה בהצלחה לכתובת האימייל שלכם';
$strForwardCountReached = 'הגעתם למקסימום ההפניות';
$strForwardNoteLimitReached = 'הושג האורך המקסימלי של תזכורת אישית';
$strForwardFooter = 'הודעה זו הופנתה אליכם על ידי [FORWARDEDBY].
  לא רשמו אתכם באופן אוטומטי לרשימת התפוצה.
  כדי להירשם לעלון תפוצה זה לכו אל';
$strForward = 'הפנייה';
$strFwd = 'Fwd'; # short version of forward for email subject
?>