<?php

# language dependent text used in the interface for users (not admin)
# Polish translation by Agata Szczesniak
$strCharSet             = 'ISO-8859-2';
$strName                = 'Imiê i nazwisko';
$strAddress             = 'Adres';
$strEmail               = 'e-mail';
$strTown                = 'miasto';
$strPostcode            = 'kod pocztowy';
$strSubscribeInfo       = 'Za pomoc± poni¿szego formularza mo¿na zasubskrybowaæ nasze listy wysy³kowe';
$strRequired            = '<br />';
$strSubscribeTitle      = 'Subskrypcja naszych list wysy³kowych';
$strPleaseSelect        = 'Nale¿y wybraæ listy do zasubskrybowania';
$strSubmit              = 'Subskrybuj';
$strNotAvailable        = 'Niestety, nie ma teraz dostêpnych list';
$strEnterName           = 'Proszê podaæ imiê i nazwisko (lub pseudonim)';
$strEnterEmail          = 'Proszê wprowadziæ adres e-mail';
$strInvalidHostInEmail  = 'Niestety, nie mo¿na dostarczaæ poczty e-mail do tej domeny; proszê sprawdziæ, czy wpisany adres jest poprawny';
$strEnterList           = 'Proszê wybraæ subskrybowan± listê';
$strPleaseEnter         = 'Proszê wprowadziæ';
# the thanks message can contain placeholders
#$strThanks              = 'Dziêkujemy za subskrypcjê naszej listy.';
$strThanks              = 'Dziêkujemy za subskrypcjê naszej listy.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Adres [email] zosta³ dodany do naszego systemu. Wkrótce zostanie wys³ane potwierdzenie subskrypcji.';
$strEmailConfirmation   = 'Adres [email] zosta³ dodany do naszego systemu. Wkrótce zostanie wys³ana pro¶ba o potwierdzenie subskrypcji. Aby potwierdziæ subskrypcjê, nale¿y klikn±æ odno¶nik zawarty w wiadomo¶ci.';
$strEmailFailed					= 'Niestety, nie uda³o siê wys³aæ wiadomo¶ci z pro¶b± o potwierdzenie subskrypcji. Aby spróbowaæ ponownie, nale¿y klikn±æ ikonê "Od¶wie¿".';
$strUnsubscribeTitle    = 'Rezygnacja z subskrypcji';
$strUnsubscribeDone     = 'Zrezygnowano z subskrypcji wybranych list wysy³kowych. Zostanie to potwierdzone poczt± elektroniczn±.';
$strBack                = 'Wstecz';
$strUnsubscribeInfo     = 'Rezygnacja z przynajmniej jednej listy wysy³kowej';
$strContinue            = 'Kontynuuj';
$strUnsubscribeSelect   = 'Proszê wybraæ listy, których subskrypcja ma byæ anulowana';
$strAllLists            = 'Wszystkie listy';
$strNoLists             = '¯adna';
$strNoListsFound        = 'Niestety, ten adres e-mail nie wystêpuje w subskrypcji ¿adnej z naszych list wysy³kowych.';
$strResubmit            = 'Ponownie podaj adres e-mail';
$strUnsubscribeSubmit   = 'Rezygnacja z wybranych list wysy³kowych';
$strValuesMissing       = 'Brakuje nastêpuj±cych danych';
$strConfirmInfo         = 'Dziêkujemy za potwierdzenie subskrypcji naszych list. Poni¿ej znajduje siê lista subskrybowanych list wysy³kowych.';
$strConfirmTitle        = 'Strona potwierdzenia subskrypcji - PHPlist';
$strUserNotFound        = 'U¿ytkownik nie zosta³ znaleziony';
$strUserAlreadyInitialised = 'Niestety, has³o zosta³o ju¿ ustawione';
$strConfirmFailInfo     = 'Niestety, pro¶ba o potwierdzenie nie zosta³a rozpoznana. Nale¿y u¿yæ pe³nego adresu internetowego z otrzymanej wiadomo¶ci. W niektórych programach pocztowych adres jest zawijany do nastêpnego wiersza.';
$strPreferHTMLEmail     = 'Chcê otrzymywaæ wiadomo¶ci w formacie HTML';
$strPreferTextEmail     = 'Chcê otrzymywaæ wiadomo¶ci w formacie tekstowym.';
$strPreferredFormat			= 'Wybrany format wiadomo¶ci:';
$strText 								= 'Tekst';
$strHTML								= 'HTML';
$strPreferencesTitle    = 'Aktualizacja preferencji';
$strPreferencesInfo     = 'Prosimy o potwierdzenie poprawno¶ci poni¿szych informacji i klikniêcie przycisku "Aktualizuj".';
$strUpdatePreferences   = 'Aktualizuj';
$strPreferencesEmailChanged = 'Adres e-mail zosta³ zmieniony. Prosimy klikn±æ odno¶nik w wiadomo¶ci, która zostanie wys³ana w celu potwierdzenia nowego adresu.';
$strPreferencesNotificationSent = 'Wys³ana wiadomo¶æ bêdzie zawieraæ informacje o zmianach';
$strPreferencesUpdated = 'Dziêkujemy za zg³oszenie. Informacje zosta³y aktualizowane.';
$strClickHere          = 'Kliknij tutaj';
$strThisLink           = 'ten odno¶nik';
$strToUnsubscribe      = 'Aby zrezygnowaæ z subskrypcji tej listy, odwied¼ stronê';
$strToUpdate           = 'Aby zaktualizowaæ preferencje, odwied¼ stronê';
$strSendHTML           = 'Wy¶lij wiadomo¶æ w formacie HTML';
$strYes                = 'Tak';
$strNo                 = 'Nie';
$strUnsubscribe        = 'Rezygnujê';
$strAllMailinglists    = 'Wszystkie listy';
$strAttachmentIntro		 = 'Ta wiadomo¶æ zawiera za³±cznik, który nie mo¿e zostaæ odczytany przez przegl±darkê:';
$strLocation					 = 'Lokalizacja';
$strFrequency					 = 'Jak czêsto mamy wysy³aæ wiadomo¶ci';
$strHourly						 = 'Co godzinê';
$strDaily							 = 'Co dzieñ';
$strWeekly						 = 'Co tydzieñ';
$strMonthly						 = 'Co miesi±c';
$strChoosePassword 		 = 'Prosimy wybraæ has³o';
$strConfirmPassword 	 = 'Potwierdzenie has³a';
$strEnterPassword			 = 'Prosimy wprowadziæ has³o';
$strForgotPassword		 = 'Zapomnia³am/Zapomnia³em has³a';
$strPassword					 = 'Has³o';
$strPassword2					 = 'Potwierdzenie has³a';
$strPasswordsNoMatch 	 = 'Wprowadzone has³a s± ró¿ne';
$strInvalidPassword		 = 'B³êdny adres e-mail lub has³o';
$strPasswordSent 		   = 'Has³o zostanie wys³ane poczt± elektroniczn±. Wiadomo¶æ powinna dotrzeæ w ci±gu kilku minut.';
$strPasswordRemindSubject = 'Has³o do list wysy³kowych';
$strPasswordRemindMessage = 'Has³o:';
$strPasswordRemindInfo = 'Aby otrzymaæ has³o poczt± elektroniczn±, nale¿y wprowadziæ adres e-mail i klikn±æ przycisk "Zapomnia³am/Zapomnia³em has³a".';
$strLogin							 = 'Zaloguj';
$strLoginTitle 				 = 'Prosimy wprowadziæ adres e-mail i has³o';
$strLoginInfo					 = 'Dostêp do strony tylko podaniu has³a. Prosimy wprowadziæ adres e-mail i has³o';
$strPersonalLocationInfo = '
	<p> Dostêp do strony wymaga osobistego identyfikatora, który znajduje siê w ka¿dej naszej wiadomo¶ci.<br/>
  Je¿eli po klikniêciu tego adresu internetowego wyst±pi b³±d, nale¿y przekleiæ do pola adresu ca³± liniê z przegl±darki. Czasami adres jest zawijany do kilku nastêpnych wierszy.</p>
  <p>W wypadku nieznajomo¶ci tego adresu mo¿na za¿±daæ wiadomo¶ci, w której zostanie on podany. Prosimy wprowadziæ adres e-mail i klikn±æ przycisk "Kontynuuj"
';
$strPersonalLocationSent = '<h1>Wkrótce zostanie wys³ana wiadomo¶æ z osobistym identyfikatorem</h1>';

?>
