<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'ISO-8859-2';
$strName                = 'Nume';
$strAddress             = 'Adresã';
$strEmail               = 'Email';
$strTown                = 'Localitate';
$strPostcode            = 'Cod poºtal';
$strSubscribeInfo       = 'Aboneazã-te la una sau mai multe liste folosint formularul de mai jos';
$strRequired            = 'câmp obligatoriu';
$strSubscribeTitle      = 'Aboneazã-te la listele noastre';
$strPleaseSelect        = 'Te rugãm alege listele la care vrei sã te abonezi';
$strSubmit              = 'Aboneazã-te la listele selectate';
$strNotAvailable        = 'Ne pare rãu, deocamdatã nu existã liste disponibile';
$strEnterName           = 'Te rugãm sã îþi introduci numele';
$strEnterEmail          = 'Te rugãm introdu adresa de e-mail';
$strInvalidHostInEmail  = 'Ne pare rãu, nu se pot livra e-mail-uri la domeniul acesta, te rugãm sã verifici dacã ai scris adresa de e-mail corectã';
$strEnterList           = 'Selecteazã o listã la care sã te abonezi';
$strPleaseEnter         = 'Te rugãm sã-þi introduci';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Mulþumim pentru cã te-ai abonat la listele noastre';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   = 'Adresa ta de e-mail a fost adãugatã la sistemul nostru. Vei primi în scurt timp un mesaj cu o cerere de confirmare. Te rugãm sã dai clic pe link-ul din acel mesaj pentru a-þi confirma abonamentul.';
$strEmailFailed		= 'Ne pare rãu, e-mailul de confirmare nu a putut fi trimis, te rugãm sã dai click pe "Reload" pentru a încerca din nou.';
$strUnsubscribeTitle    = 'Dezaboneazã-te de la listele noastre';
$strUnsubscribeDone     = 'Ai fost dezabonat de la listele selectate ºi vei primi o confirmare prin e-mail în curând.';
$strBack                = 'Înapoi';
$strUnsubscribeInfo     = 'Dezaboneazã-te de la una sau mai multe liste';
$strContinue            = 'Continuã';
$strUnsubscribeSelect   = 'Te rugãm sã selectezi listele de la care vrei sã te dezabonezi';
$strAllLists            = 'Toate listele';
$strNoLists             = 'Nici una';
$strNoListsFound        = 'Ne pare rãu, nu eºti abonat la nici una din listele noastre cu aceastã adresã de e-mail';
$strResubmit            = 'Re-trimite e-mail-ul';
$strUnsubscribeSubmit   = 'Dezaboneazã-te de la listele selectate';
$strValuesMissing       = 'Urmãtoarele câmpuri obligatorii nu au fost completate';
$strConfirmInfo         = 'Îþi mulþumim pentru cã þi-ai confirmat abonamentul la listele noastre. Listele la care eºti abonat sunt enumerate mai jos';
$strConfirmTitle        = 'Pagina de confirmare a abonamentului';
$strUserNotFound        = 'Utilizatorul nu a fost identificat';
$strUserAlreadyInitialised = 'Ne pare rãu, parola ta a fost trimisã deja';
$strConfirmFailInfo     = 'Ne pare rãu, cererea ta de confirmare nu a fost recunoscutã. Asigurã-te cã ai folosit adresa web completã aºa cum este menþionatã în mesajul pe care l-ai primit. Uneori aceastã adresã se întinde pe mai multe rânduri.';
$strPreferHTMLEmail     = 'Prefer sã primesc e-mail-uri în format HTML';
$strPreferTextEmail     = 'Prefer sã primesc e-mail-uri în format Text';
$strPreferredFormat			= 'Formatul preferat pentru e-mail-uri:';
$strText 								= 'Text';
$strHTML								= 'HTML';
$strPreferencesTitle    = 'Actualizeazã-þi preferinþele';
$strPreferencesInfo     = 'Te rugãm sã confirmi dacã informaþiile de mai jos sunt corecte ºi apãsaþi pe butonul "Actualizeazã"';
$strUpdatePreferences   = 'Actualizeazã';
$strPreferencesEmailChanged = 'Adresa ta de e-mail a fost modificatã. Te rugãm sã vizitezi link-ul din mesajul pe care îl vei primi pentru a confirma noua adresã';
$strPreferencesNotificationSent = 'Vei primi un e-mail cu schimbãrile';
$strPreferencesUpdated = 'Îþi mulþumim pentru modificãri. Am actualizat informaþiile tale.';
$strClickHere          = 'Clic Aici';
$strThisLink           = 'acest link';
$strToUnsubscribe      = 'Pentru a te dezabona de la aceastã listã viziteazã';
$strToUpdate           = 'Pentru a-þi modifica preferinþele viziteazã';
$strSendHTML           = 'Trimite e-mail HTML';
$strYes                = 'Da';
$strNo                 = 'Nu';
$strUnsubscribe        = 'Dezaboneazã-te';
$strAllMailinglists    = 'Toate listele';
$strAttachmentIntro		 = 'Acest mesaj conþine ataºamente care pot fi vãzute cu un webbrowser:';
$strLocation					 = 'Locaþie';
$strFrequency					 = 'Cât de des îþi trimitem mesaje';
$strHourly						 = 'În fiecare orã';
$strDaily							 = 'Zilnic';
$strWeekly						 = 'Sãptãmânal';
$strMonthly						 = 'Lunar';
$strChoosePassword 		 = 'Te rugãm sã alegi o parolã';
$strConfirmPassword 	 = 'Confirmã parola';
$strEnterPassword			 = 'Introdu parola';
$strForgotPassword		 = 'Am uitat parola';
$strPassword					 = 'Parola';
$strPassword2					 = 'Confirmã Parola';
$strPasswordsNoMatch 	 = 'Parolele nu sunt aceleaºi';
$strInvalidPassword		 = 'Eroare: E-mail-ul sau parola sunt incorecte';
$strPasswordSent 		   = 'Parola ta a fost trimisã prin e-mail. Ar trebui sã o primeºti în urmãtoarele minute';
$strPasswordRemindSubject = 'Parola ta pentru listele noastre';
$strPasswordRemindMessage = 'Parola ta este ';
$strPasswordRemindInfo = 'Pentru a primi parola prin e-mail, te rugãm sã introduci adresa de e-mail ºi sã apeºi butonul "'.$strForgotPassword.'".';
$strLogin							 = 'Login';
$strLoginTitle 				 = 'Te rugãm sã introduci adresa de e-mail ºi parola';
$strLoginInfo					 = 'Aceastã paginã necesitã o parolã. Te rugãm sã introduci adresa e-mail ºi parola';
$strPersonalLocationInfo = '
	<p>Aceastã paginã necesitã o identificare personalã care poate fi gãsitã în fiecare e-mail pe care þi-l trimitem.<br/>
	Dacã ai apãsat pe aceastã licaþie, ºi primeºti aceastã eroare, te rugãm sã te asiguri cã ai copiat întreaga linie în câmpul de adresã al browserului. Uneori acest link se întinde pe mai multe rânduri</p>
  <p>Dacã nu cunoºti locaþia, poþi solicita un e-mail în care þi se va spune care este. Te rugãm sã introduci adrea de e-mail în câmpul acesta ºi apasã "Continuã"';
$strPersonalLocationSent = '<h1>Succes! Ar trebui sã primeºti un mesaj cu locaþia ta personalã în scurt timp</h1>';
$strUserExists   = '<br/>Un utilizator cu aceastã adresã de e-mail existã deja, ºi înregistrãrile noastre conþin o altã parolã';
$strUserExistsExplanationStart = '<br/>Pentru a obþine parola apasã ';
$strUserExistsExplanationLink = 'aici';
$strUserExistsExplanationEnd = ' pentru a merge la pagina unde poþi sã-þi soliciþi o locaþie personalã';

?>
