<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strName                = 'Ime';
$strAddress             = 'Naslov';
$strEmail               = 'Elektronski naslov';
$strTown                = 'Mesto';
$strPostcode            = 'Poštna št.';
$strSubscribeInfo       = 'Izpolnite spodnji obrazec in se prijavite na enega ali več sklopov novic.';
$strRequired            = 'obvezno polje';
$strSubscribeTitle      = 'Prijavite se na naše novice';
$strPleaseSelect        = 'Prosimo izberite sklope novic, na katere se želite prijaviti';
$strSubmit              = 'Prijavite se na izbrane sklope novic';
$strNotAvailable        = 'Žal ni na voljo noben sklop novic';
$strEnterName           = 'Prosimo vnesite svoje ime';
$strEnterEmail          = 'Prosimo vnesite svoj elektronski naslov';
$strInvalidHostInEmail  = 'Žal na to domeno sporočila ni bilo mogoče dostaviti. Prosimo preverite ali ste pravilno vnesli elektronski naslov.';
$strEnterList           = 'Prosimo izberite sklop novic, na katerega se želite prijaviti';
$strPleaseEnter         = 'Prosimo vnesite ';
# the thanks message can contain placeholders
#$strThanks              = '[FIRST NAME], <br/>Hvala, ker ste se prijavili v naš sistem novic.';
$strThanks              = 'Hvala za prijavo.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Vaš elektronski naslov [email] je bil dodan v naš sistem novic. V kratkem boste prejeli elektronsko sporočilo z zahtevo za potrditev prijave.';
$strEmailConfirmation   = 'Vaš elektronski naslov je bil dodan v sistem novic. V kratkem boste prejeli elektronsko sporočilo z zahtevo za potrditev prijave. Prosimo kliknite na povezavo za potrditev prijave v elektronskem sporočilu.';
$strEmailFailed          = 'Žal pošiljanje sporočila za potrditev prijave ni uspelo. Prosimo kliknite "Osveži" za ponoven poskus. Če to ne zaleže, ste morda na našem "črnem seznamu", kar pomeni, da ne morete prejemati sporočil iz našega sistema novic. V tem primeru kontaktirajte administratorja.';
$strUnsubscribeTitle    = 'Odjavite se od naših sklopov novic';
$strUnsubscribeDone     = 'Odjavljeni ste od naših sklopov novic. V kratkem boste prejeli elektronsko sporočilo za potrditev odjave.';
$strBack                = 'Nazaj';
$strUnsubscribeInfo     = 'Odjavite se od naših sklopov novic';
$strContinue            = 'Naprej';
$strUnsubscribeSelect   = 'Prosimo označite sklope novic od katerih se želite odjaviti';
$strAllLists            = 'Vsi sklopi';
$strNoLists             = 'Noben sklop';
$strUnsubscribeRequestForReason = 'Žal nam je, ker niste več zainteresirani za naše novice. Da bi sistem novic izboljšali, bi vam bili hvaležni, če bi nam zaupali, kaj je botrovalo vaši odločitvi:';
$strUnsubscribeFinalInfo = '<br/><b>Pozor</b>: ta stran je namenjena prenehanju prejemanja sporočil iz našega sistema novic <b>za vedno</b>. Če bi radi le spremenili vaš elektronski naslov ali če bi radi spremenili sklope novic, ki jih prejemate, prosimo <a href="[PREFERENCESURL]">spremenite svoje nastavitve</a>';
$strNoListsFound        = 'Žal na ta naslov ne prejemate nobenega od naših sklopov novic';
$strResubmit            = 'Ponovno vnesite elektronski naslov';
$strUnsubscribeSubmit   = 'Odjavite se od označenih sklopov novic';
$strValuesMissing       = 'Manjkajo naslednji obvezni podatki';
$strConfirmInfo         = 'Hvala, ker ste potrdili vašo prijavo. Sklopi novic, na katere ste prijavljeni so našteti spodaj';
$strConfirmTitle        = 'Stran za potrditev prijave v PHPlist';
$strUserNotFound        = 'Uporabnika ni bilo mogoče najti';
$strUserAlreadyInitialised = 'Vaše geslo je bilo že poslano';
$strConfirmFailInfo     = 'Žal ni bilo mogoče prepoznati vašega zahtevka za potrditev. Preverite ali je v elektronskem sporočilu povezava v enem kosu. Včasi se namreč razdeli na več vrstic.';
$strPreferHTMLEmail     = 'Želim prejemati novice v formatu HTML';
$strPreferTextEmail     = 'Želim prejemati novice v tekstovnem formatu';
$strPreferredFormat      = 'Izbran format sporočil:';
$strText                 = 'Tekst';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Spremenite svoje nastavitve';
$strPreferencesInfo     = 'Preverite ali so vnesene vrednosti pravilne in kliknite gumb "Spremeni"';
$strUpdatePreferences   = 'Spremeni';
$strPreferencesEmailChanged = 'Vaš elektronski naslov je bil spremenenjen. Za potrditev spremembe kliknite na povezavo v elektronskem sporočilu, ki ga boste prejeli v kratkem';
$strYouAreBlacklisted = 'Vaš naslov se nahaja na našem "črnem seznamu", kar pomeni da ne želite več prejemati naših novic. <br/>
Če želite zopet prejemati naše novice, mora za to osebno poskrbeti naš administrator. Pošljite mu sporočilo, da želite zopet prejemati naše novice in odstranjeni boste s "črnega seznama".';
$strPreferencesNotificationSent = 'Prejeli boste elektronsko sporočilo s spremembami';
$strPreferencesUpdated = 'Hvala. Vaše nastavitve so bile spremenjene.';
$strClickHere          = 'Kliknite tukaj';
$strThisLink           = 'to povezavo';
$strToUnsubscribe      = 'Če ne želite več prejemati naših novic, ';
$strToUpdate           = 'Za spremembo nastavitev ali odjavo pojdite na';
$strSendHTML           = 'Pošlji elektrocsko sporočilo v formatu HTML';
$strYes                = 'Da';
$strNo                 = 'Ne';
$strUnsubscribe        = 'Odjavi';
$strAllMailinglists    = 'Vse sklope novic';
$strAttachmentIntro     = 'To sporočilo vsebuje priponke, ki jih je mogoče videti z internetnim brskalnikom:';
$strLocation           = 'Lokacija';
$strFrequency           = 'Kako pogosto želite prejemati naša sporočila';
$strHourly             = 'Na vsako uro';
$strDaily               = 'Dnevno';
$strWeekly             = 'Tedensko';
$strMonthly             = 'Mesečno';
$strChoosePassword      = 'Prosimo izberite geslo';
$strConfirmPassword    = 'Potrdite svoje geslo';
$strEnterPassword       = 'Prosimo vnesite svoje geslo';
$strForgotPassword     = 'Ste pozabili geslo?';
$strPassword           = 'Geslo';
$strPassword2           = 'Potrdite geslo';
$strPasswordsNoMatch    = 'Gesli se ne ujemata';
$strEmailsNoMatch     = 'Vnešena elektronska naslova se ne ujemata';
$strInvalidPassword     = 'Napaka: neveljaven elektronski naslov ali geslo';
$strPasswordSent        = 'Vaše geslo vam je bilo poslano po elektronski pošti. Sporočilo boste prejeli v naslednjih nekaj minutah';
$strPasswordRemindSubject = 'Vaše geslo za naše sklope novic';
$strPasswordRemindMessage = 'Vaše geslo je ';
$strPasswordRemindInfo = 'Če želite prejeti vaše geslo po elektronski pošti, vpišite vaš elektronski naslov in kliknite gumb  "'.$strForgotPassword.'".';
$strLogin               = 'Prijava';
$strLoginTitle          = 'Prosimo vnesite svoj elektronski naslov in geslo';
$strLoginInfo           = 'Za dostop do te strani je potrebno geslo. Prosimo vnesite svoj elektronski naslov in geslo';
$strPersonalLocationInfo = '
  <p>Za dostop do te strani se morate identificirati s podatki, ki smo vam jih poslali po elektronski pošti.<br/>
  Če ste sem prispeli preko povezave in dobili to napako, preglejte če je bila povezava v enem kosu. Včasih se namreč razdeli na več vrstic.</p>
  <p>Če povezave nimate več, lahko zahtevate elektronsko sporočilo, v katerem bo navedena.
  Prosimo vnesite vaš elektronski naslov v okence in kliknite "Naprej"
';
$strPersonalLocationSent = '<h1>Sporočilo z vašo osebno lokacijo vam je bilo uspešno poslano! Prejeli ga boste v naslednjih nekaj minutah.</h1>';
$strUserExists   = '<br/>Uporabnik s tem elektronskim naslovom že obstaja v sistemu, vendar je geslo za ta naslov durgačno od vnešenega';
$strUserExistsExplanationStart = '<br/>Če želite prejeti svoje geslo, kliknite ';
$strUserExistsExplanationLink = 'sem';
$strUserExistsExplanationEnd = ' in obiščite stran za pridobitev osebne lokacije';
$strForwardTitle = 'Posredujte sporočilo';
$strForwardSubtitle = 'Posredovanje sporočilo z zadevo ';
$strForwardEnterEmail = 'Prosimo vnesite veljaven elektronski naslov, kateremu želite posredovati sporočilo';
$strForwardSuccessInfo ='Sporočilo je bilo posredovano';
$strForwardFailInfo = 'Posredovanje sporočila ni uspelo';
$strForwardAlreadyDone = 'To sporočilo je že bilo uspešno posredovano na vnešen elektronski naslov';
$strForwardFooter = 'To sporočilo vam je bilo posredovano s strani [FORWARDEDBY].
  V sistem novic niste bili avtomatsko prijavljeni.
  Če se želite prijaviti na sistem novic, pojdite na';
$strForward = 'Posreduj';
$strFwd = 'Fwd'; # short version of forward for email subject
?>