<?php 
$lan = array(
  "NoRecord" => "Nincs ilyen rekord",
  "BackToBList" => "Vissza a visszapattanók listájához",
  "NotFound" => "Nem található<br/>",
  "AddedToB" => "%s hozzáadva %s visszapattanóinak számához<br/>",
  "NotAddedToB" => "%s-t nem lehetett hozzáadni %s visszapattanóinak számához<br/>",
  "MadeUnconfirmed" => "%s visszaigazolatlanná téve<br/>",
  "MadeUserRText" => "%s szöveges üzenet fogadására téve<br/>",
  "DelUser" => "A(z) %s felhasználó törlése megtörtént<br/>",
  "DeletingB" => "%s visszapattanó törlése ..\n",
  "DoneAndLoading" => "..Kész, a következő visszapattanó betöltése..",
  "NoSRecord" => "Nincs ilyen rekord",
  "PossibleActions" => "Lehetséges műveletek:",
  "ForUser" => "Felhasználó számára, akinek e-mail címe:",
  "IncreaseB" => "A visszapattanók számának követése ezzel:",
  "IncreaseBNote" => "(használjon negatív számokat a csökkentéshez)",
  "MarkAsUnconfirmed" => "A felhasználó megjelölése visszaigazolatlanként",
  "MarkAsUnconfirmedNote" => "(vagyis újraküldheti ezt a jóváhagyási kérést)",
  "SetReceiveText" => "A felhasználó beállítása szöveges üzenet fogadására a HTML helyett",
  "DelUser1" => "Felhasználó törlése",
  "DelAndGo" => "Visszapattanó törlése és folytatás a következővel",
  "DoAbove" => "A fenti végrehajtása",
  "BounceDetails" => "Visszapattanó részletei:",
  "ID" => "AZ",
  "Date" => "Dátum",
  "Status" => "Állapot",
  "Comment" => "Megjegyzés",
  "Header" => "Fejléc",
  "Body" => "Törzs",
  
  # new in 2.9.5
  'Regular Expression' => 'Reguláris kifejezés',
  'Action' => 'Művelet',
  'Memo for this rule' => 'Emlékeztető ehhez a szabályhoz',
  'Add new Rule' => 'Új szabály alkotása',
  'Create New Rule based on this bounce' => 'Új szabály alkotása ezen visszapattanó alapján',
);
?>