<?php
$lan = array( 
 'checklist for installation' => 'Telepítési ellenőrzőlista',
 'cannot be empty' => 'nem lehet üres',
 'editing' => 'Szerkesztés',
 'save changes' => 'Módosítások mentése',
 'edit' => 'módosítás',

  # added 24 May 2006
  'delete user' => 'felhasználó törlése',
  'unconfirm user' => 'felhasználó vissza nem igazolása',
  'blacklist user' => 'felhasználó feketelistára vétele',
  'delete user and bounce' => 'a felhasználó és a visszapattanó törlése',
  'unconfirm user and delete bounce' => 'a felhasználó vissza nem igazolása és a visszapattanó törlése',
  'blacklist user and delete bounce' => 'a felhasználó feketelistára vétele és a visszapattanó törlése',
  'delete bounce' => 'visszapattanó törlése',
  'Website address (without http://)' => 'A weblap címe (http:// protokoll nélkül)',
  'Domain Name of your server (for email)' => 'A kiszolgáló tartományneve (e-mailhez)',
  'Person in charge of this system (one email address)' => 'A rendszerért felelős személy (egy e-mail cím)',
  'How often do you want to check for a new version of PHPlist (days)' => 'Milyen gyakran kívánja ellenőrizni az új PHPlist verziót (napok)',
  'List of people to CC in system emails (separate by commas)' => 'A rendszerüzenetek másolatait megkapók (vesszővel tagolt) listája',
  'Who gets the reports (email address, separate multiple emails with a comma)' => 'Ki kapja meg a jelentéseket (e-mail cím, több címet vesszővel válasszon el)',
  'From email address for system messages' => 'A rendszerüzenetek feladójának e-mail címe',
  'What name do system messages appear to come from' => 'Milyen név legyen látható a rendszerüzenetek feladójaként',
  'Reply-to email address for system messages' => 'A rendszerüzenetek válaszcíme',
  'if there is only one visible list, should it be hidden in the page and automatically
    subscribe users who sign up (0/1)' => 'Ha csak egy látható lista van, rejtett legyen-e az oldalon, és a jelentkező felhasználók
    automatikusan feliratkoznak (0/1)',
  'width of a textline field (numerical)' => 'A szövegsor mező szélessége (numerikus)',
  'dimensions of a textarea field (rows,columns)' => 'A szövegterület mező méretei (sorok,oszlopok)',
  'Does the admin get copies of subscribe, update and unsubscribe messages (0/1)' => 'Az adminisztrátor megkapja a megrendelő, módosító és lemondó üzeneteket (0/1)',
  'The default subscribe page when there are multiple' => 'Az alapértelmezett rendelési oldal, ha több van',
  'The default HTML template to use when sending a message' => 'Az üzenet küldésekor felhasználandó alapértelmezett HTML sablon',
  'URL where users can subscribe' => 'A megrendelés URL-címe a felhasználók számára',
  'URL where users can unsubscribe' => 'A lemondás URL-címe a felhasználók számára',
  'URL where users have to confirm their subscription' => 'A megrendelés visszaigazolásának URL-címe a felhasználók számára',
  'URL where users can update their details' => 'A felhasználók adatmódosító URL-címe',
  'URL where messages can be forwarded' => 'Az URL-cím, ahol továbbíthatók az üzenetek',
  'Subject of the message users receive when they subscribe' => 'A felhasználók által megkapott megrendelő üzenet tárgya',
  'Message users receive when they subscribe' => 'A felhasználók által megrendeléskor megkapott üzenet',
  'Subject of the message users receive when they unsubscribe' => 'A felhasználók által megkapott lemondó üzenet tárgya',
  'Message users receive when they unsubscribe' => 'A felhasználók által lemondáskor megkapott üzenet',
  'Subject of the message users receive after confirming their email address' => 'A felhasználók által megkapott, az e-mail címet visszaigazoló üzenet tárgya',
  'Message users receive after confirming their email address' => 'Az üzenet, melyet a felhasználók az e-mail címük visszaigazolása után kapnak meg',
  'Subject of the message users receive when they have changed their details' => 'A felhasználók által az adatmódosításról megkapott üzenet tárgya',
  'Message that is sent when users change their information' => 'Az üzenet, melyet a felhasználók adataik módosításakor kapnak meg',
  'Part of the message that is sent to their new email address when users change their information, and the email address has changed' => 'A felhasználóknak az adatmódosításkor és az e-mail cím megváltozásakor az új e-mail címükre megküldendő üzenet része',
  'Part of the message that is sent to their old email address when users change their information, and the email address has changed' => 'A felhasználóknak az adatmódosításkor és az e-mail cím megváltozásakor a régi e-mail címükre megküldendő üzenet része',
  'Subject of message to send when users request their personal location' => 'A személyes helyüket kérő felhasználóknak küldendő üzenet tárgya',
  'Message to send when they request their personal location' => 'Az üzenet, melyet a személyes helyük kérésekor kell elküldeni',
  'Default footer for sending a message' => 'Alapértelmezett lábléc egy üzenet küldéséhez',
  'Footer used when a message has been forwarded' => 'Egy üzenet továbbításakor használt lábléc',
  'Header of public pages. The header should start with &lt;/head&gt; . You can add header elements, but don\'t add the title or other basic header elements.' => 'A nyilvános oldalak fejléce. A fejlécnek a &lt;/head&gt; címkével kell kezdődnie. Adhat hozzá fejléc elemeket, a címet vagy más alapvető fejléc elemet viszont ne adja hozzá.',
  'Footer of public pages' => 'A nyilvános oldalak lábléce',
  'Charset for HTML messages' => 'A HTML-üzenetek karakterkészlete',
  'Charset for Text messages' => 'A szöveges üzenetek karakterkészlete',
  'CSS for HTML messages without a template' => 'A sablon nélküli HTML-üzenetek CSS-e',
  'Domains that only accept text emails, one per line' => 'A csak szöveges üzeneteket fogadó tartományok, soronként egy',
  'Minimum amount of items to send in an RSS feed' => 'Egy RSS-csatornában legalább küldendő elemek száma',
  'Template for text item in RSS feeds' => 'Az RSS-csatornákban lévő szöveges elem sablonja',
  'Template for HTML item in RSS feeds' => 'Az RSS-csatornákban lévő HTML-elem sablonja',
  'Maximum amount of items to send in an RSS feed' => 'Egy RSS-csatornában legfeljebb küldendő elemek mennyisége',
  'Template for separator between feeds in RSS feeds (text)' => 'Az RSS-csatornákban lévő, a csatornák közti elválasztó sablonja (szöveg)',
  'Template for separator between feeds in RSS feeds (HTML)' => 'Az RSS-csatornákban lévő, a csatornák közti elválasztó sablonja (HTML)',
  'Width in px of FCKeditor Area' => 'Az FCKeditor területének szélessége',
  'Height in px of FCKeditor Area' => 'Az FCKeditor területének magassága',
);
?>