<?php

$lan = array(
  'Your database is out of date, please make sure to upgrade' => 'Az adatbázisa elavult, kérjük frissíteni.',
  'Your version' => 'Az Ön verziója',
  'Latest version' => 'Legújabb verzió',
  'phplist version' => '<a href="http://www.phplist.com">phplist</a> verzió',
  'Database has not been initialised' => 'Nem történt meg az adatbázis inicializálása',
  'go to' => 'ugrás',
  'Initialise Database' => 'Adatbázis inicializálása',
  'to continue' => 'folytatni',
  'A new version of PHPlist is available!' => 'Jelent meg új PHPlist verzió!',
  'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => 'Az új verzióban biztonsági problémákat javíthattak,<br/>ezért ajánlatos minél előbb frissíteni',
  'View what has changed' => 'Tekintse meg, hogy mi változott',
  'Download' => 'Letöltés',
  'System Functions' => 'Rendszerfunkciók',
  'Setup ' => 'Telepítés: ',
  'Check Database structure' => 'Az adatbázis-szerkezet elemzése',
  'View the eventlog' => 'Az eseménynapló megtekintése',
  'Configuration functions' => 'Konfigurációs funkciók',
  'Configure Attributes' => 'A tulajdonságok konfigurálása',
  'Control values for' => 'A következő értékeinek ellenőrzése',
  'Control values for' => 'A következő értékeinek ellenőrzése',
  'Control values for' => 'A következő értékeinek ellenőrzése',
  'Configure Subscribe pages' => 'A rendelési oldalak konfigurálása',
  'List and user functions' => 'Lista és felhasználói funkciók',
  'List the current lists' => 'A jelenlegi listák listája',
  'List all Users' => 'Az összes felhasználó listája',
  'Reconcile the user database' => 'A felhasználói adatbázis újraegyeztetése',
  'Import Users' => 'A felhasználók importálása',
  'Export Users' => 'A felhasználók exportálása',
  'Administrator functions' => 'Adminisztrátori funkciók',
  'Add, edit and remove Administrators' => 'Adminisztrátorok hozzáadása, módosítása és eltávolítása',
  'Configure attributes for administrators' => 'Az adminisztrátorok tulajdonságainak beállítása',
  'Message functions' => 'Üzenet funkciók',
  'Configure Templates' => 'Sablonok beállítása',
  'List all Messages' => 'Az összes üzenet listája',
  'Process the Message queue' => 'Az Üzenet várólista feldolgozása',
  'RSS Functions' => 'RSS funkciók',
  'Get RSS feeds' => 'RSS-csatornák lekérése',
  'View RSS items' => 'RSS-elemek megtekintése',
  'Plugins' => 'Beépülő modulok',
  'Upgrade' => 'Frissítés',
'Change your details (e.g. password)' => 'Az Ön adatainak módosítása (pl. jelszó)',
'You have set TEST in config.php to 1, so it will only show what would be sent' => 'A config.php fájlban a TEST paraméter értéke 1, vagyis csak azt fogja megmutatni, hogy mi kerülne elküldésre',

  # added at a later stage
  'setup' => 'telepítés',
  'upgrade' => 'frissítés',
  'dbcheck' => 'adatbázis-ellenőrzés',
  'eventlog' => 'eseménynapló',
  'attributes' => 'tulajdonságok',
  'spage' => 'rendelésioldal',
  'list' => 'lista',
  'reconcileusers' => 'felhasználókújraegyeztetése',
  'import' => 'importálás',
  'export' => 'exportálás',
  'admins' => 'adminisztrátorok',
  'adminattributes' => 'admintulajdonságok',
  'send' => 'küldés',
  'templates' => 'sablonok',
  'processqueue' => 'várólistafeldolgozása',
  'processbounces' => 'visszapattanókfeldolgozása',
  'getrss' => 'rsslekérése',
  'viewrss' => 'rssmegtekintése',
  'admin' => 'admin',
  'preparesend' => 'küldéselőkészítése',
  'sendprepared' => 'előkészítettekküldése',


);

?>