<?php 
$lan = array(

  'add_list' => 'Lista hozzáadása', //duplicated in import1_text
  'cant_connect' => 'nem lehet csatlakozni a távoli adatbázishoz',
  'no_users_to_copy' => 'Nincs másolandó felhasználó, jó az előtag?',
  'remote_server' => 'Írja be a távoli kiszolgáló adatait',
  'server' => 'Kiszolgáló:',
  'user' => 'Felhasználónév:',
  'passwd' => 'Jelszó:',
  'database' => 'Adatbázis neve:',
  'table_prefix' => 'Táblanév előtag:',
  'usertable_prefix' => 'Felhasználó-táblanév előtag:',
  'select_lists' => 'Jelölje be azokat a listákat, melyekhez hozzá akarja adni az e-mail címeket',
  'copy_lists' => 'Listák másolása távoli kiszolgálóról (a listák egyeztetése név alapján)',
  'users_as_html' => 'Az új felhasználók megjelölése HTML-ként:',
  'info_overwrite_existing' => 'Ha bejelöli a "Meglévők felülírása" beállítást, akkor a felhasználó adatbázisban lévő adatai lecserélésre kerülnek az importált adatokkal. A felhasználók egyeztetése az e-mail cím alapján történik.',
  'overwrite_existing' => 'Meglévők felülírása:',
  'connecting_remote' => 'Csatlakozás a távoli adatbázishoz',
  'getting_data' => 'Adatok lekérése innen: ',
  'remote_version' => 'A távoli változat',
  'remote_has' => 'A távoli verziónak van',
  'users' => 'felhasználók',
  'lists' => 'listák',
  'copying_lists' => 'Listák másolása',
  'list' => 'Lista',
  'exists_locally' => 'helyileg létezik',
  'created_locally' => 'helyben létrehozva',
  'remote_list' => 'Távoli lista',
  'not_created' => 'nincs létrehozva',
  'copying_attribs' => 'Tulajdonságok másolása',
  'attrib' => 'Tulajdonság',
  'copying_users' => 'Felhasználók másolása',
  'overwrite_local' => 'a helyi adatok felülírása',
  'keep_local' => 'a helyi adatok megőrzése',
  'new_user' => 'egy új felhasználó',
  'no_mapped_attrib' => 'Hiba: Nincs egyeztetett tulajdonság a következőhöz:',
  'no_local_list' => 'Hiba: Nincs helyi lista meghatározva a következőhöz:',
  'No lists available' => 'Nincsenek listák',
  'Done' => 'Kész',
  'new users' => 'új felhasználók',
  'and' => 'és',
  'existing users' => 'létező felhasználók',
  'continue' => 'Folytatás',

);
?>