<?php
$lan = array(
  "Import emails from IMAP folders" => "E-mail címek importálása IMAP-mappákból",
  "No lists available" => "Nincsenek listák",
  "Add a list" => "Lista hozzáadása",
  "personal" => "személyes",
  "email" => "e-mail cím",
  "folder" => "mappa",
  "date" => "dátum",
  "can't connect" => "nem lehet csatlakozni",
  "Processing" => "Feldolgozandó",
  "messages" => "üzenet",
  "done" => "kész",
  "imap_getmailboxes failed" => "az imap_getmailboxes nem sikerült",
  "Please enter details of the IMAP account" => "Írja be az IMAP-fiók adatait",
  "Select the headers fields to search" => "Válassza ki a fejléc mezőket a kereséshez",
  "Select the lists to add the emails to" => "Jelölje be azokat a listákat, melyekhez hozzá akarja adni az e-mail címeket",
  "Adding users to list" => "Felhasználók felvétele a következő listára:",
  "Mark new users as HTML" => "Az új felhasználók megjelölése HTML-ként",
/* read lines below as sentences: if you check 'overwrite' information about a user... etc. */
  "If you check" => "Ha bejelöli",
  "Overwrite Existing" => "Meglévők felülírása",
  "information about a user in the database will be replaced by the imported information. Users are matched by email." => "a felhasználóról az adatbázisban tárolt információkat kicseréli az importált adatokkal. A felhasználók egyeztetése e-mail cím alapján történik.",
  "Only use complete addresses" => "Csak teljes címek használata",
  "addresses that do not have a real name will be ignored. Otherwise all emails will be imported." => "a valódi névvel nem rendelkező címek mellőzésre kerülnek. Egyéb esetben az összes e-mail cím importálásra kerül.",
  "If you choose" => "Ha választja",
  "send notification email" => "értesítő e-mail küldése",
  "the users you are adding will be sent the request for confirmation of subscription to which they will have to reply. This is recommended, because it will identify invalid emails." => "az Ön által hozzáadni kívánt felhasználóknak a PHPlist elküldi a feliratkozás visszaigazolásának kérését, melyre válaszolniuk kell. Ez azért ajánlott, mert így beazonosítja az érvénytelen e-mail címeket.",
  "Send&nbsp;Notification&nbsp;email&nbsp;" => "Értesítő&nbsp;e-mail&nbsp;küldése&nbsp;",
  "Make confirmed immediately" => "Azonnali visszaigazolttá tétel",
  "import3info" => "A felhasználók nevei hozzáadásának két módja van,
 vagy egy tulajdonság a teljes névnek, vagy két tulajdonság, az egyik az utónévnek, a másik a vezetéknévnek.
A 'Két tulajdonság' használatakor a név az első szóköz után kerül felosztásra.",
  "Use one attribute for name" => "Egy tulajdonság használata a névhez",
  'Use two attributes for the name' => 'Két tulajdonság használata a névhez',
  "Attribute one" => "Első tulajdonság",
  "Create Attribute" => "Tulajdonság létrehozása",
  "Attribute two" => "Második tulajdonság",
  "Cannot continue" => "Nem folytatható",
  "ok" => "ok",
  "failed" => "sikertelen",
  "Processed" => "Feldolgozva",
  "folders and" => "mappa és",
  "unique emails found" => "egyedi e-mail cím található",
  "list" => "lista",
  "lists" => "listák",
  "new email was" => "új e-mail volt",
  "new emails were" => "új e-mailek voltak",
  "email was" => "e-mail volt",
  "emails were" => "e-mailek voltak",
  "All the emails already exist in the database and are members of the" => "Az összes e-mail már az adatbázisban van, és a következők tagjai:",
  "succesfully imported to the database and added to" => "importálásuk és hozzáadásuk sikerült az adatbázisba",
  "subscribed to the" => "feliratkozott a(z)",
  "emails already existed in the database" => "e-mail cím már volt az adatbázisban",
  "Invalid Emails found." => "Hibás e-mail címek találhatók.",
  "These records were added, but the email has been made up. You can find them by doing a search on" => "Ezek a rekordok kerültek hozzáadásra, viszont az e-mail ki lett egészítve. A következő keresésével találhatja meg őket:",
  "These records were deleted. Check your source and reimport the data. Duplicates will be identified." => "Ezek a rekordok törlésre kerültek. Ellenőrizze a forrást, s importálja újra az adatokat. A phplist be fogja azonosítani a duplumokat.",
  "No emails found" => "Nem találhatók e-mail címek",
  "Import some more emails" => "Még néhány e-mail cím importálása",
  'Server' => 'Kiszolgáló',
  'User' => 'Felhasználónév',
  'Password' => 'Jelszó',
  'Continue' => 'Folytatás',
  'Process Selected Folders' => 'Kiválasztott mappák feldolgozása',
);
?>