<?php
$lan = array(
  'You do not have enough priviliges to view this page' => 'Ezen oldal megtekintéséhez Ön nem rendelkezik elegendő joggal',
  'Add a user' => 'Felhasználó hozzáadása',
  'add user' => 'Felhasználó hozzáadása',
  'Members of' => 'A következő lista tagjai:',
  'Tag all users in this page' => 'Az oldalon lévő összes felhasználó címkézése',
  'back to this list' => 'vissza a listához',
  'Download users on this list as a CSV file' => 'A listán lévő felhasználók letöltése CSV fájlként',
  'Please enter a listid' => 'Írja be a lista azonosítószámát',
  'Processing' => 'Feldolgozandó',
  'users were moved to' => 'felhasználó került áthelyezésre ide:',
  'users were copied to' => 'felhasználó került másolásra ide:',
  'users were deleted from this list' => 'felhasználó került törlésre erről a listáról',
  'Users found, click add to add this user' => 'felhasználó található, kattintson a Hozzáadás gombra a felhasználó hozzáadásához',
  'Add' => 'Hozzáadás',
  'No user found with that email' => 'Nem található ezzel az e-mail címmel rendelkező felhasználó',
  'Inserting user' => 'Felhasználó beszúrása',
  'User added' => 'A felhasználó hozzáadása megtörtént',
  'Deleting' => 'Törlés',
  'Done' => 'Kész',
  'Users on this list' => 'felhasználó tagja a listának',
  'Listing user' => 'Felhasználó listázása',
  'to' => '-',//in sentence 'listing user 1  to  50'
  'Listing user 1 to 50' => 'Felhasználó listázása, 1 - 50',
  'Members' => 'Tagok',
  'confirmed' => 'visszaigazolt',
  'tag' => 'címke',
  'del' => 'törlés',
  'Delete'=>'Törlés',
  '# msgs' => 'üz #',
  '# rss' => 'rss #',
  'rss freq' => 'rss gyak',
  'last sent' => 'utolsó küldés',
  'What to do with "Tagged" users' => 'Mi a teendő a "Címkézett" felhasználókkal',
  'This will only process the users in this page that have the "Tag" checkbox checked' => 'Csak azokat a felhasználókat fogja feldolgozni ezen az oldalon, akiknél bejelölte a "Címke" jelölőnégyzetet',
  'delete' => 'Törlés',
  'move' => 'Áthelyezés',
  'copy' => 'Másolás',
  'nothing' => 'Semmi',
  'to' => 'ide:', # as in destination
  'from this list' => 'erről a listáról',
  'What to do with all users' => 'Mi a teendő az összes felhasználóval',
  'This will process all users on this list' => 'A listán lévő összes felhasználót fogja feldolgozni',
  'do it' => 'csináld',
  
  
);
?>