<?php
$lan = array(
 'Please select a message to display' => 'Válassza ki a megjelenítendő üzenetet',
 'Attachments for this message' => 'Az üzenet mellékletei',
 'No attachments' => 'Nincsenek mellékletek',
 'Filename' => 'Fájlnév',
 'Size' => 'Méret',
 'Mime Type' => 'Mime-típus',
 'Description' => 'Leírás',
 'Lists this message has been sent to' => 'Listák, melyeknek ez az üzenet elküldésre került',
 'None yet' => 'Még nincs',
 'Send this (same) message to (a) new list(s)' => '(Ugyan)ennek az üzenetnek a küldése új listá(k)ra',
 'List is Active' => 'A lista aktív',
 'List is not Active' => 'A lista nem aktív',
 '<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the "Requeue" function.' => '<b>Megjegyzés:</b> Ez az üzenet már az összes listán elküldésre került. Ha szeretné az új felhasználóknak újraküldeni, akkor használja az "Ismételt várólistára vétel" funkciót.',
 'Resend' => 'Újraküldés',
 'id' => 'az',
 'subject' => 'tárgy',
 'fromfield' => 'feladó mező',
 'tofield' => 'címzett mező',
 'replyto' => 'válaszcím',
 'message' => 'üzenet',
 'textmessage' => 'szöveges üzenet',
 'footer' => 'lábléc',
 'entered' => 'beírva',
 'modified' => 'módosítva',
 'embargo' => 'zárolás',
 'repeatinterval' => 'ismétlődésiidőköz',
 'repeatuntil' => 'ismétlődésihatáridő',
 'status' => 'állapot',
 'userselection' => 'felhasználóiválasztás',
 'sent' => 'elküldve',
 'htmlformatted' => 'htmlformátumú',
 'sendformat' => 'küldésformátuma',
 'template' => 'sablon',
 'processed' => 'feldolgozva',
 'astext' => 'szövegként',
 'ashtml' => 'html-ként',
// 'astextandhtml' => 'szövegként és html-ként', //obsolete by bug 0009687
 'aspdf' => 'pdf-ként',
 'astextandpdf' => 'szövegként és pdf-ként',
 'viewed' => 'megtekintve',
 'bouncecount' => 'visszapattanók száma',
 'sendstart' => 'küldés indítása',
 'rsstemplate' => 'RSS-sablon',
 'owner' => 'tulajdonos',

 # new in 2.10.1
 'edit this message' => 'Üzenet szerkesztése',
);
?>
