<?php

$lan = array(
'Running in testmode, no emails will be sent. Check your config file.' => 'A PHPlist próba üzemmódban fut, nem küld el e-maileket. Ellenőrizze a konfgurációs fájlt.',
'The following restrictions have been set by your ISP:' => 'Az internetszolgáltatója a következő korlátozásokat szabta meg:',
'Script stage' => 'Parancsfájl állapota',
'Finished, Nothing to do' => 'Befejeződött, nincs tennivaló.',
'messages sent in' => 'üzenet elküldve in',
'seconds' => 'másodperc',
'invalid emails' => 'érvénytelen e-mail címek',
'emails failed (will retry later)' => 'sikertelen e-mail címek (újabb próba később)',
'emails unconfirmed (not sent)' => 'nem visszaigazolt e-mail címek (nincs elküldve)',
'Warning: script never reached stage 5' => 'Figyelmeztetés: a parancsfájl sohasem lépett az 5. szakaszba',
'This may be caused by a too slow or too busy server' => 'Ezt túl lassú vagy túl leterhelt kiszolgáló okozhatja',


'In safe mode, batches are set to a maximum of 100' => 'Biztonságos módban legfeljebb 100-ra állítottak a kötegek',
'Running in safe mode' => 'Futás biztonságos módban',
'msgs/hr' => 'üz/óra',
'Reload required' => 'Szükségesek újratöltése',
'Finished, All done' => 'Befejeződött, mind kész.',
'Script finished, but not all messages have been sent yet.' => 'A parancsfájl befejeződött, de még nem küldte el az összes üzenetet.',
'Finished this run' => 'A futás befejeződött',
'(test)' => '(teszt)',
'Would have sent' => 'El lett volna küldve',
'(test)' => '(teszt)',
'Would have sent' => 'El lett volna küldve',
'Started' => 'Elindult',
'Processing has been suspended by your ISP, please try again later' => 'Az internetszolgáltató felfüggesztette a feldolgozást. Próbálja meg később',
'Sending in batches of' => 'Küldés kötegekben of',
'emails' => 'e-mail',
'This batch will be' => 'Ez a köteg',
'emails, because in the last' => 'e-mail lesz, mert az utolsó',
'emails were sent' => 'e-mail lett elküldve',
'Sending in batches of' => 'Küldés kötegekben of',
'emails' => 'e-mail',
'In the last' => 'Az utolsó',
'seconds more emails were sent' => 'másodpercben több e-mail került elküldésre,',
'than is currently allowed per batch' => 'mint jelenleg kötegenként engedélyezett',
'Sent in last run' => 'Az utolsó futáskor elküldöttek',
'Skipped in last run' => 'Az utolsó futáskor kihagyottak',
'Processing has started,' => 'A feldolgozás megkezdődött,',
'message(s) to process.' => 'üzenet dolgozandó fel.',
'It is safe to click your stop button now, report will be sent by email to' => 'Most nyugodtan kattinthat a "leállítás" gombra, a jelentés a következőnek kerül e-mailben elküldésre:',
'Your webserver is running in safe_mode. Please keep this window open. It may reload several times to make sure all messages are sent.' => 'A webkiszolgáló "safe_mode" beállítással fut. Hagyja nyitva ezt az ablakot. Több alkalommal újratöltődhet, hogy megbizonyosdhasson arról, az összes üzenet elküldésre került.',
'Reports will be sent by email to' => 'A jelentések e-mailben kerülnek elküldésre a következőnek:',
'Processing message' => 'Feldolgozandó üzenet:',
'Message' => 'Üzenet',
'is an RSS feed for' => 'egy RSS-csatorna a következőhöz:',
'Looking for users' => 'Felhasználók keresése',
'users apply for attributes, now checking lists' => 'a felhasználók alkalmazása a tulajdonságokra, most a listák ellenőrzése van folyamatban',
'No users apply for attributes' => 'Egy felhasználó sem érvényes a tulajdonságokra',
'looking for users who can be excluded from this mailing' => 'felhasználók keresése, akik kizárhatók ebből a várólista feldolgozási lefuttatásból',
'Process Killed by other process' => 'Egy másik folyamat leállította a folyamatot',
'Found them' => 'Találtak',
'to process' => 'feldolgozandó',
'No users to process for this batch' => 'Nincsenek ehhez a köteghez feldolgozandó felhasználók',
'batch limit reached' => 'elérkezett a köteg korlátozása',
'Process Killed by other process' => 'Egy másik folyamat leállította a folyamatot',
'Message I was working on has disappeared' => 'Az üzenet, melyen dolgoztam, eltűnt',
'Sending' => 'Küldés',
'It took' => 'A küldéshez',
'seconds to send' => 'másodpercre volt szükség',
'Failed sending to' => 'A küldés nem sikerült a következőnek',
'Unconfirmed user' => 'Nem visszaigazolt felhasználó',
'Not sending to' => 'Nem küldendő a következőnek:',
'already sent' => 'már elküldve',
'Processed' => 'Feldolgozva',
'out of' => '/',
'Hmmm, No users found to send to' => 'Hmmm. Nem találhatók felhasználók, akiknek küldhető',
'It took' => 'Az üzenet küldéséhez',
'to send this message' => 'volt szükség',
'waiting for' => 'a következőre várás:',
'to make sure we don\'t exceed our limit of' => 'meggyőződni arról, hogy nem lépjük-e túl a korlátozásunkat of',
'messages in' => 'üzenet in',

### new in 2.9.5
'Message Sending has started' => 'Az üzenet küldése megkezdődött',
'phplist has started sending the message with subject %s' => 'A phplist megkezdte a(z) %s tárgyú üzenet küldését',
'to view the progress of this message, go to %s' => 'ezen üzenet haladásának megtekintéséhez menjen %s',
'There have been more than 10 attempts to send to %s that have been blocked for domain throttling.' => 'Több, mint 10 kísérlet történt a(z) %s címre történő küldéshez, mely tartományszabályozáshoz került blokkolásra.',
'Introducing extra delay to decrease throttle failures' => 'További késleltetés bevezetése a szabályozási hibák csökkentése végett',
'%s is currently over throttle limit of %d per %d seconds' => '%s jelenleg a(z) %d per %d másodperc szabályozási korlátozás fölött van',
'not sending to ' => 'nem küld a következő címre ',
'Message Sending has finished' => 'Az üzenet küldése befejeződött',
'phplist has finished sending the message with subject %s' => 'A phplist befejezte a(z) %s tárgyú üzenet küldését',

'Sending of this message has been suspended' => 'Az üzenet küldése felfüggesztésre került',

# new in 2.10.1
'Less than batch size were sent, so reloading imminently' => 'A köteg méreténél kevesebb került elküldésre, ezért az újratöltés elkerülhetetlen',
'Waiting for %d seconds before reloading' => '%d másodperc várakozás az újratöltés előtt',
'Please leave this window open. You have batch processing enabled, so it will reload several times to send the messages. Reports will be sent by email to' => 'Hagyja nyitva ezt az ablakot. Ön engedélyezte a tömeges feldolgozást, ezért többször újra fog tölteni az üzenetek elküldéséhez. A jelentések e-mailben kerülnek elküldésre a következőnek:',

);

?>