<?php
$lan = array(
  'Resending confirmation request to' => 'A visszaigazolási kérés újraküldése a következő jelentkező számára:',
  'user found' => 'felhasználó található',
  'no user found' => 'nem található felhasználó',
  'unable to find original email' => 'nem található az eredeti e-mail',
  'Marking all users confirmed' => 'Az összes felhasználó megjelölése visszaigazoltként',
  'users apply' => 'felhasználóra érvényes',
  'Creating UniqID for all users who do not have one' => 'UniqID készítése mindazon felhasználóknak, akiknek nincs',
  'Marking all users to receive HTML' => 'Az összes felhasználó bejelölése HTML-üzenet fogadásához',
  'Marking all users to receive text' => 'Az összes felhasználó bejelölése szöveges üzenet fogadásához',
  'Deleting users who are not on any list' => 'Az egyik listán sem szereplő felhasználók törlése',
  'Moving users who are not on any list to' => 'Az egyik listán sem szereplő felhasználók áthelyezése',
  'Deleting users with more than' => 'Felhasználók törlése, akiknek több, mint',
  'bounces' => 'visszapattanója van',
  'Resending request for confirmation to users who signed up after' => 'Visszaigazolás kérésének küldése az utána jelentkező felhasználóknak',
  'and before' => 'és előtte',
  'Deleting unconfirmed users who signed up after' => 'A visszaigazolatlan felhasználók törlése, akik utána jelentkeztek',
  'Trying to merge duplicates' => 'A duplumok összevonásának megpróbálása',
  'Don\'t know how to' => 'Nem tudom, hogyan',
  'Listing users with an invalid email' => 'Érvénytelen e-mail címmel rendelkező felhasználók listázása',
  'Users deleted' => 'A felhasználók törlése megtörtént',
  'Users apply' => 'Alkalmazás felhasználókra',
  'Trying to fix users with an invalid email' => 'Az érvénytelen e-mail címmel rendelkező felhasználók javításának megpróbálása',
  'User' => 'Felhasználó',
  'Users fixed' => 'A felhasználók javítása megtörtént',
  'Users could not be fixed' => 'Nem lehetett megjavítani a felhasználókat',
  'Deleting users with an invalid email' => 'Érvénytelen e-mail címmel rendelkező felhasználók törlése',
  'Marking users with an invalid email as unconfirmed' => 'Az érvénytelen e-mail címmel rendelkező felhasználók megjelölése nem visszaigazoltként',
  'Users updated' => 'A felhasználók frissítése megtörtént',
  'Cleaning some user tables of invalid entries' => 'Érvénytelen bejegyzések törlése néhány felhasználói táblából',
  'entries apply' => 'alkalmazás bejegyzésekre',
  'Delete will delete user and all listmemberships' => 'A Törlés törölni fogja a felhasználót és annak összes listatagságát',
  'Done' => 'Kész',
  'Users' => 'felhasználó',
  'found' => 'található',
  'in the database' => 'az adatbázisban',
  'Delete all users who are not subscribed to any list' => 'Az egyik listára sem feliratkozott felhasználók törlése',
  # next two are one sentence
  'To try to (automatically)' => '(Automatikus) próba:',
  'Find users who have an invalid email' => 'Az érvénytelen e-mail címmel rendelkező felhasználók megkeresése',
  'Make sure that all users have a UniqID' => 'Az összes felhasználó egyedi azonosítószámának ellenőrzése',
  'Mark all users with an invalid email as unconfirmed' => 'Az érvénytelen e-mail címmel rendelkező felhasználók megjelölése nem visszaigazoltként',
  'Delete users who have an invalid email' => 'Az érvénytelen e-mail címmel rendelkező felhasználók törlése',
  'Mark all users to receive HTML' => 'Az összes felhasználó megjelölése a HTML-formátumú üzenetek fogadására',
  'Mark all users to receive text' => 'Az összes felhasználó megjelölése a szöveges üzenetek fogadására',
  'Mark all users confirmed' => 'Az összes felhasználó megjelölése visszaigazoltként',
  'Fix emails for users who have an invalid email' => 'Az érvénytelen e-mail címmel rendelkező felhasználók e-mail címeinek javítása',
  'Remove Stale entries from the database' => 'Az elavult bejegyzések eltávolítása az adatbázisból',
  'Merge Duplicate Users' => 'A dupla felhasználók összevonása',
  'To move all users who are not subscribed to any list to' => 'Az egyik listára sem feliratkozott felhasználók áthelyezése a következő listába:',
  'Click here' => 'Kattintson ide',
  'To delete all users with more than' => 'Mindazon felhasználó törlése, akiknek több, mint',
  'bounces' => 'visszapattanójuk van',
  'Note: this will use the total count of bounces on a user, not consecutive bounces' => 'Megjegyzés: Ez a lehetőség egy felhasználó visszapattanóinak összes számát fogja használni, nem az egymást követő visszapattanókét',
  'To resend the request for confirmation to users who signed up and have not confirmed their subscription' => 'A visszaigazolási kérés újraküldése azoknak a felhasználóknak, akik jelentkeztek és nem igazolták vissza a feliratkozásukat',
  'Date they signed up after' => 'A jelentkezés utáni dátum',
  'Date they signed up before' => 'A jelentkezés előtti dátum',
  'Text to prepend to email' => 'Az e-mail elejéhez hozzáfűzendő szöveg',
  'prependemailtext' => '
Elnézést kérünk a zavarásért: takarítjuk az adatbázisunkat, 
s úgy tűnik, hogy Ön valamikor jelentkezett a levelező listáinkra, 
s nem igazolta vissza a jelentkezését.

Szeretnénk Önnek lehetőséget adni a feliratkozás ismételt 
visszaigazolásához. Az utasításokat alább találja.
  ',
  'To delete users who signed up and have not confirmed their subscription' => 'A jelentkezett és a feliratkozásukat vissza nem igazolt felhasználók törlése',

  # new in 2.10.1
  'Delete Tagged Users' => 'Címkézett felhasználók törlése',


);
?>