<?php 
$lan = array(
  "NoRecord" => "No such record",
  "BackToBList" => "Back to the list of bounces",
  "NotFound" => "Not Found<br/>",
  "AddedToB" => "Added %s to bouncecount for user %s<br/>",
  "NotAddedToB" => "Could not add %s to bouncecount for user %s<br/>",
  "MadeUnconfirmed" => "Made user %s unconfirmed<br/>",
  "MadeUserRText" => "Made user %s to receive text<br/>",
  "DelUser" => "Deleted user %s<br/>",
  "DeletingB" => "Deleting bounce %s ..\n",
  "DoneAndLoading" => "..Done, loading next bounce..",
  "NoSRecord" => "No such Record",
  "PossibleActions" => "Possible Actions:",
  "ForUser" => "For user with email",
  "IncreaseB" => "Increase bouncecount with",
  "IncreaseBNote" => "(use negative numbers to decrease)",
  "MarkAsUnconfirmed" => "Mark user as unconfirmed",
  "MarkAsUnconfirmedNote" => "(so you can resend the request for confirmation)",
  "SetReceiveText" => "Set user to receive text instead of HTML",
  "DelUser1" => "Delete user",
  "DelAndGo" => "Delete this bounce and go to the next",
  "DoAbove" => "Do the above",
  "BounceDetails" => "Bounce Details:",
  "ID" => "ID",
  "Date" => "Date",
  "Status" => "Status",
  "Comment" => "Comment",
  "Header" => "Header",
  "Body" => "Body",
  
  # new in 2.9.5
  'Regular Expression' => 'Regular Expression',
  'Action' => 'Action',
  'Memo for this rule' => 'Memo for this rule',
  'Add new Rule' => 'Add new Rule',
  'Create New Rule based on this bounce' => 'Create New Rule based on this bounce',
);
?>