<?php
$lan = array( 
 'checklist for installation' => 'Checklist for Installation',
 'cannot be empty' => 'cannot be empty',
 'editing' => 'Editing',
 'save changes' => 'Save changes',
 'edit' => 'edit',

  # added 24 May 2006
  'delete user' => 'delete user',
  'unconfirm user' => 'unconfirm user',
  'blacklist user' => 'blacklist user',
  'delete user and bounce' => 'delete user and bounce',
  'unconfirm user and delete bounce' => 'unconfirm user and delete bounce',
  'blacklist user and delete bounce' => 'blacklist user and delete bounce',
  'delete bounce' => 'delete bounce',
  'Website address (without http://)' => 'Website address (without http://)',
  'Domain Name of your server (for email)' => 'Domain Name of your server (for email)',
  'Person in charge of this system (one email address)' => 'Person in charge of this system (one email address)',
  'How often do you want to check for a new version of phplist (days)' => 'How often do you want to check for a new version of phpList (days)',
  'List of people to CC in system emails (separate by commas)' => 'List of people to CC in system emails (separate by commas)',
  'Who gets the reports (email address, separate multiple emails with a comma)' => 'Who gets the reports (email address, separate multiple emails with a comma)',
  'From email address for system messages' => 'From email address for system messages',
  'What name do system messages appear to come from' => 'What name do system messages appear to come from',
  'Reply-to email address for system messages' => 'Reply-to email address for system messages',
  'if there is only one visible list, should it be hidden in the page and automatically
    subscribe users who sign up (0/1)' => 'if there is only one visible list, should it be hidden in the page and automatically
    subscribe users who sign up (0/1)',
  'width of a textline field (numerical)' => 'width of a textline field (numerical)',
  'dimensions of a textarea field (rows,columns)' => 'dimensions of a textarea field (rows,columns)',
  'Does the admin get copies of subscribe, update and unsubscribe messages (0/1)' => 'Does the admin get copies of subscribe, update and unsubscribe messages (0/1)',
  'The default subscribe page when there are multiple' => 'The default subscribe page when there are multiple',
  'The default HTML template to use when sending a message' => 'The default HTML template to use when sending a message',
  'URL where users can subscribe' => 'URL where users can subscribe',
  'URL where users can unsubscribe' => 'URL where users can unsubscribe',
  'URL where users have to confirm their subscription' => 'URL where users have to confirm their subscription',
  'URL where users can update their details' => 'URL where users can update their details',
  'URL where messages can be forwarded' => 'URL where messages can be forwarded',
  'Subject of the message users receive when they subscribe' => 'Subject of the message users receive when they subscribe',
  'Message users receive when they subscribe' => 'Message users receive when they subscribe',
  'Subject of the message users receive when they unsubscribe' => 'Subject of the message users receive when they unsubscribe',
  'Message users receive when they unsubscribe' => 'Message users receive when they unsubscribe',
  'Subject of the message users receive after confirming their email address' => 'Subject of the message users receive after confirming their email address',
  'Message users receive after confirming their email address' => 'Message users receive after confirming their email address',
  'Subject of the message users receive when they have changed their details' => 'Subject of the message users receive when they have changed their details',
  'Message that is sent when users change their information' => 'Message that is sent when users change their information',
  'Part of the message that is sent to their new email address when users change their information, and the email address has changed' => 'Part of the message that is sent to their new email address when users change their information, and the email address has changed',
  'Part of the message that is sent to their old email address when users change their information, and the email address has changed' => 'Part of the message that is sent to their old email address when users change their information, and the email address has changed',
  'Subject of message to send when users request their personal location' => 'Subject of message to send when users request their personal location',
  'Message to send when they request their personal location' => 'Message to send when they request their personal location',
  'Default footer for sending a message' => 'Default footer for sending a message',
  'Footer used when a message has been forwarded' => 'Footer used when a message has been forwarded',
  'Header of public pages. The header should start with &lt;/head&gt; . You can add header elements, but don\'t add the title or other basic header elements.' => 'Header of public pages. The header should start with &lt;/head&gt; . You can add header elements, but don\'t add the title or other basic header elements.',
  'Footer of public pages' => 'Footer of public pages',
  'Charset for HTML messages' => 'Charset for HTML messages',
  'Charset for Text messages' => 'Charset for Text messages',
  'CSS for HTML messages without a template' => 'CSS for HTML messages without a template',
  'Domains that only accept text emails, one per line' => 'Domains that only accept text emails, one per line',
  'Minimum amount of items to send in an RSS feed' => 'Minimum amount of items to send in an RSS feed',
  'Template for text item in RSS feeds' => 'Template for text item in RSS feeds',
  'Template for HTML item in RSS feeds' => 'Template for HTML item in RSS feeds',
  'Maximum amount of items to send in an RSS feed' => 'Maximum amount of items to send in an RSS feed',
  'Template for separator between feeds in RSS feeds (text)' => 'Template for separator between feeds in RSS feeds (text)',
  'Template for separator between feeds in RSS feeds (HTML)' => 'Template for separator between feeds in RSS feeds (HTML)',
  'Width in px of FCKeditor Area' => 'Width in px of FCKeditor Area',
  'Height in px of FCKeditor Area' => 'Height in px of FCKeditor Area',

  ## new in 2.11.

  'URL where known users can unsubscribe' => 'URL where known users can unsubscribe',
  'URL where unknown users can unsubscribe (blacklist)' => 'URL where unknown users can unsubscribe (blacklist)',
  'Width for Wordwrap of Text messages' => 'Width for Wordwrap of Text messages',
  'categories for lists. Separate with commas.' => 'categories for lists. Separate with commas.',
);
?>
