<?php

$lan = array(
  'Your database is out of date, please make sure to upgrade' => 'Your database is out of date, please make sure to upgrade',
  'Your version' => 'Your version',
  'Latest version' => 'Latest version',
  'phplist version' => '<a href="http://www.phplist.com">phplist</a> version',
  'Database has not been initialised' => 'Database has not been initialised',
  'go to' => 'go to',
  'Initialise Database' => 'Initialise Database',
  'to continue' => 'to continue',
  'A new version of PHPlist is available!' => 'A new version of PHPlist is available!',
  'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => 'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible',
  'View what has changed' => 'View what has changed',
  'Download' => 'Download',
  'System Functions' => 'System Functions',
  'Setup ' => 'Setup ',
  'Check Database structure' => 'Check Database structure',
  'View the eventlog' => 'View the eventlog',
  'Configuration functions' => 'Configuration functions',
  'Configure Attributes' => 'Configure Attributes',
  'Control values for' => 'Control values for',
  'Control values for' => 'Control values for',
  'Control values for' => 'Control values for',
  'Configure Subscribe pages' => 'Configure Subscribe pages',
  'List and user functions' => 'List and user functions',
  'List the current lists' => 'List the current lists',
  'List all Users' => 'List all Users',
  'Reconcile the user database' => 'Reconcile the user database',
  'Import Users' => 'Import Users',
  'Export Users' => 'Export Users',
  'Administrator functions' => 'Administrator functions',
  'Add, edit and remove Administrators' => 'Add, edit and remove Administrators',
  'Configure attributes for administrators' => 'Configure attributes for administrators',
  'Message functions' => 'Message functions',
  'Configure Templates' => 'Configure Templates',
  'List all Messages' => 'List all Messages',
  'Process the Message queue' => 'Process the Message queue',
  'RSS Functions' => 'RSS Functions',
  'Get RSS feeds' => 'Get RSS feeds',
  'View RSS items' => 'View RSS items',
  'Plugins' => 'Plugins',
  'Upgrade' => 'Upgrade',
'Change your details (e.g. password)' => 'Change your details (e.g. password)',
'You have set TEST in config.php to 1, so it will only show what would be sent' => 'You have set TEST in config.php to 1, so it will only show what would be sent',

  # added at a later stage
  'setup' => 'setup',
  'upgrade' => 'upgrade',
  'dbcheck' => 'dbcheck',
  'eventlog' => 'eventlog',
  'attributes' => 'attributes',
  'spage' => 'spage',
  'list' => 'list',
  'reconcileusers' => 'reconcileusers',
  'import' => 'import',
  'export' => 'export',
  'admins' => 'admins',
  'adminattributes' => 'adminattributes',
  'send' => 'send',
  'templates' => 'templates',
  'processqueue' => 'processqueue',
  'processbounces' => 'processbounces',
  'getrss' => 'getrss',
  'viewrss' => 'viewrss',
  'admin' => 'admin',
  'preparesend' => 'preparesend',
  'sendprepared' => 'sendprepared',


);

?>