<?php
$lan = array(
  "Import emails from IMAP folders" => "Import emails from IMAP folders",
  "No lists available" => "No lists available",
  "Add a list" => "Add a list",
  "personal" => "personal",
  "email" => "email",
  "folder" => "folder",
  "date" => "date",
  "can't connect" => "can't connect",
  "Processing" => "Processing",
  "messages" => "messages",
  "done" => "done",
  "imap_getmailboxes failed" => "imap_getmailboxes failed",
  "Please enter details of the IMAP account" => "Please enter details of the IMAP account",
  "Select the headers fields to search" => "Select the headers fields to search",
  "Select the lists to add the emails to" => "Select the lists to add the emails to",
  "Adding users to list" => "Adding users to list",
  "Mark new users as HTML" => "Mark new users as HTML",
/* read lines below as sentences: if you check 'overwrite' information about a user... etc. */
  "If you check" => "If you check",
  "Overwrite Existing" => "Overwrite Existing",
  "information about a user in the database will be replaced by the imported information. Users are matched by email." => "information about a user in the database will be replaced by the imported information. Users are matched by email.",
  "Only use complete addresses" => "Only use complete addresses",
  "addresses that do not have a real name will be ignored. Otherwise all emails will be imported." => "addresses that do not have a real name will be ignored. Otherwise all emails will be imported.",
  "If you choose" => "If you choose",
  "send notification email" => "send notification email",
  "the users you are adding will be sent the request for confirmation of subscription to which they will have to reply. This is recommended, because it will identify invalid emails." => "the users you are adding will be sent the request for confirmation of subscription to which they will have to reply. This is recommended, because it will identify invalid emails.",
  "Send&nbsp;Notification&nbsp;email&nbsp;" => "Send&nbsp;Notification&nbsp;email&nbsp;",
  "Make confirmed immediately" => "Make confirmed immediately",
  "import3info" => "There are two ways to add the names of the users,
 either one attribute for the entire name or two attributes, one for first name and one for last name.
If you use 'two attributes', the name will be split after the first space.",
  "Use one attribute for name" => "Use one attribute for name",
  'Use two attributes for the name' => 'Use two attributes for the name',
  "Attribute one" => "Attribute one",
  "Create Attribute" => "Create Attribute",
  "Attribute two" => "Attribute two",
  "Cannot continue" => "Cannot continue",
  "ok" => "ok",
  "failed" => "failed",
  "Processed" => "Processed",
  "folders and" => "folders and",
  "unique emails found" => "unique emails found",
  "list" => "list",
  "lists" => "lists",
  "new email was" => "new email was",
  "new emails were" => "new emails were",
  "email was" => "email was",
  "emails were" => "emails were",
  "All the emails already exist in the database and are members of the" => "All the emails already exist in the database and are members of the",
  "succesfully imported to the database and added to" => "succesfully imported to the database and added to",
  "subscribed to the" => "subscribed to the",
  "emails already existed in the database" => "emails already existed in the database",
  "Invalid Emails found." => "Invalid Emails found.",
  "These records were added, but the email has been made up. You can find them by doing a search on" => "These records were added, but the email has been made up. You can find them by doing a search on",
  "These records were deleted. Check your source and reimport the data. Duplicates will be identified." => "These records were deleted. Check your source and reimport the data. Duplicates will be identified.",
  "No emails found" => "No emails found",
  "Import some more emails" => "Import some more emails",
  'Server' => 'Server',
  'User' => 'User',
  'Password' => 'Password',
  'Continue' => 'Continue',
  'Process Selected Folders' => 'Process Selected Folders',
);
?>