<?php
$lan = array(
  'You do not have enough priviliges to view this page' => 'You do not have enough priviliges to view this page',
  'Add a user' => 'Add a user',
  'add user' => 'Add User',
  'Members of' => 'Members of',
  'Tag all users in this page' => 'Tag all users in this page',
  'back to this list' => 'back to this list',
  'Download users on this list as a CSV file' => 'Download users on this list as a CSV file',
  'Please enter a listid' => 'Please enter a listid',
  'Processing' => 'Processing',
  'users were moved to' => 'users were moved to',
  'users were copied to' => 'users were copied to',
  'users were deleted from this list' => 'users were deleted from this list',
  'Users found, click add to add this user' => 'Users found, click add to add this user',
  'Add' => 'Add',
  'No user found with that email' => 'No user found with that email',
  'Inserting user' => 'Inserting user',
  'User added' => 'User added',
  'Deleting' => 'Deleting',
  'Done' => 'Done',
  'Users on this list' => 'Users on this list',
  'Listing user' => 'Listing user',
  'to' => 'to',//in sentence 'listing user 1  to  50'
  'Listing user 1 to 50' => 'Listing user 1 to 50',
  'Members' => 'Members',
  'confirmed' => 'confirmed',
  'tag' => 'tag',
  'del' => 'del',
  'Delete'=>'Delete',
  '# msgs' => '# msgs',
  '# rss' => '# rss',
  'rss freq' => 'rss freq',
  'last sent' => 'last sent',
  'What to do with "Tagged" users' => 'What to do with "Tagged" users',
  'This will only process the users in this page that have the "Tag" checkbox checked' => 'This will only process the users in this page that have the "Tag" checkbox checked',
  'delete' => 'Delete',
  'move' => 'Move',
  'copy' => 'Copy',
  'nothing' => 'Nothing',
  'to' => 'to', # as in destination
  'from this list' => 'from this list',
  'What to do with all users' => 'What to do with all users',
  'This will process all users on this list' => 'This will process all users on this list',
  'do it' => 'do it',
  
  
);
?>