<?php
$lan = array(
 'Please select a message to display' => 'Please select a message to display',
 'Attachments for this message' => 'Attachments for this message',
 'No attachments' => 'No attachments',
 'Filename' => 'Filename',
 'Size' => 'Size',
 'Mime Type' => 'Mime Type',
 'Description' => 'Description',
 'Lists this message has been sent to' => 'Lists this message has been sent to',
 'None yet' => 'None yet',
 'Send this (same) message to (a) new list(s)' => 'Send this (same) message to (a) new list(s)',
 'List is Active' => 'List is Active',
 'List is not Active' => 'List is not Active',
 '<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the "Requeue" function.' => '<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the "Requeue" function.',
 'Resend' => 'Resend',
 'id' => 'id',
 'subject' => 'subject',
 'fromfield' => 'from field',
 'tofield' => 'to field',
 'replyto' => 'reply to',
 'message' => 'message',
 'textmessage' => 'textmessage',
 'footer' => 'footer',
 'entered' => 'entered',
 'modified' => 'modified',
 'embargo' => 'embargo',
 'repeatinterval' => 'repearinterval',
 'repeatuntil' => 'repeatuntil',
 'status' => 'status',
 'userselection' => 'userselection',
 'sent' => 'sent',
 'htmlformatted' => 'htmlformatted',
 'sendformat' => 'sendformat',
 'template' => 'template',
 'processed' => 'processed',
 'astext' => 'as text',
 'ashtml' => 'as html',
// 'astextandhtml' => 'as text and html', //obsolete by bug 0009687
 'aspdf' => 'as pdf',
 'astextandpdf' => 'as text and pdf',
 'viewed' => 'viewed',
 'bouncecount' => 'bounce count',
 'sendstart' => 'send start',
 'rsstemplate' => 'RSS template',
 'owner' => 'owner',

 # new in 2.10.1
 'edit this message' => 'Edit this message',
);
?>
