<?php
$lan = array(
  "This page can only be called from the commandline" => "This page can only be called from the commandline",
  "Bounce processing error" => "Bounce processing error",
  "Bounce Processing info" => "Bounce Processing info",
  "error" => "error",
  "info" => "info",
  "system message bounced, user marked unconfirmed" => "system message bounced, user marked unconfirmed",
  "Bounced system message" => "Bounced system message",
  "User marked unconfirmed" => "User marked unconfirmed",
  "View Bounce" => "View Bounce",
  "Cannot create POP3 connection to" => "Cannot create POP3 connection to",
  "Cannot open mailbox file" => "Cannot open mailbox file",
  "bounces to fetch from the mailbox" => "bounces to fetch from the mailbox",
  "Please do not interrupt this process" => "Please do not interrupt this process",
  "bounces to process" => "bounces to process",
  "Processing first" => "Processing first",
  "bounces" => "bounces",
  "Running in test mode, not deleting messages from mailbox" => "Running in test mode, not deleting messages from mailbox",
  "Processed messages will be deleted from mailbox" => "Processed messages will be deleted from mailbox",
  "Deleting message" => "Deleting message",
  "Closing mailbox, and purging messages" => "Closing mailbox, and purging messages",
  "IMAP is not included in your PHP installation, cannot continue" => "IMAP is not included in your PHP installation, cannot continue",
  "Check out" => "Check out",// or 'go look', 'consult', etc.
  "Bounce mechanism not properly configured" => "Bounce mechanism not properly configured",
  "bounce_protocol not supported" => "bounce_protocol not supported",
  "Identifying consecutive bounces" => "Identifying consecutive bounces",
  "Nothing to do" => "Nothing to do",
  "Process Killed by other process" => "Process Killed by other process",
// 3 lines below = one sentence
  "User" => "User",
  "has consecutive bounces" => "has consecutive bounces",
  "over threshold, user marked unconfirmed" => "over threshold, user marked unconfirmed",
  "Auto Unsubscribed" => "Auto Unsubscribed",
// 2 lines below = one sentence
  "User auto unsubscribed for" => "User auto unsubscribed for",
  "consecutive bounces" => "consecutive bounces",
// 3 lines below = one sentence
  "Identifying consecutive bounces" => "Identifying consecutive bounces",
  "of" => "of",
  "users processed" => "users processed",
  'processing first' => 'processing first',
  'Report:' => 'Report:',
  'Below are users who have been marked unconfirmed. The number in [] is their userid, the number in () is the number of consecutive bounces' => 'Below are users who have been marked unconfirmed. The number in [] is their userid, the number in () is the number of consecutive bounces',
  
  ## new in 2.9.5
  'Processing bounces based on active bounce rules' => 'Processing bounces based on active bounce rules',
  'Auto Blacklisted' => 'Auto Blacklisted',
  'User auto blacklisted for' => 'User auto blacklisted for',
  'bounce rule' => 'bounce rule',
  'system message bounced, but unknown user' => 'system message bounced, but unknown user',
  'bounces processed by advanced processing' => 'bounces processed by advanced processing',
  'bounces were not matched by advanced processing rules' => 'bounces were not matched by advanced processing rules',
  'Report of advanced bounce processing:' => 'Report of advanced bounce processing:',
);
?>