<?php
$lan = array (
  'warnemailattribute' => 'Email是系统栏位',
  'converting' => '转换中',
  'from' => '从',
  'to' => '到',
  'deleting' => '删除中',
  'cannotdelete' => '无法删除栏位，目前被下面表单使用：',
  'warninglongtime' => '注意，修改任何类型的栏位都可能需要等候一段时间',
  'sorrymergingcbgroupnotimplemented' => '抱歉，合併选取方块群组还没完成',
  'cannotmergeone' => '无法只合併一个栏位',
  'merging' => '合併中',
  'into' => '变成',
  'notsametype' => '只能够合併同样类型的栏位',
  'existing' => '已存在的栏位',
  'noattributesdefined' => '还没定义任何栏位',
  'loadfrom' => '读取资料自',
  'defaults' => '预设值',
  'attribute' => '栏位',
  'usedin' => '使用于',
  'forms' => '表单',
  'tag' => '标籤',
  'name' => '名称',
  'type' => '类型',
  'defaultvalue' => '预设值',
  'orderoflisting' => '顺序',
  'isrequired' => '必填？',
  'textline' => '文字方块',
  'checkbox' => '核选方块',
  'checkboxgroup' => '核选方块群组',
  'radio' => '单选项目',
  'select' => '下拉选单',
  'hidden' => '隐藏项目',
  'textarea' => '多行文字',
  'date' => '日期',
  'savechanges' => '储存',
  'withtagged' => '使用标示的栏位',
  'delete' => '删除',
  'merge' => '合併',
  'addnew' => '新增栏位',

);
?>