<?php
$lan = array (
  'NoRecord' => '没有记录',
  'BackToBList' => '回到退信清单',
  'NotFound' => '找不到<br/>',
  'AddedToB' => '新增 %s 到 %s 的退信指数<br/>',
  'NotAddedToB' => '无法新增 %s 到 %s 的退信指数<br/>',
  'MadeUnconfirmed' => '让使用者 %s 状态变成未确认<br/>',
  'MadeUserRText' => '让使用者 %s 订阅纯文字版本<br/>',
  'DelUser' => '删除使用者 %s<br/>',
  'DeletingB' => '删除退信中 %s ..',
  'DoneAndLoading' => '..完成，读取下一封退信..',
  'NoSRecord' => '没有这笔记录',
  'PossibleActions' => '动作：',
  'ForUser' => '给使用者信箱',
  'IncreaseB' => '增加退信指数于',
  'IncreaseBNote' => '(使用负数来减少)',
  'MarkAsUnconfirmed' => '让使用者状态变成未确认',
  'MarkAsUnconfirmedNote' => '(接着您就可以重新发送确认信函)',
  'SetReceiveText' => '设定使用者订阅纯文字版本',
  'DelUser1' => '删除使用者',
  'DelAndGo' => '删除这封退信并且读取下一封',
  'DoAbove' => '执行',
  'BounceDetails' => '退信细节：',
  'ID' => 'ID',
  'Date' => '日期',
  'Status' => '状态',
  'Comment' => '意见',
  'Header' => '页首',
  'Body' => '内容',
  'Regular Expression' => '样式比对',
  'Action' => '操作',
  'Memo for this rule' => '这个规则的备注',
  'Add new Rule' => '新增规则',
  'Create New Rule based on this bounce' => '以这封退信建立新规则',

);
?>