<?php
$lan = array (
  'add_list' => '新增電子報',
  'cant_connect' => '無法連結遠端資料庫',
  'no_users_to_copy' => '無法複製使用者，確定前置字元正確？',
  'remote_server' => '請輸入遠端伺服器資訊',
  'server' => '伺服器：',
  'user' => '帳號：',
  'passwd' => '密碼：',
  'database' => '資料庫名稱：',
  'table_prefix' => '資料表前置字元：',
  'usertable_prefix' => '使用者資料表前置字元：',
  'select_lists' => '選擇新增 email 訂閱的電子報',
  'copy_lists' => '從遠端伺服器複製電子報 (透過名稱比對)',
  'users_as_html' => '新使用者訂閱 HTML格式：',
  'info_overwrite_existing' => '如果您勾選 "覆蓋現有的"，已經存在的資料會被新的資料取代。',
  'overwrite_existing' => '覆蓋現有的：',
  'connecting_remote' => '與遠端資料庫連線中',
  'getting_data' => '取得資料自',
  'remote_version' => '遠端版本',
  'remote_has' => '遠端版本有',
  'users' => '使用者',
  'lists' => '電子報',
  'copying_lists' => '複製電子報中',
  'list' => '電子報',
  'exists_locally' => '本地端存在的',
  'created_locally' => '本地端建立的',
  'remote_list' => '遠端電子報',
  'not_created' => '沒有建立',
  'copying_attribs' => '複製欄位',
  'attrib' => '欄位',
  'copying_users' => '複製使用者中',
  'overwrite_local' => '覆蓋本地端資料',
  'keep_local' => '保留本地端資料',
  'new_user' => '是新使用者',
  'no_mapped_attrib' => '錯誤，沒有對應的欄位',
  'no_local_list' => '錯誤，本地端電子報未定義',
  'No lists available' => '沒有電子報可以訂閱',
  'Done' => '完成',
  'new users' => '新使用者',
  'and' => '與',
  'existing users' => '已經存在的使用者',
  'continue' => '繼續',

);
?>