<?php
$lan = array (
  'File is either to large or does not exist.' => '档桉太大或不存在',
  'No file was specified.' => '没有指定档桉',
  'Some characters that are not valid have been found. These might be delimiters. Please check the file and select the right delimiter. Character found:' => '发现部分字元错误，可能资料中包含了分隔字元，请检查档桉后选择正确的分隔字元。找到的字元：',
  'Name cannot be empty' => '名称不能空白',
  'Name is not unique enough' => '名称必须唯一',
  'Cannot find the email in the header' => '从页首找不到 email',
  'Cannot find the password in the header' => '从页首找不到密码',
  'Cannot find the loginname in the header' => '从页首找不到帐号',
  'Record has no email' => '没有email',
  'Invalid Email' => '错误的email',
  'Record has more values than header indicated, this may cause trouble' => '资料有超过页首定义的数值，这也许会造成错误',
  'password' => '密码',
  'loginname' => '帐号',
  'Empty loginname, using email:' => '空白的帐号，使用 email：',
  'Value' => '数值',
  'added to attribute' => '新增到栏位',
  'new email was' => '新 email 是',
  'new emails were' => '新 email 是',
  'email was' => 'email 是',
  'emails were' => 'email 是',
  'All the emails already exist in the database' => '所有的 emails 都已经在资料库中',
  'succesfully imported to the database and added to the system.' => '成功汇入到资料库并且新增到系统中',
  'Import some more emails' => '汇入更多 email',
  'No default permissions have been defined, please create default permissions first, by creating one dummy admin and assigning the default permissions to this admin' => '没有定义预设权限，请先建立一个预设权限，并且指定预设的权限给这个管理者',
  'importadmininfo' => '您上传的档桉必须包含您希望新增的管理者资讯，标题列需要包含栏位如下：<b>email</b>、<b>帐号</b>、<b>密码</b>，其他的栏位会被新增为管理者栏位。
 <b>注意</b>：档桉必须是纯文字格式，而非 Word 之类的文件
  ',
  'File containing emails' => '档桉包含 email',
  'Field Delimiter' => '栏位分隔字元',
  'Record Delimiter' => '资料分隔字元',
  'importadmintestinfo' => '如果您选择 "测试输出"，您将会看到系统解析出来的 email 清单，而不会立刻新增到资料库中。这个功能可以协助您确认档桉格式，所以它只会撷取前五十笔资料。',
  'Test output' => '测试输出',
  'Check this box to create a list for each administrator, named after their loginname' => '勾选这个项目来为每个管理者建立电子报，会以他们的帐号作为名称',
  'Do Import' => '汇入',
  'default is TAB' => '遇设是 TAB',
  'default is line break' => '预设是段落',
  'testoutputinfo' => '测试输出：<br/>一行应该只有一个 email。<br/>如果输出正常，可以 <a href="javascript:history.go(-1)">回上页</a> 来正式送出<br/><br/>',
  'List for' => '电子报',
  'login' => '帐号',

);
?>