<?php
$lan = array (
  'You do not have enough priviliges to view this page' => '您没有存取这个页面的权限',
  'Add a user' => '新增使用者',
  'add user' => '新增使用者',
  'Members of' => '订阅者于',
  'Tag all users in this page' => '选取这个页面的所有使用者',
  'back to this list' => '回到这个电子报',
  'Download users on this list as a CSV file' => '下载这个电子报的使用者资料(CSV格式)',
  'Please enter a listid' => '请输入电子报编号',
  'Processing' => '处理中',
  'users were moved to' => '个使用者移到',
  'users were copied to' => '个使用者複製到',
  'users were deleted from this list' => '个使用者从这个电子报移除',
  'Users found, click add to add this user' => '个使用者，点选新增来继续',
  'Add' => '新增',
  'No user found with that email' => '没有使用这个 email 的会员',
  'Inserting user' => '新增使用者中',
  'User added' => '使用者新增了',
  'Deleting' => '删除中',
  'Done' => '完成',
  'Users on this list' => '这个电子报的订阅者',
  'Listing user' => '列出订阅者',
  'to' => '到',
  'Listing user 1 to 50' => '列出前五十个订阅者',
  'Members' => '会员',
  'confirmed' => '已确认',
  'tag' => '选取',
  'del' => '删除',
  'Delete' => '删除',
  '# msgs' => '# msgs',
  '# rss' => '# rss',
  'rss freq' => 'rss 频率',
  'last sent' => '最后寄出',
  'What to do with "Tagged" users' => '标示的使用者要执行什麽动作',
  'This will only process the users in this page that have the "Tag" checkbox checked' => '这将只会处理页面中有沟选的使用者',
  'delete' => '删除',
  'move' => '移动',
  'copy' => '複製',
  'nothing' => '无',
  'from this list' => '自这个电子报',
  'What to do with all users' => '要对所有使用者进行什麽动作',
  'This will process all users on this list' => '这会影响本电子报的所有订阅者',
  'do it' => '执行',

);
?>