<?php
$lan = array (
  'Resending confirmation request to' => '重新发送确认讯息到',
  'user found' => '个使用者',
  'no user found' => '没有找到使用者',
  'unable to find original email' => '无法找到原来的信箱',
  'Marking all users confirmed' => '将所有使用者标示为已确认',
  'users apply' => '个使用者符合',
  'Creating UniqID for all users who do not have one' => '为所有还没处理的使用者建立唯一的代码',
  'Marking all users to receive HTML' => '将所有使用者标示为接收 HTML 信件',
  'Marking all users to receive text' => '将所有使用者标示为接收纯文字信件',
  'Deleting users who are not on any list' => '删除没有订阅任何电子报的使用者',
  'Moving users who are not on any list to' => '移动没有订阅任何电子报的使用者到',
  'Deleting users with more than' => '删除使用者，如果超过',
  'bounces' => '封退信',
  'Resending request for confirmation to users who signed up after' => '重新发送确认信函给使用者，注册日期晚于',
  'and before' => '且早于',
  'Deleting unconfirmed users who signed up after' => '删除未确认的使用者，注册日期晚于',
  'Trying to merge duplicates' => '尝试合併重複资料',
  'Don\'t know how to' => '不知道如何',
  'Listing users with an invalid email' => '列出信箱错误的使用者',
  'Users deleted' => '个使用者删除了',
  'Users apply' => '个使用者调整了',
  'Trying to fix users with an invalid email' => '尝试修正信箱错误的使用者资料',
  'User' => '使用者',
  'Users fixed' => '个使用者资料修正了',
  'Users could not be fixed' => '个使用者资料无法修正',
  'Deleting users with an invalid email' => '删除信箱错误的使用者',
  'Marking users with an invalid email as unconfirmed' => '将信箱错误的使用者标示为未确认',
  'Users updated' => '个使用者更新了',
  'Cleaning some user tables of invalid entries' => '清楚使用者资料表中的错误项目',
  'entries apply' => '笔资料处理了',
  'Delete will delete user and all listmemberships' => '将会删除使用者与所有的会员关係',
  'Done' => '完成',
  'Users' => '个使用者',
  'found' => '发现于',
  'in the database' => '资料库中',
  'Delete all users who are not subscribed to any list' => '删除未订阅任何电子报的使用者',
  'To try to (automatically)' => '尝试（自动）',
  'Find users who have an invalid email' => '找寻信箱错误的使用者',
  'Make sure that all users have a UniqID' => '确认所有使用者都有唯一的代码',
  'Mark all users with an invalid email as unconfirmed' => '将信箱格式有误的使用者标示为未确认',
  'Delete users who have an invalid email' => '删除信箱格式错误的使用者',
  'Mark all users to receive HTML' => '将所有使用者标示为接收 HTML 信件',
  'Mark all users to receive text' => '将所有使用者标示为接收 纯文字 信件',
  'Mark all users confirmed' => '标示所有使用者为已确认',
  'Fix emails for users who have an invalid email' => '修正信箱错误的使用者资料',
  'Remove Stale entries from the database' => '从资料库中移除较旧的资料',
  'Merge Duplicate Users' => '合併重複的使用者',
  'To move all users who are not subscribed to any list to' => '移动未订阅任何电子报的使用者到',
  'Click here' => '点选这裡',
  'To delete all users with more than' => '删除所有使用者，如果超过',
  'Note: this will use the total count of bounces on a user, not consecutive bounces' => '注意：这将会使用个别使用者的退信总数，不包括连续退信',
  'To resend the request for confirmation to users who signed up and have not confirmed their subscription' => '重新发送确认信函给那些未确认的使用者',
  'Date they signed up after' => '订阅日期晚于',
  'Date they signed up before' => '订阅日期早于',
  'Text to prepend to email' => '附加到信件前的讯息',
  'prependemailtext' => '抱歉，不是刻意要打扰您；我们目前正在清理资料库，发现您曾经订阅了我们的电子报，但是还没完成确认。

我们希望透过这封信让您能够重新确认，请参考下面步骤。',
  'To delete users who signed up and have not confirmed their subscription' => '删除订阅但未确认的使用者',
  'Delete Tagged Users' => '删除标示的使用者',

);
?>