<?php
$lan = array (
  'General Information' => '一般资讯',
  'Title' => '标题',
  'Title of this set of lists' => '这个系列电子报的标题',
  'Please indicate how often you want to receive messages' => '请指定您希望收到电子报的频率',
  'Don\'t offer choice, default to <b>text</b>' => '不提供选择，预设为 <b>纯文字</b>',
  'Don\'t offer choice, default to <b>HTML</b>' => '不提供选择，预设为 <b>HTML</b>',
  'Don\'t display email confirmation' => '不显示确认信箱栏位',
  'Intro' => '介绍',
  'Header' => '页首',
  'Footer' => '页尾',
  'Thank you page' => '感谢订阅页面',
  'Text for Button' => '按钮文字',
  'HTML Email choice' => 'HTML 邮件选择',
  'Offer checkbox for text' => '提供纯文字选项',
  'Offer checkbox for HTML' => '提供 HTML 选项',
  'Radio buttons, default to text' => '单选表单，预设为纯文字',
  'Radio buttons, default to HTML' => '单选表单，预设为 HTML',
  'Display Email confirmation' => '显示信箱确认',
  'Display email confirmation' => '显示信箱确认',
  'Message they receive when they subscribe' => '订阅时会收到的信件',
  'Message they receive when they confirm their subscription' => '完成确认后会收到的信件',
  'Subject' => '主旨',
  'Message' => '内容',
  'Select the attributes to use' => '选择要使用的属性',
  'No lists available, please create one first' => '没有任何电子报，请先建立',
  'Attribute' => '属性',
  'Check this box to use this attribute in the page' => '勾选要在订阅页面使用的属性',
  'Type' => '类型',
  'Default Value' => '预设值',
  'Order of Listing' => '顺序',
  'Is this attribute required?' => '必填项目？',
  'RSS settings' => 'RSS 设定',
  'Intro Text' => '介绍',
  'Offer option to receive' => '提供接收项目',
  'Daily' => '每日',
  'default' => '预设',
  'Weekly' => '每週',
  'Monthly' => '每月',
  'Select the lists to offer' => '选择要提供的电子报',
  'Owner' => '拥有者',
  'Save Changes' => '储存',
  'Save and Activate' => '储存＆启用',
  'Save and Deactivate' => '储存＆停用',

);
?>