<?php
$lan = array (
  'Delete will delete user and all listmemberships' => '这将会删除使用者与相关的会员关係',
  '%s users apply' => '%s 个符合的使用者',
  'Users marked <span class="highlight">red</span> are unconfirmed' => '标示为 <span class="highlight">红色</span> 字的使用者表示未确认',
  'Show only unconfirmed users' => '只显示未确认的使用者',
  'Show only blacklisted users' => '只显示黑名单的使用者',
  'email' => '信箱',
  'bouncecount' => '退信数量',
  'entered' => '输入日期',
  'modified' => '修改日期',
  'foreignkey' => '外部键值',
  'Sort by' => '排序',
  'desc' => '降幂',
  'asc' => '升幂',
  'Go' => '到',
  'Find a user' => '找寻使用者',
  'Email' => '信箱',
  'Foreign Key' => '外部键值',
  'reset' => '重设',
  'Download all users as CSV file' => '以 CSV 格式下载所有使用者资料',
  'Add a User' => '新增使用者',
  'confirmed' => '已确认',
  'bl l' => '黑名单',
  'del' => '删除',
  'key' => '键值',
  'msgs' => '信件',
  'rss' => 'rss',
  'rss freq' => 'rss 频率',
  'bncs' => '退信',
  'No users apply' => '没有符合的使用者',
  'Your privileges for this page are insufficient' => '您没有足够的权限',
  'Delete will delete user from the list' => '这将会删除所有电子报的使用者',
  'deleting' => '删除中',
  'Done' => '完成',
  'User added' => '使用者新增了',
  'Add this user' => '新增这个使用者',
  'Click on a link to use the corresponding public subscribe page to add this user:' => '点选一个连结来透过一致的公开订阅页面新增使用者：',
  'Click this link to use the public subscribe page to add this user:' => '点选这个连结来使用公开订阅页面新增使用者：',
  'Listing user %d to %d' => '列出使用者 %d 到 %d',
  'last sent' => '最后发信日期',

);
?>