<?php
$lan = array (
  'Delete will delete user and all listmemberships' => '这将会删除使用者与相关的会员关係',
  'No Lists' => '没有电子报',
  'update page' => '更新页面',
  'unsubscribe page' => '取消订阅页面',
  'History' => '存取记录',
  'User Details' => '使用者细节',
  'You only have privileges to view this page, not change any of the information' => '您只能够检视这个页面，无法修改任何资料',
  'Delete will delete user from the list' => '这将会从电子报中删除使用者',
  'User added to group' => '使用者新增到群组',
  'User added to list %s' => '使用者新增到电子报 %s',
  'Changes saved' => '异动储存了',
  'Deleting' => '删除中',
  'Done' => '完成',
  'No such User' => '没有这个使用者',
  'Add a new User' => '新增使用者',
  'encrypted' => '加密',
  'Save Changes' => '保存',
  'User is blacklisted. No emails will be sent to this user' => '使用者在黑名单中，无法发送信件给他',
  'Mailinglist Membership' => '电子报会员',
  'Group Membership' => '会员群组',
  'Please select the groups this user is a member of' => '请选择这个使用者要归类的群组',
  'ID' => '编号',
  'Email' => '信箱',
  'Is this user confirmed' => '已确认？',
  'Is this user blacklisted' => '黑名单？',
  'Number of bounces on this user' => '这个使用者的退信数量',
  'Entered' => '加入',
  'Last Modified' => '最后更新',
  'Unique ID for User' => '这个使用者的唯一代码',
  'Send this user HTML emails' => '发送 HTML 信件给这个使用者',
  'Which page was used to subscribe' => '要使用那个页面来订阅',
  'RSS Frequency' => 'RSS 频率',
  'Last time password was changed' => '最后更新密码时间',
  'Is this account disabled?' => '停用这个帐号？',
  'Additional data' => '其他资讯',
  'Foreign Key' => '外部键值',
  'Error adding user, please check that the user exists' => '新增使用者错误，请检查这个使用者是否已经存在',

);
?>