<?php 
$lan = array(
  "NoRecord" => "Kein solcher Datensatz",
  "BackToBList" => "Zur&uuml;ck zur Liste der unzustellbaren Mails",
  "NotFound" => "Nicht gefunden<br/>",
  "AddedToB" => "Addiere %s zum Retouren-Z&auml;hler des Empf&auml;ngers %s<br/>",
  "NotAddedToB" => "Das Addieren von %s zum Retouren-Z&auml;hler des Empf&auml;ngers %s ist fehlgeschlagen.<br/>",
  "MadeUnconfirmed" => "Der Empf&auml;nger %s wurde als unbest&auml;tigt markiert.<br/>",
  "MadeUserRText" => "Der Empf&auml;nger %s wurde auf den Empfang von Text-Mails gesetzt.<br/>",
  "DelUser" => "Empf&auml;nger %s l&ouml;schen<br/>",
  "DeletingB" => "L&ouml;sche unzustellbares Mail %s ..\n",
  "DoneAndLoading" => "..Ausgef&uuml;hrt. Lade n&auml;chstes retourniertes Mail..",
  "NoSRecord" => "Kein solcher Datensatz",
  "PossibleActions" => "M&ouml;gliche Aktionen:",
  "ForUser" => "F&uuml;r Empf&auml;nger mit E-Mail",
  "IncreaseB" => "Erh&ouml;he den Retouren-Z&auml;hler um",
  "IncreaseBNote" => "(negative Werte <strong>verringern</strong> der Z&auml;hlerwert)",
  "MarkAsUnconfirmed" => "Empf&auml;nger als unbest&auml;tigt markieren",
  "MarkAsUnconfirmedNote" => "(damit die Best&auml;tigungsanforderung erneut verschickt werden kann)",
  "SetReceiveText" => "Der Empf&auml;nger wurde von HTML-Mails auf Text-Mails umgeschaltet.",
  "DelUser1" => "Empf&auml;nger l&ouml;schen",
  "DelAndGo" => "Unzustellbares Mail l&ouml;schen und n&auml;chstes anzeigen",
  "DoAbove" => "Obiges ausf&auml;hren",
  "BounceDetails" => "Details zu unzustellbarem Mail:",
  "ID" => "ID",
  "Date" => "Datum",
  "Status" => "Status",
  "Comment" => "Kommentar",
  "Header" => "Header",
  "Body" => "Body",
  
  # new in 2.9.5
  'Regular Expression' => 'Regular Expression',
  'Action' => 'Aktion',
  'Memo for this rule' => 'Notiz f&uuml;r diese Regel',
  'Add new Rule' => 'Neue Regel anlegen',
  'Create New Rule based on this bounce' => 'Neue Regel basierend auf diesem unzustellbaren Mail anlegen',
);
?>