<?php
$lan = array(

  'temp_dir_not_writeable' => 'Das tempor&auml;re Upload-Verzeichnis ist schreibgesch&uuml;tzt. Der Import wird fehlschlagen.',
  'select_list' => 'Bitte w&auml;hlen Sie mindestens 1 Liste aus.',
  'too_large_inexistant' => 'Die Datei ist entweder zu gross oder sie existiert nicht.',
  'none_specified' => 'Es wurde keine Datei ausgew&auml;hlt. M&ouml;glicherweise ist die Datei zu gross?',
  'too_big' => 'Die Datei ist zu gross. Bitte teilen Sie sie in mehrere kleinere Dateien auf.',
  'wrong_characters' => 'Es wurden falsche Zeichen benutzt: ',
  'signup_or_notify' => 'Bitte w&auml;hlen Sie, ob die Anmeldung sofort erfolgen soll oder eine Best&auml;tigungsanfrage verschickt werden soll.',
  'unreadable' => 'Die Datei ist nicht lesbar.',
  'empty_file' => 'Beim Upload der Datei ist ein Fehler aufgetreten; es wurde eine leere Datei empfangen. M&ouml;glicherweise ist die Datei zu gross, oder Sie haben keine Zugriffsberechtigung daf&uuml;r.',
  'invalid_delimiter' => 'Es wurden ung&uuml;ltige Zeichen gefunden. M&ouml;glicherweise sind es Feld- oder Datensatz-Trennzeichen. Bitte &uuml;berpr&uuml;fen Sie die Datei und w&auml;hlen Sie das korrekte Zeichen.',
  'import_user' => 'Import eines bestehenden Benutzers',
  'import_new_user' => 'Import eines neuen Benutzers',
  'no_data_changed' => 'Es wurden keine Benutzerdaten ge&auml;ndert.',
  'lists_subscriptions' => 'Zeige Abonnemente:',
  'was_subscribed' => 'War abonniert auf:',
  'is_subscribed' => 'Ist nun abonniert auf:',
  'not_subscribed' => 'Auf keine Liste abonniert',
  'import_by' => 'Import von ',
  'list' => 'Liste',
  'lists' => 'Listen',
  'new_email_was' => 'Die neue E-Mail-Adresse war',
  'new_emails_were' => 'Die neuen E-Mail-Adressen waren',
  'email_was' => 'Die E-Mail-Adresse war',
  'emails_were' => 'Die E-Mail-Adressen waren',
  'import_more_emails' => 'Importiere weitere E-Mail-Adressen',
  'add_list' => 'Liste hinzuf&uuml;gen',
  'test_output' => 'Test-Durchlauf',
  'one_email_per_line' => 'Es sollte nur 1 E-Mail-Adresse pro Zeile existieren.',
  'output_ok' => 'Wenn die Ausgabe einwandfrei aussieht, gehe',
  'back' => 'zur&uuml;ck',
  'resubmit' => ' to resubmit for real',
  'some_emails_exist' => 'E-Mail-Adressen existierten in der Datenbank',
  'all_emails_exist' => 'Alle E-Mail-Adresse existierten bereits in der Datenbank.',
  'import_successful' => 'Erfolgreich in die Datenbank importiert und hinzugef&uuml;gt zu',
  'subscribed' => 'Abonniert auf',
  'adding_users' => 'F&uuml;ge Benutzer zur Liste hinzu',
  'select_lists' => 'W&auml;hlen Sie die Liste(n) aus, zu der/denen die E-Mail-Adressen hinzugef&uuml;gt werden sollen.',
  'no_lists' => 'Es sind keine Listen verf&uuml;gbar.',
  'info_emails_file' =>
  	'Die zu importierende Datei muss die E-Mail-Adressen enthalten, die Sie zu diesen Listen hinzuf&uuml;gen wollen.
	Alles was hinter der E-Mail-Adresse steht wird als Attribut "Info" des jeweiligen Benutzers gespeichert.
	Die weiteren Attribute dieser Benutzer k&ouml;nnen Sie unten angeben.
	<b>Achtung</b>: Die Datei muss eine reine Textdatei sein.
	Importieren Sie keine bin&auml;ren Dateien wie beispielsweise Word-Dokumente.',
  'emails_file' => 'Textdatei mit E-Mail-Adressen:',
  'field_delimiter' => 'Feld-Trennzeichen:',
  'tab_default' => '(Standard: TAB)',
  'record_delimiter' => 'Datensatz-Trennzeichen:',
  'line_break_default' => '(Standard: Zeilenschaltung)',
  'info_test_output' => 'Wenn Sie einen Test-Durchlauf durchf&uuml;hren, werden die E-Mail-Adressen nur auf dem Bildschirm ausgegeben und nicht in die Datenbank geschrieben. Dies ist hilfreich um zu pr&uuml;fen, ob das Format der importierten Datei korrekt ist. Es werden allerdings nur die ersten 50 Datens&auml;tze angezeigt.',
  'test_output' => 'Test-Durchlauf:',
  'info_notification_email' =>
  	'Wenn Sie nachfolgend die Option "Best&auml;tigungsanfrage senden" w&auml;hlen, wird den importierten Benutzern eine E-Mail geschickt, die sie beantworten m&uuml;ssen, um das Abonnement zu best&auml;tigen. Dies wird empfohlen, denn so k&ouml;nnen ung&uuml;ltige E-Mail-Adressen identifiziert werden.',
  'notification_email' => 'Best&auml;tigungsanfrage senden',
  'confirmed_immediately' => 'Sofort auf "best&auml;tigt" setzen',
  'import' => 'Importieren',
);
?>