<?php
$lan = array(
  'You do not have enough priviliges to view this page' => 'Sie haben keine Zugriffsberechtigung f&uuml;r diese Seite.',
  'Add a user' => 'Neuer Abonnent',
  'add user' => 'Neuer Abonnent',
  'Members of' => 'Abonnenten der Liste',
  'Tag all users in this page' => 'Alle Abonnenten auf dieser Seite markieren',
  'back to this list' => 'Listen-Details',
  'Download users on this list as a CSV file' => 'Abonnenten dieser Liste als CSV-Datei herunterladen',
  'Please enter a listid' => 'Bitte eine Listen-ID eingeben',
  'Processing' => 'Verarbeitung',
  'users were moved to' => 'Abonnenten wurden verschoben nach',
  'users were copied to' => 'Abonnenten wurden kopiert nach',
  'users were deleted from this list' => 'Abonnenten wurden von dieser Liste gel&ouml;scht',
  'Users found, click add to add this user' => 'Abonnenten gefunden',
  'Add' => 'Hinzuf&uuml;gen',
  'No user found with that email' => 'Kein Abonnent mit dieser E-Mail-Adresse gefunden',
  'Inserting user' => 'Abonnent wird hinzugef&uuml;gt',
  'User added' => 'Abonnent hinzugef&uuml;gt',
  'Deleting' => 'L&ouml;sche',
  'Done' => 'Abgeschlossen',
  'Users on this list' => 'Abonnenten dieser Liste',
  'Listing user' => 'Abonnenten',
  'to' => 'bis',//in sentence 'listing user 1  to  50'
  'Listing user 1 to 50' => 'Abonnenten 1 bis 50',
  'Members' => 'Abonnenten',
  'confirmed' => 'best&auml;tigt',
  'tag' => 'Markierung',
  'del' => 'L&ouml;schen',
  'Delete'=>'L&ouml;schen',
  '# msgs' => '# Nachrichten',
  '# rss' => '# RSS',
  'rss freq' => 'RSS-Frequenz',
  'last sent' => 'Letzter Versand',
  'What to do with "Tagged" users' => 'Aktionen f&uuml;r markierte Abonnenten',
  'This will only process the users in this page that have the "Tag" checkbox checked' =>
  	'Die folgenden Aktionen werden nur auf Abonnenten angewendet, die &uuml;ber die Checkbox "Markierung" ausgew&auml;hlt sind.',
  'delete' => 'L&ouml;schen',
  'move' => 'Verschieben',
  'copy' => 'Kopieren',
  'nothing' => 'Keine Aktion',
  'to' => 'auf Liste', # as in destination
  'from this list' => 'von dieser Liste',
  'What to do with all users' => 'Aktionen f&uuml;r alle Abonnenten',
  'This will process all users on this list' => 'Die folgenden Aktionen werden auf alle Abonnenten dieser Liste angewendet (unabh&auml;ngig davon, ob sie markiert sind oder nicht).',
  'do it' => 'Aktionen ausf&uuml;hren',
  
  
);
?>