<?php
$lan = array(
 'Please select a message to display' => 'Ch&#7885;n th&#432;',
 'Attachments for this message' => 'T&#7879;p &#273;&iacute;nh k&egrave;m cho th&#432; n&agrave;y',
 'No attachments' => 'Kh&ocirc;ng c&oacute; t&#7879;p &#273;&iacute;nh k&egrave;m',
 'Filename' => 'Filename',
 'Size' => 'Size',
 'Mime Type' => 'Mime Type',
 'Description' => 'Description',
 'Lists this message has been sent to' => 'C&aacute;c danh s&aacute;ch &#273;&#432;&#7907;c  g&#7917;i t&#7899;i',
 'None yet' => 'None yet',
 'Send this (same) message to (a) new list(s)' => 'G&#7917;i th&#432; n&agrave;y t&#7899;i danh s&aacute;ch kh&aacute;c',
 'List is Active' => 'Danh s&aacute;ch &#273;ang Active',
 'List is not Active' => 'Danh s&aacute;ch kh&ocirc;ng Active',
 '<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the "Requeue" function.' => '<b>Ch&uacute; &yacute;:</b> th&#432; n&agrave;y &#273;&atilde; &#273;&#432;&#7907;c g&#7917;i t&#7899;i t&#7845;t c&#7843; c&aacute;c danhs&aacute;ch. N&#7871;u b&#7841;n mu&#7889;n g&#7917;i t&#7899;i h&#7897;i vi&ecirc;n m&#7899;i &#273;&#259;ng k&yacute; h&atilde;y d&ugrave;ng ch&#7913;c n&#259;ng "Requeue".',
 'Resend' => 'G&#7917;i l&#7841;i',
 'id' => 'id',
 'subject' => 'subject',
 'fromfield' => 'from field',
 'tofield' => 'to field',
 'replyto' => 'reply to',
 'message' => 'message',
 'textmessage' => 'textmessage',
 'footer' => 'footer',
 'entered' => 'entered',
 'modified' => 'modified',
 'embargo' => 'embargo',
 'repeatinterval' => 'repearinterval',
 'repeatuntil' => 'repeatuntil',
 'status' => 'status',
 'userselection' => 'userselection',
 'sent' => 'sent',
 'htmlformatted' => 'htmlformatted',
 'sendformat' => 'sendformat',
 'template' => 'template',
 'processed' => 'processed',
 'astext' => 'as text',
 'ashtml' => 'as html',
 'astextandhtml' => 'as text and html',
 'aspdf' => 'as pdf',
 'astextandpdf' => 'as text and pdf',
 'viewed' => 'viewed',
 'bouncecount' => 'bounce count',
 'sendstart' => 'send start',
 'rsstemplate' => 'RSS template',
 'owner' => 'owner',

 # new in 2.10.1
 'edit this message' => 'So&#7841;n l&#7841;i th&#432;',
);
?>
