<?php

$lan = array(
'Running in testmode, no emails will be sent. Check your config file.' => 'Ejecutando en modo prueba, no se enviar&aacute; ning&uacute;n correo. Compruebe su fichero de configuraci&oacute;n.',
'The following restrictions have been set by your ISP:' => 'Su ISP ha establecido las siguientes restricciones:',
'Script stage' => 'Estadio de script',
'Finished, Nothing to do' => 'Acabado. No hay nada que hacer',
'messages sent in' => 'mensajes enviados en',
'seconds' => 'segundos',
'invalid emails' => 'email(s) no v&aacute;lido(s)',
'emails failed (will retry later)' => 'algunos emails fracasaron (se volver&aacute; a intentar depu&eacute;s)',
'emails unconfirmed (not sent)' => 'emails no confirmados (no se envi&oacute;)',
'Warning: script never reached stage 5' => 'Atenci&oacute;n: el script no alcanz&oacute; el estadio 5',
'This may be caused by a too slow or too busy server' => 'Esto puede ser debido a que el servidor es demasiado lento o est&aacute; demasiado ocupado',


'In safe mode, batches are set to a maximum of 100' => 'En modo seguro, los lotes tienen asignado un m&aacute;ximo de 100',
'Running in safe mode' => 'Ejecutando en modo seguro',
'msgs/hr' => 'mensajes/hora',
'Reload required' => 'Se necesita volver a cargar',
'Finished, All done' => 'Acabado, todo hecho',
'Script finished, but not all messages have been sent yet.' => 'El script ha finalizado, pero aun no se han enviado todos los mensajes.',
'Finished this run' => 'Acabada esta pasada',
'(test)' => '(prueba)',
'Would have sent' => 'Habr&iacute;a enviado',
'(test)' => '(prueba)',
'Would have sent' => 'Habr&iacute;a enviado',
'Started' => 'Comenzado...',
'Processing has been suspended by your ISP, please try again later' => 'Su ISP ha detenido la ejecuci&oacute;n, int&eacute;ntelo de nuevo m&aacute;s tarde', 
'Sending in batches of' => 'Enviando en lotes de',
'emails' => 'emails',
'This batch will be' => 'Este lote tendr&aacute;',
'emails, because in the last' => 'emails, porque en el &uacute;ltimo',
'emails were sent' => 'emails fueron enviados',
'Sending in batches of' => 'Enviando en lotes de',
'emails' => 'emails',
'In the last' => 'En los &uacute;ltimos',
'seconds more emails were sent' => 'segundos se enviaron m&aacute;s emails',
'than is currently allowed per batch' => 'de lo que actualmente se permite por lote',
'Sent in last run' => 'Enviados en la &uacute;ltima pasada',
'Skipped in last run' => 'Saltados en la &uacute;ltima pasada',
'Processing has started,' => 'Ha comenzado el procesamiento,',
'message(s) to process.' => 'mensaje(s) que procesar.',
'It is safe to click your stop button now, report will be sent by email to' => 'es seguro hacer click en el bo&oacute;n &#171;detener&#187; ahora. Se enviar&aacute; un informe por correo a',
'Your webserver is running in safe_mode. Please keep this window open. It may reload several times to make sure all messages are sent.' => 'Su servidor est&aacute; funcionando en &#171;safe_mode&#187; (modo seguro). Mantenga esta ventana abierta. Puede que se recargue varias veces para asegurar que se env&iacute;n todos los mensajes.',
'Reports will be sent by email to' => 'Los informes se enviar&aacute;n por correo a',
'Processing message' => 'Procesando mensaje',
'Message' => 'Mensaje',
'is an RSS feed for' => 'es un canal RSS para',
'Looking for users' => 'Buscando usuarios',
'users apply for attributes, now checking lists' => 'usuarios corresponden a los atributos. Comprobando listas',
'No users apply for attributes' => 'Ning&uacute;n usuario corresponde a los atributos',
'looking for users who can be excluded from this mailing' => 'buscando usuarios que puedan ser exclu&iacute;dos de esta pasada de &#171;processqueue&#187; (procesado de la cola de mensajes)',
'Process Killed by other process' => 'El proceso fue eliminado por otro proceso',
'Found them' => 'Encontrados',
'to process' => 'para procesar',
'No users to process for this batch' => 'No hay usuarios que procesar en este lote',
'batch limit reached' => 'se alcanz&oacute; el l&iacute;mite del lote',
'Process Killed by other process' => 'El proceso fue eliminado por otro proceso',
'Message I was working on has disappeared' => 'El mensaje en el que estaba trabajando ha desaparecido',
'Sending' => 'Enviando',
'It took' => 'Llev&oacute;',
'seconds to send' => 'segundos enviarlo',
'Failed sending to' => 'Fracas&oacute; el env&iacute; a',
'Unconfirmed user' => 'Usuario no confirmado',
'Not sending to' => 'No se enviar&aacute; a',
'already sent' => 'ya se envi&oacute;',
'Processed' => 'Procesado',
'out of' => 'de',
'Hmmm, No users found to send to' => 'Vaya vaya, no se encontraron usuarios a los que enviarlo',
'It took' => 'Llev&oacute;',
'to send this message' => 'segundos enviar este mensaje',
'waiting for' => 'esperando a',
'to make sure we don\'t exceed our limit of' => 'para estar seguros de no pasarnos de nuestro l&iacute;mite de',
'messages in' => 'mensajes en',

### new in 2.9.5
'Message Sending has started' => 'Se ha comenzado a enviar el mensaje',
'phplist has started sending the message with subject %s' => 'phplist ha comenzado a enviar el mensaje cuyo asunto es %s',
'to view the progress of this message, go to %s' => 'para ver el progreso del mensaje vaya a %s',
'There have been more than 10 attempts to send to %s that have been blocked for domain throttling.' => 'M&aacute;s de 10 intentos de enviar mensajes a %s han sido bloqueados por regulaci&oacute;n de tr&aacute;fico entre dominios.',
'Introducing extra delay to decrease throttle failures' => 'Incrementando el tiempo de espera para reducir fracasos debidos a la regulaci&oacute;n de tr&aacute;fico',
'%s is currently over throttle limit of %d per %d seconds' => '%s actualmente est&aacute; por encima del l&iacute;mite de regulaci&oacute;n de tr&aacute;fico, establecido en %d por %d segundos',
'not sending to ' => 'no se env&iacute;a a ',
'Message Sending has finished' => 'Finaliz&oacute; el env&iacute;o del mensaje',
'phplist has finished sending the message with subject %s' => 'PHPList ha terminado de enviar el mensaje cuyo asunto es %s'

);

?>
