<?php 
$lan = array(
  "NoRecord" => "そのようなレコードはありません。",
  "BackToBList" => "バウンスのリストに戻る",
  "NotFound" => "何もみつかりませんでした。<br/>",
  "AddedToB" => "次のユーザのバウンスカウントに%sを追加しました：ユーザ %s<br/>",
  "NotAddedToB" => "次のユーザのバウンスカウントに%sを追加できませんでした：ユーザ %s<br/>",
  "MadeUnconfirmed" => "ユーザ %s を unconfirmed にしました。<br/>",
  "MadeUserRText" => "ユーザ %s をテキストメールを受信できるようにしました。<br/>",
  "DelUser" => "ユーザ %s を削除しました。<br/>",
  "DeletingB" => "削除中。 バウンスメール %s ..",
  "DoneAndLoading" => "..実行されました。、次のバウンスメールをロード中..",
  "NoSRecord" => "そのようなレコードはありません。",
  "PossibleActions" => "可能なアクション:",
  "ForUser" => "次の電子メールをもつユーザに対して実行",
  "IncreaseB" => "バウンスカウントを増加",
  "IncreaseBNote" => "（減少するときはマイナスの数値を使用）",
  "MarkAsUnconfirmed" => "ユーザを unconfirmed とマークします。",
  "MarkAsUnconfirmedNote" => "(あなたは再度確定の要求を送信することができます。)",
  "SetReceiveText" => "ユーザがHTMLメールのかわりにテキストメールを受け取れるように設定します。",
  "DelUser1" => "ユーザの削除",
  "DelAndGo" => "このバウンスメールを削除し、次にいく",
  "DoAbove" => "上記を実行",
  "BounceDetails" => "バウンスメールの詳細:",
  "ID" => "ID",
  "Date" => "日付",
  "Status" => "ステータス",
  "Comment" => "コメント",
  "Header" => "ヘッダ",
  "Body" => "本文",
  
  # new in 2.9.5
  'Regular Expression' => '正規表現',
  'Action' => 'アクション',
  'Memo for this rule' => 'このルールに対するメモ',
  'Add new Rule' => '新規ルール追加',
  'Create New Rule based on this bounce' => 'このバウンスメールに基づく新規ルールを作成する',
);
?>