<?php

$lan = array(
  'Your database is out of date, please make sure to upgrade' => 'あなたのデータベースは旧式です。アップデートをしてください。',
  'Your version' => 'あなたのバージョン',
  'Latest version' => '最新バージョン',
  'phplist version' => '<a href="http://www.phplist.com">phplist</a> version',
  'Database has not been initialised' => 'データベースは初期化されませんでした。',
  'go to' => '続けるためには',
  'Initialise Database' => 'データベースの初期化',
  'to continue' => 'に行ってください。',
  'A new version of PHPlist is available!' => 'PHPlistの最新バージョンが利用可能です！',
  'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => '新しいバージョンはセキュリティーの問題をFIXしています。<br/>そのため可能か限りアップグレードすることをお勧めします。',
  'View what has changed' => '変更された箇所をみる',
  'Download' => 'ダウンロード',
  'System Functions' => 'システム機能',
  'Setup ' => 'セットアップ:',
  'Check Database structure' => 'データベース構造のチェック',
  'View the eventlog' => 'イベントログをみる',
  'Configuration functions' => 'コンフィギュレーション機能',
  'Configure Attributes' => '属性設定',
  'Control values for' => 'コントロール値：',
  'Control values for' => 'コントロール値：',
  'Control values for' => 'コントロール値：',
  'Configure Subscribe pages' => '購読ページの設定',
  'List and user functions' => 'リストとユーザ機能',
  'List the current lists' => '現在のリストを表示する',
  'List all Users' => 'すべてのユーザを表示する',
  'Reconcile the user database' => 'ユーザデータベースの調整',
  'Import Users' => 'ユーザのインポート',
  'Export Users' => 'ユーザのエクスポート',
  'Administrator functions' => '管理者機能',
  'Add, edit and remove Administrators' => '管理者の追加、編集および削除',
  'Configure attributes for administrators' => '管理者属性の設定',
  'Message functions' => 'メッセージ機能',
  'Configure Templates' => 'テンプレートの設定',
  'List all Messages' => 'すべてのメッセージのリスト',
  'Process the Message queue' => 'メッセージキューの処理',
  'RSS Functions' => 'RSS 機能',
  'Get RSS feeds' => 'RSSフィードの入手',
  'View RSS items' => 'RSSアイテムの閲覧',
  'Plugins' => 'プラグイン',
  'Upgrade' => 'アップグレード',
'Change your details (e.g. password)' => 'Change your details (e.g. password)',
'You have set TEST in config.php to 1, so it will only show what would be sent' => 'もしあなたが、config.phpのTESTを1に設定しているのであれば、送信されたことだけを表示します。',

  # added at a later stage
  'setup' => 'セットアップ',
  'upgrade' => 'アップグレード',
  'dbcheck' => 'データベースチェック',
  'eventlog' => 'イベントログ',
  'attributes' => '属性',
  'spage' => '購読ページ',
  'list' => 'リスト',
  'reconcileusers' => 'ユーザの調整',
  'import' => 'インポート',
  'export' => 'エクスポート',
  'admins' => '管理者',
  'adminattributes' => '管理者属性',
  'send' => '送信',
  'templates' => 'テンプレート',
  'processqueue' => 'キューの処理',
  'processbounces' => 'バウンスの処理',
  'getrss' => 'RSS入手',
  'viewrss' => 'RSS閲覧',
  'admin' => 'admin',
  'preparesend' => 'メッセージの準備',
  'sendprepared' => '準備済メッセージの送信',


);

?>