<?php 
$lan = array(

  'add_list' => 'リストの追加', //duplicated in import1_text
  'cant_connect' => 'リモートデータベースに接続できません。',
  'no_users_to_copy' => 'ユーザは何もコピーされません、プレフィックスは正しいですか？',
  'remote_server' => 'リモートサーバの詳細を入力してください。',
  'server' => 'サーバ:',
  'user' => 'ユーザ:',
  'passwd' => 'パスワード:',
  'database' => 'データベース名:',
  'table_prefix' => 'テーブルプレフィックス:',
  'usertable_prefix' => 'ユーザテーブルプレフィックス:',
  'select_lists' => '電子メールを追加するリストを選択',
  'copy_lists' => 'リモートサーバからリストをコピー（リストは名前でマッチされます）',
  'users_as_html' => '「HTMLメールを受信する」として新規ユーザをマーク:',
  'info_overwrite_existing' => 'もし"既存を上書き"をチェックするのでしたら、データベース内のユーザの情報は、インポートされた情報で置換されます。ユーザは電子メールアドレスでマッチされます。',
  'overwrite_existing' => '既存を上書き:',
  'connecting_remote' => 'リモートデータベースに接続中',
  'getting_data' => 'データを取得中 from ',
  'remote_version' => 'リモートバージョン：',
  'remote_has' => 'Remote version has',
  'users' => 'ユーザ',
  'lists' => 'リスト',
  'copying_lists' => 'リストをコピー中',
  'list' => 'リスト',
  'exists_locally' => 'ローカルに存在します。',
  'created_locally' => 'ローカルに作成されました。',
  'remote_list' => 'リモートリスト',
  'not_created' => '作成されませんでした。',
  'copying_attribs' => '属性をコピー中',
  'attrib' => '属性',
  'copying_users' => 'ユーザをコピー中',
  'overwrite_local' => 'ローカルデータを上書き中',
  'keep_local' => 'ローカルデータを保持中',
  'new_user' => 'は新規のユーザです。',
  'no_mapped_attrib' => 'エラー、属性がマップされませんでした：',
  'no_local_list' => 'エラー、ローカルリストが定義されませんでした：',
  'No lists available' => '利用可能なリストはありません。',
  'Done' => '実行',
  'new users' => '新規ユーザ',
  'and' => 'and',
  'existing users' => '既存ユーザ',
  'continue' => '続ける',

);
?>