<?php
$lan = array(
  'You do not have enough priviliges to view this page' => 'あなたはこのページをみるための十分な権限をもっていません。',
  'Add a user' => 'ユーザ追加',
  'add user' => 'ユーザ追加',
  'Members of' => 'メンバー：',
  'Tag all users in this page' => 'このページのすべてのユーザにTag',
  'back to this list' => 'このリストに戻る',
  'Download users on this list as a CSV file' => 'CSVファイルとしてこのリストのユーザをダウンロード',
  'Please enter a listid' => 'リストIDを入力してください。',
  'Processing' => '処理中',
  'users were moved to' => '人のユーザが次のリストに移動されました：',
  'users were copied to' => '人のユーザが次のリストにコピーされました：',
  'users were deleted from this list' => '人のユーザがこのリストから削除されました。',
  'Users found, click add to add this user' => 'ユーザがみつかりました。このユーザを追加するためには追加をクリックしてください',
  'Add' => '追加',
  'No user found with that email' => 'その電子メールアドレスをもつユーザはみつかりませんでした。',
  'Inserting user' => 'ユーザの挿入中',
  'User added' => 'ユーザが追加されました。',
  'Deleting' => '削除中',
  'Done' => '実行',
  'Users on this list' => '人のユーザがこのリストにいます。',
  'Listing user' => 'Listing user',
  'to' => 'to',//in sentence 'listing user 1  to  50'
  'Listing user 1 to 50' => 'Listing user 1 to 50',
  'Members' => 'メンバー',
  'confirmed' => '確定済',
  'tag' => 'tag',
  'del' => '削除',
  'Delete'=>'削除',
  '# msgs' => '# msgs',
  '# rss' => '# rss',
  'rss freq' => 'rss頻度',
  'last sent' => 'last sent',
  'What to do with "Tagged" users' => '"Tagged"ユーザの処理',
  'This will only process the users in this page that have the "Tag" checkbox checked' => '"Tag"チェックボックスがチェックされたこのページのユーザのみを処理します。',
  'delete' => '削除',
  'move' => '移動',
  'copy' => 'コピー',
  'nothing' => '何もしない',
  'to' => 'to', # as in destination
  'from this list' => 'このリストから',
  'What to do with all users' => 'すべてのユーザの処理',
  'This will process all users on this list' => 'このリストのすべてのユーザを処理します。',
  'do it' => '実行',
  
  
);
?>