<?php
$lan = array(
 'Please select a message to display' => '表示するメッセージを選択してください。',
 'Attachments for this message' => 'このメッセージへの添付',
 'No attachments' => '添付ファイルがありません。',
 'Filename' => 'ファイル名',
 'Size' => 'サイズ',
 'Mime Type' => 'Mime Type',
 'Description' => '説明',
 'Lists this message has been sent to' => 'このメッセージを送るリスト',
 'None yet' => 'まだ何もありません。',
 'Send this (same) message to (a) new list(s)' => '新しいリストにこの（同じ）メッセージを送る',
 'List is Active' => 'リストはアクティブです。',
 'List is not Active' => 'リストは非アクティブです。',
 '<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the "Requeue" function.' => '<b>注目:</b> このメッセージは既にすべてのリストに送信されました。新しいユーザに再送信するためには、"Requeue"機能を使ってください。',
 'Resend' => '再送信',
 'id' => 'id',
 'subject' => 'メールタイトル',
 'fromfield' => 'from 欄',
 'tofield' => 'to field',
 'replyto' => 'reply to',
 'message' => 'メッセージ',
 'textmessage' => 'テキスト形式でのメッセージ',
 'footer' => 'フッター',
 'entered' => '作成日時',
 'modified' => '修正日時',
 'embargo' => '差止日時',
 'repeatinterval' => 'repearinterval',
 'repeatuntil' => '繰り返し利用期限',
 'status' => 'ステータス',
 'userselection' => 'userselection',
 'sent' => 'sent',
 'htmlformatted' => 'HTMLフォーマット',
 'sendformat' => 'sendformat',
 'template' => 'テンプレート',
 'processed' => 'processed',
 'astext' => 'text形式',
 'ashtml' => 'html形式',
 'astextandhtml' => 'text形式およびhtml形式',
 'aspdf' => 'pdfファイル',
 'astextandpdf' => 'text形式およびpdfファイル',
 'viewed' => '閲覧済',
 'bouncecount' => 'バウンスカウント',
 'sendstart' => '送信スタート',
 'rsstemplate' => 'RSS テンプレート',
 'owner' => 'オーナー',

 # new in 2.10.1
 'edit this message' => 'このメッセージの編集',
);
?>
