<?php
$lan = array(
  "This page can only be called from the commandline" => "このページはコマンドラインからのみ呼び出されます。",
  "Bounce processing error" => "バウンス処理エラー",
  "Bounce Processing info" => "バウンス処理インフォ",
  "error" => "エラー",
  "info" => "インフォ",
  "system message bounced, user marked unconfirmed" => "システムメッセージがバウンスでした。ユーザは unconfirmed とマークされました。",
  "Bounced system message" => "バウンスシステムメッセージ",
  "User marked unconfirmed" => "ユーザは unconfirmed とマークされました。",
  "View Bounce" => "バウンスを閲覧",
  "Cannot create POP3 connection to" => "POP3コネクションが作成できません。",
  "Cannot open mailbox file" => "mailboxファイルがオープンできません。",
  "bounces to fetch from the mailbox" => "bounces to fetch from the mailbox",
  "Please do not interrupt this process" => "どうかこの処理を中止しないでください。",
  "bounces to process" => "bounces to process",
  "Processing first" => "Processing first",
  "bounces" => "バウンス",
  "Running in test mode, not deleting messages from mailbox" => "テストモードで実行中です。mailboxからメッセージを削除できません。",
  "Processed messages will be deleted from mailbox" => "処理されたメッセージはmailboxから削除されるでしょう。",
  "Deleting message" => "メッセージ削除中",
  "Closing mailbox, and purging messages" => "mailboxをクローズし、メッセージを消去中",
  "IMAP is not included in your PHP installation, cannot continue" => "IMAPはあなたのPHPインストールには含まれていません。続行できません。",
  "Check out" => "調べる",// or 'go look', 'consult', etc.
  "Bounce mechanism not properly configured" => "バウンスのメカニズムは適切に設定されませんでした。",
  "bounce_protocol not supported" => "バウンスのプロトコールはサポートされていません。",
  "Identifying consecutive bounces" => "連続したバウンスの同定中",
  "Nothing to do" => "何もしない",
  "Process Killed by other process" => "プロセスは他のプロセスにより停止されました。",
// 3 lines below = one sentence
  "User" => "ユーザ",
  "has consecutive bounces" => "連続したバウンスを持っています。",
  "over treshold, user marked unconfirmed" => "tresholdを超えました。ユーザは unconfirmed とマークされました。",
  "Auto Unsubscribed" => "自動で購読解除しました。",
// 2 lines below = one sentence
  "User auto unsubscribed for" => "User auto unsubscribed for",
  "consecutive bounces" => "連続したバウンス",
// 3 lines below = one sentence
  "Identifying consecutive bounces" => "連続したバウンスの同定中",
  "of" => "of",
  "users processed" => "処理されたユーザ",
  'processing first' => 'processing first',
  'Report:' => 'レポート:',
  'Below are users who have been marked unconfirmed. The number in [] is their userid, the number in () is the number of consecutive bounces' => '以下は unconfirmed とマークされたユーザです。[]中の数字はユーザIDで、()中の数字は連続したバウンスの数です。',
  
  ## new in 2.9.5
  'Processing bounces based on active bounce rules' => 'バウンスを処理することはアクティブなバウンスルールに基づきました。',
  'Auto Blacklisted' => '自動的にブラックリストに追加されました。',
  'User auto blacklisted for' => 'User auto blacklisted for',
  'bounce rule' => 'バウンスルール',
  'system message bounced, but unknown user' => 'system message bounced, but unknown user',
  'bounces processed by advanced processing' => 'bounces processed by advanced processing',
  'bounces were not matched by advanced processing rules' => 'bounces were not matched by advanced processing rules',
  'Report of advanced bounce processing:' => 'Report of advanced bounce processing:',
);
?>