<?php

$lan = array(
'General Information' => '一般インフォメーション',
'Title' => 'タイトル',
'Title of this set of lists' => 'この設定のタイトル',
'Please indicate how often you want to receive messages' => 'メッセージを受け取りたい頻度を指定してください。',
'Don\'t offer choice, default to <b>text</b>' => '選択はしない。デフォルト<b>text</b>',
'Don\'t offer choice, default to <b>HTML</b>' => '選択はしない。デフォルト<b>HTML</b>',
'Don\'t display email confirmation' => '電子メールの確認を表示しない。',
'Intro' => 'イントロ',
'Header' => 'ヘッダ',
'Footer' => 'フッタ',
'Thank you page' => 'Thank you ページ',
'Text for Button' => 'ボタンのテキスト',
'HTML Email choice' => 'HTMLメール選択',
'Offer checkbox for text' => 'textメールのためのチェックボックス',
'Offer checkbox for HTML' => 'HTMLメールのためのチェックボックス',
'Radio buttons, default to text' => 'ラジオボタン、デフォルトはtextメール',
'Radio buttons, default to HTML' => 'ラジオボタン、デフォルトはHTMLメール',
'Display Email confirmation' => '電子メールの確認を表示する。',
'Display email confirmation' => '電子メールの確認を表示する。',
'Message they receive when they subscribe' => '購読時に受け取るメッセージ',
'Message they receive when they confirm their subscription' => '購読の確定時に受け取るメッセージ',
'Subject' => 'メールタイトル',
'Message' => 'メッセージ',
'Select the attributes to use' => '使用したい属性を選択してください。',
'No lists available, please create one first' => '利用できるリストはありません。最初にリストを作成してください。',
'Attribute' => '属性',
'Check this box to use this attribute in the page' => 'ページでこの属性を使用するためにはこのボックスをチェックしてください。',
'Type' => 'タイプ',
'Default Value' => 'デフォルト値',
'Order of Listing' => '表示順',
'Is this attribute required?' => 'この属性は必須ですか？',
'Attribute' => '属性',
'Check this box to use this attribute in the page' => 'ページでこの属性を使用するためにはこのボックスをチェックしてください。',
'Type' => 'タイプ',
'Default Value' => 'デフォルト値',
'Order of Listing' => '表示順',
'Is this attribute required?' => 'この属性は必須ですか？',
'RSS settings' => 'RSS 設定',
'Intro Text' => 'イントロテキスト',
'Offer option to receive' => '受け取りたい申込オプション',
'Daily' => '毎日',
'default' => 'デフォルト',
'Offer option to receive' => '受け取りたい申込オプション',
'Weekly' => '毎週',
'default' => 'デフォルト',
'Offer option to receive' => '受け取りたい申込オプション',
'Monthly' => '毎月',
'default' => 'デフォルト',
'Select the lists to offer' => '申込可能なリストを選択してください。',
'Owner' => 'オーナー',
'Save Changes' => '変更を保存',
'Save and Activate' => '保存およびアクティブ',
'Save and Deactivate' => '保存および非アクティブ',

# Add 2006.10.10 日本PHPLISTユーザグループ
'Language file to use' => '利用する言語ファイル',

);
?>