<?php 
$lan = array(
  "NoRecord" => "Il n&rsquo;y a aucun dossier de ce type",
  "BackToBList" => "Retour vers la liste d&rsquo;emails rejet&eacute;s",
  "NotFound" => "Pas trouv&eacute;<br/>",
  "AddedToB" => "Ajout de %s au nombre d&rsquo;emails rejet&eacute;s pour l&rsquo;utilisateur %s<br/>",
  "NotAddedToB" => "Il n&rsquo;a pas &eacute;t&eacute; possible d&rsquo;ajouter %s au nombre d&rsquo;emails rejet&eacute;s pour l&rsquo;utilisateur %s<br/>",
  "MadeUnconfirmed" => "Utilisateur %s marqu&eacute; comme non-confirm&eacute;<br/>",
  "MadeUserRText" => "Utilisateur %s marqu&eacute; comme recevant des emails au format texte<br/>",
  "DelUser" => "Suppression de l&rsquo;utilisateur %s<br/>",
  "DeletingB" => "Suppression des messages rejet&eacute;s %s ..\n",
  "DoneAndLoading" => "..C&rsquo;est fait, chargement du prochain message rejet&eacute;..",
  "NoSRecord" => "Il n&rsquo;y a pas de dossier de ce type",
  "PossibleActions" => "Actions Possibles:",
  "ForUser" => "Pour l&rsquo;utilisateur avec l&rsquo;email",
  "IncreaseB" => "Augmenter le nombre de messages rejet&eacute;s avec",
  "IncreaseBNote" => "(utiliser des chiffres n&eacute;gatifs pour diminuer le chiffre)",
  "MarkAsUnconfirmed" => "Marquer l&rsquo;utilisateur comme Non-confirm&eacute;",
  "MarkAsUnconfirmedNote" => "(de mani&egrave;re &agrave; lui renvoyer la demande de confirmation)",
  "SetReceiveText" => "Marquer l&rsquo;utilisateur comme devant recevoir des messages au format texte et non plus au format HTML",
  "DelUser1" => "Supprimer utilisateur",
  "DelAndGo" => "Supprimer ce message rejet&eacute; et aller au suivant",
  "DoAbove" => "Ex&eacute;cuter",
  "BounceDetails" => "D&eacute;tails sur les messages rejet&eacute;s:",
  "ID" => "ID",
  "Date" => "Date",
  "Status" => "Statut",
  "Comment" => "Commentaire",
  "Header" => "En-t&ecirc;te",
  "Body" => "Corps du message",
'Regular Expression' => 'Expression r&eacute;guli&egrave;re',
'Action' => 'Action',
'Memo for this rule' => 'Memo pour cette r&egrave;gle',
'Add new Rule' => 'Ajouter une nouvelle R&egrave;gle',
'Create New Rule based on this bounce' => 'Cr&eacute;er une nouvelle r&egrave;gle en fonction de ce message rejet&eacute;',
);
?>