<?php
$lan = array(
  'That rule exists already' => 'Cette r&egrave;gle existe d&eacute;j&agrave;',
'Number of %s rules: %d' => 'Nombre de %s r&egrave;gles: %d',
'active' => 'active',
'candidate' => 'potentielle',
'candidate' => 'potentielle',
'active' => 'active',
'Bounce Regular Expressions' => 'Expressions r&eacute;guli&egrave;res pour les rejets',
'No Rules found' => 'Aucune r&egrave;gle trouv&eacute;e',
'rule' => 'r&egrave;gle',
'match' => 'correspondance',
'match' => 'correspondance',
'expression' => 'expression',
'action' => 'action',
'#bncs' => '#rejets',
'#bncs' => '#rejets',
'tag' => 'cocher',
'order' => 'ordre',
'del' => 'suppr',
'del' => 'suppr',
'with tagged rules: ' => 'avec les r&egrave;gles coch&eacute;es: ',
'delete' => 'supprimer',
'make active' => 'activer',
'make inactive' => 'd&eacute;sactiver',
'Save Changes' => 'Enregistrer les modifications',
'add a new rule' => 'ajouter une nouvelle r&egrave;gle',
'Regular Expression' => 'Expression R&eacute;guli&egrave;re',
'Action' => 'Action',
'Memo for this rule' => 'Memo pour cette r&egrave;gle',
'Add new Rule' => 'Ajouter une nouvelle r&egrave;gle',
);
?>