<?php
$lan = array( 
 'checklist for installation' => 'Checklist d\'Installation',
 'cannot be empty' => 'Ne peut &ecirc;tre vide',
 'editing' => 'Modification',
 'save changes' => 'Enregistrer les modifications',
 'edit' => 'modifier',

  # added 24 May 2006
  'delete user' => 'supprimer l\'utilisateur',
  'unconfirm user' => 'd&eacute;-confirmer l\'utilisateur',
  'blacklist user' => 'mettre l\'utilisateur sur la liste noire (blacklist)',
  'delete user and bounce' => 'supprimer l\'utilisateur et le bounce',
  'unconfirm user and delete bounce' => 'd&eacute;-confirmer l\'utilisateur et supprimer le bounce',
  'blacklist user and delete bounce' => 'mettre l\'utilisateur sur la liste noire (blacklist) et supprimer le bounce',
  'delete bounce' => 'supprimer le bounce',
  'Website address (without http://)' => 'Adresse du site web (sans http://)',
  'Domain Name of your server (for email)' => 'Nom de domaine du serveur mail',
  'Person in charge of this system (one email address)' => 'Personne en charge du syst&egrave;me (une adresse e-mail)',
  'How often do you want to check for a new version of phplist (days)' => 'P&eacute;riodicit&eacute; de d&eacute;tection automatique des mises-&agrave;-jour de PHPlist (en jours)',
  'List of people to CC in system emails (separate by commas)' => 'Liste de personnes &agrave; mettre en copie des e-mails syst&egrave;mes',
  'Who gets the reports (email address, separate multiple emails with a comma)' => 'Qui re&ccedil;oit les rapports (adresses e-mails s&eacute;par&eacute;es par une virgule)',
  'From email address for system messages' => 'Adresse d\'origine (from:) des e-mails syst&egrave;mes',
  'What name do system messages appear to come from' => 'Nom de l\'exp&eacute;diteur des messages syst&egrave;mes',
  'Reply-to email address for system messages' => 'Adresse de r&eacute;ponse (reply-to:) des messages syst&egrave;mes',
  'if there is only one visible list, should it be hidden in the page and automatically
    subscribe users who sign up (0/1)' => 'Si il n\'y a qu\'une liste visible, la cacher sur la page et y inscrire automatiquement les utilisateurs qui s\'enregistrent (0/1)',
  'width of a textline field (numerical)' => 'Largeur des champs de texte (nombre)',
  'dimensions of a textarea field (rows,columns)' => 'Dimensions des champs de type zone de texte (lignes, colonnes)',
  'Does the admin get copies of subscribe, update and unsubscribe messages (0/1)' => 'Est-ce que l\'admin re&ccedil;oit des copies des messages d\'inscription, mises &agrave; jour et d&eacute;sinscriptions (0/1)',
  'The default subscribe page when there are multiple' => 'Page d\'inscription par d&eacute;faut si il y en a plusieurs',
  'The default HTML template to use when sending a message' => 'Mod&egrave;le HTML par d&eacute;faut &agrave; utiliser pour envoyer un message',
  'URL where users can subscribe' => 'URL o&ugrave; les utilisateurs peuvent s\'inscrire',
  'URL where users can unsubscribe' => 'URL o&ugrave; les utilisateurs peuvent se d&eacute;sinscrire',
  'URL where users have to confirm their subscription' => 'URL o&ugrave; les utilisateurs peuvent confirmer leur inscription',
  'URL where users can update their details' => 'URL o&ugrave; les utilisateurs peuvent mettre &agrave; jour leurs d&eacute;tails',
  'URL where messages can be forwarded' => 'URL o&ugrave; les messages peuvent &ecirc;tre transmis',
  'Subject of the message users receive when they subscribe' => 'Sujet du message que les utlisateurs re&ccedil;oivent quand ils s\'inscrivent',
  'Message users receive when they subscribe' => 'Message que les utlisateurs re&ccedil;oivent quand ils s\'inscrivent',
  'Subject of the message users receive when they unsubscribe' => 'Sujet du message que les utlisateurs re&ccedil;oivent quand ils se d&eacute;sinscrivent',
  'Message users receive when they unsubscribe' => 'Message que les utlisateurs re&ccedil;oivent quand ils se d&eacute;sinscrivent',
  'Subject of the message users receive after confirming their email address' => 'Sujet du message que les utlisateurs re&ccedil;oivent quand ils ont confirm&eacute; leur adresse e-mail',
  'Message users receive after confirming their email address' => 'Message que les utlisateurs re&ccedil;oivent quand ils ont confirm&eacute; leur adresse e-mail',
  'Subject of the message users receive when they have changed their details' => 'Sujet du message que les utlisateurs re&ccedil;oivent quand ils ont mis &agrave; jour leurs d&eacute;tails',
  'Message that is sent when users change their information' => 'Message que les utlisateurs re&ccedil;oivent quand ils ont mis &agrave; jour leurs d&eacute;tails',
  'Part of the message that is sent to their new email address when users change their information, and the email address has changed' => 'Morceau du message envoy&eacute; &agrave; leur nouvelle adresse e-mail quand les utilisateurs mettent &agrave; jour leurs d&eacute;tails et changent d\'adresse e-mail',
  'Part of the message that is sent to their old email address when users change their information, and the email address has changed' => 'Morceau du message envoy&eacute; &agrave; leur ancienne adresse e-mail quand les utilisateurs mettent &agrave; jour leurs d&eacute;tails et changent d\'adresse e-mail',
  'Subject of message to send when users request their personal location' => 'Sujet du message que les utlisateurs re&ccedil;oivent quand ils demandent leur localisation personnelle',
  'Message to send when they request their personal location' => 'Message que les utlisateurs re&ccedil;oivent quand ils demandent leur localisation personnelle',
  'Default footer for sending a message' => 'Pied de page par d&eacute;faut des messages envoy&eacute;s',
  'Footer used when a message has been forwarded' => 'Pied de page pour un message transmis (forward&eacute;)',
  'Header of public pages. The header should start with &lt;/head&gt; . You can add header elements, but don\'t add the title or other basic header elements.' => 'T&ecirc;te de page des pages publiques. La t&ecirc;te de page doit commencer par &lt;/head&gt; . Vous pouvez ajouter des &eacute;l&eacute;ments de headers, mais n\'ajoutez pas le titre ou d\'autres &eacute;l&eacute;ments de headers basiques.',
  'Footer of public pages' => 'Pied de page des pages pibliques',
  'Charset for HTML messages' => 'Table de caract&egrave;res pour les messages HTML',
  'Charset for Text messages' => 'Table de caract&egrave;res pour les messages texte',
  'CSS for HTML messages without a template' => 'CSS pour les messages HTML sans mod&egrave;le',
  'Domains that only accept text emails, one per line' => 'Domaines qui acceptent seulement les messages en texte (un par ligne)',
  'Minimum amount of items to send in an RSS feed' => 'Nombre minimum d\'&eacute;l&eacute;ments &agrave; envoyer dans un flux RSS',
  'Template for text item in RSS feeds' => 'Mod&egrave;le pour un &eacute;l&eacute;ment en texte dans un flux RSS',
  'Template for HTML item in RSS feeds' => 'Mod&egrave;le pour un &eacute;l&eacute;ment en HTML dans un flux RSS',
  'Maximum amount of items to send in an RSS feed' => 'Nombre maximum d\'&eacute;l&eacute;ments &agrave; envoyer dans un flux RSS',
  'Template for separator between feeds in RSS feeds (text)' => 'Mod&egrave;le pour s&eacute;parateur entre les flux dans un flux RSS (texte)',
  'Template for separator between feeds in RSS feeds (HTML)' => 'Mod&egrave;le pour s&eacute;parateur entre les flux dans un flux RSS (HTML)',
  'Width in px of FCKeditor Area' => 'Largeur de la zone de FCKeditor (en pixels)',
  'Height in px of FCKeditor Area' => 'Hauteur de la zone de FCKeditor (en pixels)',
);
?>
