<?php

$lan = array(
  'Your database is out of date, please make sure to upgrade' => 'Votre base n&rsquo;est pas &agrave; jour, veillez &agrave; la mettre &agrave; jour',
  'Your version' => 'Votre version',
  'Latest version' => 'La derni&egrave;re version',
  'phplist version' => 'version <a href="http://www.phplist.com">phplist</a>',
  'Database has not been initialised' => 'La base n&rsquo;a pas &eacute;t&eacute; initialis&eacute;e',
  'go to' => 'aller &agrave;',
  'Initialise Database' => 'Initialiser Base de donn&eacute;es',
  'to continue' => 'pour continuer',
  'A new version of PHPlist is available!' => 'Une nouvelle version de PHPlist est disponible!',
  'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => 'La nouvelle version a peut-&ecirc;tre r&eacute;solu des probl&egrave;mes de s&eacute;curit&eacute;,<br/>nous vous recommandons de mettre &agrave; jour votre syst&egrave;me au plus t&ocirc;t',
  'View what has changed' => 'Voir ce qui a chang&eacute;',
  'Download' => 'T&eacute;l&eacute;charger',
  'System Functions' => 'Fonctions concernant le Syst&egrave;me',
  'Setup ' => 'Configuration initiale ',
  'Check Database structure' => 'V&eacute;rifier la structure de la Base de donn&eacute;es',
  'View the eventlog' => 'Visualiser le Journal des &eacute;v&eacute;nements (eventlog)',
  'Configuration functions' => 'Fonctions concernant la Configuration',
  'Configure Attributes' => 'Configurer les Attributs',
  'Control values for' => 'Configurer les valeurs de',
  'Control values for' => 'Configurer les valeurs de',
  'Control values for' => 'Configurer les valeurs de',
  'Configure Subscribe pages' => 'Configurer les pages d&rsquo;Inscription',
  'List and user functions' => 'Fonctions concernant les Listes et les Utilisateurs',
  'List the current lists' => 'Afficher toutes les listes',
  'List all Users' => 'Afficher tous les Utilisateurs',
  'Reconcile the user database' => 'Mettre de l&rsquo;ordre dans la base de donn&eacute;es des utilisateurs',
  'Import Users' => 'Importer des Utilisateurs',
  'Export Users' => 'Exporter des Utilisateurs',
  'Administrator functions' => 'Fonctions concernant les Administrateurs',
  'Add, edit and remove Administrators' => 'Ajouter, modifier et supprimer des Administrateurs',
  'Configure attributes for administrators' => 'Configurer les attributs des administrateurs',
  'Message functions' => 'Fonctions concernant les Messages',
  'Configure Templates' => 'Configurer les Mod&egrave;les',
  'List all Messages' => 'Afficher tous les Messages',
  'Process the Message queue' => 'Envoyer les messages dans la file d\'attente',
  'RSS Functions' => 'Fonctions RSS',
  'Get RSS feeds' => 'Importer les donn&eacute;es des fils RSS',
  'View RSS items' => 'Afficher les donn&eacute;es import&eacute;es des fils RSS',
  'Plugins' => 'Plugins',
  'Upgrade' => 'Mise &agrave; jour',
'Change your details (e.g. password)' => 'Modifiez vos donn&eacute;es personnelles (par exemple, votre mot de passe)',
'You have set TEST in config.php to 1, so it will only show what would be sent' => 'Vous avez choisi d&rsquo;&ecirc;tre en mode TEST dans le fichier config.php, ce qui fait que vous allez uniquement pouvoir afficher ce qui aurait &eacute;t&eacute; envoy&eacute;',


  # added at a later stage
  'setup' => 'installation',
  'upgrade' => 'mettre &agrave; jour',
  'dbcheck' => 'v&eacute;rifier la base de donn&eacute;es',
  'eventlog' => 'journal des &eacute;v&eacute;nements',
  'attributes' => 'attributs',
  'spage' => 'page(s) d&rsquo;inscription',
  'list' => 'listes',
  'reconcileusers' => 'faire le m&eacute;nage',
  'import' => 'importer',
  'export' => 'exporter',
  'admins' => 'administrateurs',
  'adminattributes' => 'attributs des admins',
  'send' => 'envoyer',
  'templates' => 'mod&egrave;les',
  'processqueue' => 'traiter la file d&rsquo;attente',
  'processbounces' => 'traiter les rejets',
  'getrss' => 'importer des fils rss',
  'viewrss' => 'afficher les fils rss',
  'admin' => 'admin',
  'preparesend' => 'pr&eacute;parer un message',
  'sendprepared' => 'envoyer un message pr&eacute;par&eacute;',

);

?>