<?php
$lan = array(

  'add_list' => 'Ajouter une liste', //duplicated in import1_text
  'cant_connect' => 'la connexion &agrave; la base du serveur distant a &eacute;chou&eacute;',
  'no_users_to_copy' => 'Il n&rsquo;y a pas d&rsquo;utilisateur &agrave; copier, le pr&eacute;fixe est-il correct?',
  'remote_server' => 'Rentrez les coordonn&eacute;es du Serveur distant',
  'server' => 'Serveur:',
  'user' => 'Utilisateur:',
  'passwd' => 'Mot de passe:',
  'database' => 'Nom de la base de donn&eacute;es:',
  'table_prefix' => 'Pr&eacute;fixe de la table:',
  'usertable_prefix' => 'Pr&eacute;fix de la table des Utilisateurs (Usertable):',
  'select_lists' => 'S&eacute;lectionnez les listes auxquelles vous voulez ajouter les emails',
  'copy_lists' => 'Copier les listes du serveur distant (les listes sont identifi&eacute;es par leur nom)',
  'users_as_html' => 'Marquer les nouveaux utilisateurs comme devant recevoir les messages au format HTML:',
  'info_overwrite_existing' => 'Si vous cochez "Ecraser Donn&eacute;es Existantes", l&rsquo;information sur un utilisateur dans la base de donn&eacute;es sera remplac&eacute;e par les donn&eacute;es import&eacute;es.  Les utilisateurs sont identifi&eacute;s par leur email.',
  'overwrite_existing' => 'Ecraser Donn&eacute;es Existantes:',
  'connecting_remote' => 'Connexion avec la base de donn&eacute;es distante',
  'getting_data' => 'R&eacute;cup&eacute;ration de donn&eacute;es de ',
  'remote_version' => 'La version distante est',
  'remote_has' => 'La version distante comporte',
  'users' => 'utilisateurs',
  'lists' => 'listes',
  'copying_lists' => 'Copie des listes',
  'list' => 'Liste',
  'exists_locally' => 'existe en local',
  'created_locally' => 'cr&eacute;&eacute; en local',
  'remote_list' => 'Liste distante',
  'not_created' => 'non cr&eacute;&eacute;',
  'copying_attribs' => 'Copie des attributs',
  'attrib' => 'Attribut',
  'copying_users' => 'Copie des utilisateurs',
  'overwrite_local' => '&eacute;crasement des donn&eacute;es en local',
  'keep_local' => 'maintien des donn&eacute;es en local',
  'new_user' => 'est un nouvel utilisateur',
  'no_mapped_attrib' => 'Erreur, aucun attribu d&eacute;fini pour',
  'no_local_list' => 'Erreur, aucune liste en local d&eacute;finie pour',
  'No lists available' => 'Aucune liste disponible',
  'Done' => 'C&rsquo;est fait',
  'new users' => 'nouveaux utilisateurs',
  'and' => 'et',
  'existing users' => 'utilisateurs d&eacute;j&agrave; existants',
  'continue' => 'Continuer',

);
?>