<?php
$lan = array(
  'You do not have enough priviliges to view this page' => 'Vous n&rsquo;&ecirc;tes pas autoris&eacute;(e) &agrave; visualiser cette page',
  'Add a user' => 'Ajouter un utilisateur',
  'add user' => 'Ajouter l&rsquo;Utilisateur',
  'Members of' => 'Membres de',
  'Tag all users in this page' => 'Cocher tous les utilisateurs sur cette page',
  'back to this list' => 'retour vers cette liste',
  'Download users on this list as a CSV file' => 'T&eacute;l&eacute;charger les utilisateurs de cette liste dans un fichier CSV',
  'Please enter a listid' => 'Choisissez une listid (identifiant de liste)',
  'Processing' => 'En cours de traitement',
  'users were moved to' => 'utilisateurs ont &eacute;t&eacute; d&eacute;plac&eacute;s vers',
  'users were copied to' => 'utilisateurs ont &eacute;t&eacute; copi&eacute;s sur',
  'users were deleted from this list' => 'utilisateurs ont &eacute;t&eacute; supprim&eacute;s de cette liste',
  'Users found, click add to add this user' => 'Utilisateur trouv&eacute;, cliquer sur Ajouter pour ajouter cet utilisateur',
  'Add' => 'Ajouter',
  'No user found with that email' => 'Aucun utilisateur avec cet email n&rsquo;a &eacute;t&eacute; trouv&eacute;',
  'Inserting user' => 'Insertion de l&rsquo;utilisateur',
  'User added' => 'Utilisateur ajout&eacute;',
  'Deleting' => 'Suppression',
  'Done' => 'C&rsquo;est fait',
  'Users on this list' => 'Utilisateurs sur cette liste',
  'Listing user' => 'Liste des utilisateurs',
  'to' => '&agrave;',//in sentence 'listing user 1  to  50'
  'Listing user 1 to 50' => 'Liste des utilisateurs 1 &agrave; 50',
  'Members' => 'Membres',
  'confirmed' => 'confirm&eacute;',
  'tag' => 'cocher',
  'del' => 'suppr',
  'Delete'=>'Supprimer',
  '# msgs' => '# msgs',
  '# rss' => '# rss',
  'rss freq' => 'fr&eacute;q rss',
  'last sent' => 'dernier envoi',
  'What to do with "Tagged" users' => 'Avec les utilisateurs "coch&eacute;s"',
  'This will only process the users in this page that have the "Tag" checkbox checked' => 'Ceci ne traitera que les utilisateurs sur cette page dont vous avez coch&eacute; la case "Cocher"',
  'delete' => 'Supprimer',
  'move' => 'D&eacute;placer',
  'copy' => 'Copier',
  'nothing' => 'Ne rien faire',
  'to' => 'vers', # as in destination
  'from this list' => 'de cette liste',
  'What to do with all users' => 'Avec tous les utilisateurs',
  'This will process all users on this list' => 'Ceci traitera tous les utilisateurs sur cette liste',
  'do it' => 'ex&eacute;cuter',
  
  
);
?>