<?php
$lan = array(
  'Resending confirmation request to' => 'Demande de confirmation renvoy&eacute;e &agrave;',
  'user found' => 'utilisateur trouv&eacute;',
  'no user found' => 'pas trouv&eacute; d&rsquo;utilisateur',
  'unable to find original email' => 'impossible de retrouver l&rsquo;email original',
  'Marking all users confirmed' => 'Tous les utilisateurs marqu&eacute;s comme &eacute;tant confirm&eacute;s',
  'users apply' => 'utilisateurs concern&eacute;s',
  'Creating UniqID for all users who do not have one' => 'Cr&eacute;ation d&rsquo;un UniqID pour tous les utilisateurs qui n&rsquo;en ont pas',
  'Marking all users to receive HTML' => 'Tous les utilisateurs marqu&eacute;s comme devant recevoir les emails au format HTML',
  'Marking all users to receive text' => 'Tous les utilisateurs marqu&eacute;s comme devant recevoir les emails au format texte',
  'Deleting users who are not on any list' => 'Suppression des utilisateurs qui ne sont sur aucune liste',
  'Moving users who are not on any list to' => 'D&eacute;placement des utilisateurs qui ne sont sur aucune liste vers',
  'Deleting users with more than' => 'Suppression des utilisateurs qui ont plus de',
  'bounces' => 'messages rejet&eacute;s',
  'Resending request for confirmation to users who signed up after' => 'Renvoi de la demande de confirmation aux utilisateurs qui se sont inscrits apr&egrave;s le',
  'and before' => 'et avant le',
  'Deleting unconfirmed users who signed up after' => 'Suppression des utilisateurs non-confirm&eacute;s qui se sont inscrits apr&egrave;s le',
  'Trying to merge duplicates' => 'Tentative de fusion des doubles',
  'Don&rsquo;t know how to' => 'Je ne sais pas comment',
  'Listing users with an invalid email' => 'Liste des utilisateurs avec un email invalide',
  'Users deleted' => 'Utilisateurs supprim&eacute;s',
  'Users apply' => 'Utilisateurs concern&eacute;s',
  'Trying to fix users with an invalid email' => 'Tentative de rectification des dossiers des utilisateurs dont l&rsquo;email n&rsquo;est pas valide',
  'User' => 'Utilisateur',
  'Users fixed' => 'Dossiers d&rsquo;utilisateurs rectifi&eacute;s',
  'Users could not be fixed' => 'Dossiers d&rsquo;utilisateurs n&rsquo;ont pas pu &ecirc;tre rectifi&eacute;s',
  'Deleting users with an invalid email' => 'Suppression des utilisateurs avec un email invalide',
  'Marking users with an invalid email as unconfirmed' => 'Les utilisateurs avec un email invalide marqu&eacute;s comme non-confirm&eacute;s',
  'Users updated' => 'Utilisateurs mis &agrave; jour',
  'Cleaning some user tables of invalid entries' => 'Nettoyage de certaines tables d&rsquo;utilisateurs d&rsquo;entr&eacute;es invalides',
  'entries apply' => 'entr&eacute;es concern&eacute;es',
  'Delete will delete user and all listmemberships' => 'Suppression va supprimer l&rsquo;utilisateur et toutes ses inscriptions aux listes',
  'Done' => 'C&rsquo;est fait',
  'Users' => 'Utilisateurs',
  'found' => 'trouv&eacute;s',
  'in the database' => 'dans la base de donn&eacute;es',
  'Delete all users who are not subscribed to any list' => 'Supprimer tous les utilisateurs qui ne sont inscrits sur aucune liste',
  # next two are one sentence
  'To try to (automatically)' => 'Essayer de (automatiquement)',
  'Find users who have an invalid email' => 'Trouver les utilisateurs qui ont un email invalide',
  'Make sure that all users have a UniqID' => 'V&eacute;rifier que tous les utilisateurs ont un UniqID',
  'Mark all users with an invalid email as unconfirmed' => 'Marquer tous les utilisateurs avec un email invalide comme &eacute;tant non-confirm&eacute;s',
  'Delete users who have an invalid email' => 'Supprimer les utilisateurs avec un email invalide',
  'Mark all users to receive HTML' => 'Marquer tous les utilisateurs comme devant recevoir les emails au format HTML',
  'Mark all users to receive text' => 'Marquer tous les utilisateurs comme devant recevoir les emails au format texte',
  'Mark all users confirmed' => 'Marquer tous les utilisateurs comme &eacute;tant confirm&eacute;s',
  'Fix emails for users who have an invalid email' => 'Rectifier les emails des utilisateurs qui ont un email invalide',
  'Remove Stale entries from the database' => 'Eliminer des entr&eacute;es trop anciennes et non mises &agrave; jour de la base de donn&eacute;es',
  'Merge Duplicate Users' => 'Fusionner les dossiers d&rsquo;utilisateurs en double',  
  'To move all users who are not subscribed to any list to' => 'Pour d&eacute;placer tous les utilisateurs qui ne sont inscrits sur aucune liste vers',
  'Click here' => 'Cliquer ici',
  'To delete all users with more than' => 'Pour supprimer tous les utilisateurs avec plus de',
  'bounces' => 'messages rejet&eacute;s',
  'Note: this will use the total count of bounces on a user, not consecutive bounces' => 'Note: cette option utilisera le nombre total de messages rejet&eacute;s de l&rsquo;utilisateur, pas le nombre de messages rejet&eacute;s de mani&egrave;re cons&eacute;cutive',
  'To resend the request for confirmation to users who signed up and have not confirmed their subscription' => 'Pour renvoyer la demande de confirmation aux utilisateurs qui se sont inscrits mais qui n&rsquo;ont pas confirm&eacute; leur inscription',
  'Date they signed up after' => 'Inscription apr&egrave;s le',
  'Date they signed up before' => 'Inscription avant le',
  'Text to prepend to email' => 'Texte &agrave; ajouter &agrave; l&rsquo;email',
  'prependemailtext' => '
D&eacute;sol&eacute;s de vous emb&ecirc;ter: nous sommes en train de faire le 
m&eacute;nage dans notre base de donn&eacute;es et il semble que vous vous 
&ecirc;tes inscrit(e) &agrave; nos listes sans confirmer votre inscription.

Nous aimerions vous permettre de re-confirmer votre inscription.
Les instructions sur comment confirmer votre inscription sont ci-dessous.
  ',
  'To delete users who signed up and have not confirmed their subscription' => 'Pour supprimer les utilisateurs qui se sont inscrits mais qui n&rsquo;ont pas confirm&eacute; leur inscription',
  'Don\'t know how to' => 'Je ne sais pas comment',

);
?>