<?php
$lan = array (
  'warnemailattribute' => 'Email是系統欄位',
  'converting' => '轉換中',
  'from' => '從',
  'to' => '到',
  'deleting' => '刪除中',
  'cannotdelete' => '無法刪除欄位，目前被下面表單使用：',
  'warninglongtime' => '注意，修改任何類型的欄位都可能需要等候一段時間',
  'sorrymergingcbgroupnotimplemented' => '抱歉，合併選取方塊群組還沒完成',
  'cannotmergeone' => '無法只合併一個欄位',
  'merging' => '合併中',
  'into' => '變成',
  'notsametype' => '只能夠合併同樣類型的欄位',
  'existing' => '已存在的欄位',
  'noattributesdefined' => '還沒定義任何欄位',
  'loadfrom' => '讀取資料自',
  'defaults' => '預設值',
  'attribute' => '欄位',
  'usedin' => '使用於',
  'forms' => '表單',
  'tag' => '標籤',
  'name' => '名稱',
  'type' => '類型',
  'defaultvalue' => '預設值',
  'orderoflisting' => '順序',
  'isrequired' => '必填？',
  'textline' => '文字方塊',
  'checkbox' => '核選方塊',
  'checkboxgroup' => '核選方塊群組',
  'radio' => '單選項目',
  'select' => '下拉選單',
  'hidden' => '隱藏項目',
  'textarea' => '多行文字',
  'date' => '日期',
  'savechanges' => '儲存',
  'withtagged' => '使用標示的欄位',
  'delete' => '刪除',
  'merge' => '合併',
  'addnew' => '新增欄位',

);
?>