<?php
$lan = array (
  'NoRecord' => '沒有記錄',
  'BackToBList' => '回到退信清單',
  'NotFound' => '找不到<br/>',
  'AddedToB' => '新增 %s 到 %s 的退信指數<br/>',
  'NotAddedToB' => '無法新增 %s 到 %s 的退信指數<br/>',
  'MadeUnconfirmed' => '讓使用者 %s 狀態變成未確認<br/>',
  'MadeUserRText' => '讓使用者 %s 訂閱純文字版本<br/>',
  'DelUser' => '刪除使用者 %s<br/>',
  'DeletingB' => '刪除退信中 %s ..',
  'DoneAndLoading' => '..完成，讀取下一封退信..',
  'NoSRecord' => '沒有這筆記錄',
  'PossibleActions' => '動作：',
  'ForUser' => '給使用者信箱',
  'IncreaseB' => '增加退信指數於',
  'IncreaseBNote' => '(使用負數來減少)',
  'MarkAsUnconfirmed' => '讓使用者狀態變成未確認',
  'MarkAsUnconfirmedNote' => '(接著您就可以重新寄送確認信函)',
  'SetReceiveText' => '設定使用者訂閱純文字版本',
  'DelUser1' => '刪除使用者',
  'DelAndGo' => '刪除這封退信並且讀取下一封',
  'DoAbove' => '執行',
  'BounceDetails' => '退信細節：',
  'ID' => 'ID',
  'Date' => '日期',
  'Status' => '狀態',
  'Comment' => '意見',
  'Header' => '頁首',
  'Body' => '內容',
  'Regular Expression' => '樣式比對',
  'Action' => '操作',
  'Memo for this rule' => '這個規則的備註',
  'Add new Rule' => '新增規則',
  'Create New Rule based on this bounce' => '以這封退信建立新規則',

);
?>