<?php
$lan = array (
  'You do not have enough priviliges to view this page' => '您沒有存取這個頁面的權限',
  'Add a user' => '新增使用者',
  'add user' => '新增使用者',
  'Members of' => '訂閱者於',
  'Tag all users in this page' => '選取這個頁面的所有使用者',
  'back to this list' => '回到這個電子報',
  'Download users on this list as a CSV file' => '下載這個電子報的使用者資料(CSV格式)',
  'Please enter a listid' => '請輸入電子報編號',
  'Processing' => '處理中',
  'users were moved to' => '個使用者移到',
  'users were copied to' => '個使用者複製到',
  'users were deleted from this list' => '個使用者從這個電子報移除',
  'Users found, click add to add this user' => '個使用者，點選新增來繼續',
  'Add' => '新增',
  'No user found with that email' => '沒有使用這個 email 的會員',
  'Inserting user' => '新增使用者中',
  'User added' => '使用者新增了',
  'Deleting' => '刪除中',
  'Done' => '完成',
  'Users on this list' => '這個電子報的訂閱者',
  'Listing user' => '列出訂閱者',
  'to' => '到',
  'Listing user 1 to 50' => '列出前五十個訂閱者',
  'Members' => '會員',
  'confirmed' => '已確認',
  'tag' => '選取',
  'del' => '刪除',
  'Delete' => '刪除',
  '# msgs' => '# msgs',
  '# rss' => '# rss',
  'rss freq' => 'rss 頻率',
  'last sent' => '最後寄出',
  'What to do with "Tagged" users' => '標示的使用者要執行什麼動作',
  'This will only process the users in this page that have the "Tag" checkbox checked' => '這將只會處理頁面中有溝選的使用者',
  'delete' => '刪除',
  'move' => '移動',
  'copy' => '複製',
  'nothing' => '無',
  'from this list' => '自這個電子報',
  'What to do with all users' => '要對所有使用者進行什麼動作',
  'This will process all users on this list' => '這會影響本電子報的所有訂閱者',
  'do it' => '執行',

);
?>