<?php
$lan = array (
  'Resending confirmation request to' => '重新寄送確認訊息到',
  'user found' => '個使用者',
  'no user found' => '沒有找到使用者',
  'unable to find original email' => '無法找到原來的信箱',
  'Marking all users confirmed' => '將所有使用者標示為已確認',
  'users apply' => '個使用者符合',
  'Creating UniqID for all users who do not have one' => '為所有還沒處理的使用者建立唯一的代碼',
  'Marking all users to receive HTML' => '將所有使用者標示為接收 HTML 信件',
  'Marking all users to receive text' => '將所有使用者標示為接收純文字信件',
  'Deleting users who are not on any list' => '刪除沒有訂閱任何電子報的使用者',
  'Moving users who are not on any list to' => '移動沒有訂閱任何電子報的使用者到',
  'Deleting users with more than' => '刪除使用者，如果超過',
  'bounces' => '封退信',
  'Resending request for confirmation to users who signed up after' => '重新寄送確認信函給使用者，註冊日期晚於',
  'and before' => '且早於',
  'Deleting unconfirmed users who signed up after' => '刪除未確認的使用者，註冊日期晚於',
  'Trying to merge duplicates' => '嘗試合併重複資料',
  'Don\'t know how to' => '不知道如何',
  'Listing users with an invalid email' => '列出信箱錯誤的使用者',
  'Users deleted' => '個使用者刪除了',
  'Users apply' => '個使用者調整了',
  'Trying to fix users with an invalid email' => '嘗試修正信箱錯誤的使用者資料',
  'User' => '使用者',
  'Users fixed' => '個使用者資料修正了',
  'Users could not be fixed' => '個使用者資料無法修正',
  'Deleting users with an invalid email' => '刪除信箱錯誤的使用者',
  'Marking users with an invalid email as unconfirmed' => '將信箱錯誤的使用者標示為未確認',
  'Users updated' => '個使用者更新了',
  'Cleaning some user tables of invalid entries' => '清楚使用者資料表中的錯誤項目',
  'entries apply' => '筆資料處理了',
  'Delete will delete user and all listmemberships' => '將會刪除使用者與所有的會員關係',
  'Done' => '完成',
  'Users' => '個使用者',
  'found' => '發現於',
  'in the database' => '資料庫中',
  'Delete all users who are not subscribed to any list' => '刪除未訂閱任何電子報的使用者',
  'To try to (automatically)' => '嘗試（自動）',
  'Find users who have an invalid email' => '找尋信箱錯誤的使用者',
  'Make sure that all users have a UniqID' => '確認所有使用者都有唯一的代碼',
  'Mark all users with an invalid email as unconfirmed' => '將信箱格式有誤的使用者標示為未確認',
  'Delete users who have an invalid email' => '刪除信箱格式錯誤的使用者',
  'Mark all users to receive HTML' => '將所有使用者標示為接收 HTML 信件',
  'Mark all users to receive text' => '將所有使用者標示為接收 純文字 信件',
  'Mark all users confirmed' => '標示所有使用者為已確認',
  'Fix emails for users who have an invalid email' => '修正信箱錯誤的使用者資料',
  'Remove Stale entries from the database' => '從資料庫中移除較舊的資料',
  'Merge Duplicate Users' => '合併重複的使用者',
  'To move all users who are not subscribed to any list to' => '移動未訂閱任何電子報的使用者到',
  'Click here' => '點選這裡',
  'To delete all users with more than' => '刪除所有使用者，如果超過',
  'Note: this will use the total count of bounces on a user, not consecutive bounces' => '注意：這將會使用個別使用者的退信總數，不包括連續退信',
  'To resend the request for confirmation to users who signed up and have not confirmed their subscription' => '重新寄送確認信函給那些未確認的使用者',
  'Date they signed up after' => '訂閱日期晚於',
  'Date they signed up before' => '訂閱日期早於',
  'Text to prepend to email' => '附加到信件前的訊息',
  'prependemailtext' => '抱歉，不是刻意要打擾您；我們目前正在清理資料庫，發現您曾經訂閱了我們的電子報，但是還沒完成確認。

我們希望透過這封信讓您能夠重新確認，請參考下面步驟。',
  'To delete users who signed up and have not confirmed their subscription' => '刪除訂閱但未確認的使用者',
  'Delete Tagged Users' => '刪除標示的使用者',

);
?>