<?php
$lan = array (
  'General Information' => '一般資訊',
  'Title' => '標題',
  'Title of this set of lists' => '這個系列電子報的標題',
  'Please indicate how often you want to receive messages' => '請指定您希望收到電子報的頻率',
  'Don\'t offer choice, default to <b>text</b>' => '不提供選擇，預設為 <b>純文字</b>',
  'Don\'t offer choice, default to <b>HTML</b>' => '不提供選擇，預設為 <b>HTML</b>',
  'Don\'t display email confirmation' => '不顯示確認信箱欄位',
  'Intro' => '介紹',
  'Header' => '頁首',
  'Footer' => '頁尾',
  'Thank you page' => '感謝訂閱頁面',
  'Text for Button' => '按鈕文字',
  'HTML Email choice' => 'HTML 郵件選擇',
  'Offer checkbox for text' => '提供純文字選項',
  'Offer checkbox for HTML' => '提供 HTML 選項',
  'Radio buttons, default to text' => '單選表單，預設為純文字',
  'Radio buttons, default to HTML' => '單選表單，預設為 HTML',
  'Display Email confirmation' => '顯示信箱確認',
  'Display email confirmation' => '顯示信箱確認',
  'Message they receive when they subscribe' => '訂閱時會收到的信件',
  'Message they receive when they confirm their subscription' => '完成確認後會收到的信件',
  'Subject' => '主旨',
  'Message' => '內容',
  'Select the attributes to use' => '選擇要使用的屬性',
  'No lists available, please create one first' => '沒有任何電子報，請先建立',
  'Attribute' => '屬性',
  'Check this box to use this attribute in the page' => '勾選要在訂閱頁面使用的屬性',
  'Type' => '類型',
  'Default Value' => '預設值',
  'Order of Listing' => '順序',
  'Is this attribute required?' => '必填項目？',
  'RSS settings' => 'RSS 設定',
  'Intro Text' => '介紹',
  'Offer option to receive' => '提供接收項目',
  'Daily' => '每日',
  'default' => '預設',
  'Weekly' => '每週',
  'Monthly' => '每月',
  'Select the lists to offer' => '選擇要提供的電子報',
  'Owner' => '擁有者',
  'Save Changes' => '儲存',
  'Save and Activate' => '儲存＆啟用',
  'Save and Deactivate' => '儲存＆停用',

);
?>