<?php
$lan = array (
  'Delete will delete user and all listmemberships' => '這將會刪除使用者與相關的會員關係',
  '%s users apply' => '%s 個符合的使用者',
  'Users marked <font color=red>red</font> are unconfirmed' => '標示為 <font color=red>紅色</font> 字的使用者表示未確認',
  'Show only unconfirmed users' => '只顯示未確認的使用者',
  'Show only blacklisted users' => '只顯示黑名單的使用者',
  'email' => '信箱',
  'bouncecount' => '退信數量',
  'entered' => '輸入日期',
  'modified' => '修改日期',
  'foreignkey' => '外部鍵值',
  'Sort by' => '排序',
  'desc' => '降冪',
  'asc' => '升冪',
  'Go' => '到',
  'Find a user' => '找尋使用者',
  'Email' => '信箱',
  'Foreign Key' => '外部鍵值',
  'reset' => '重設',
  'Download all users as CSV file' => '以 CSV 格式下載所有使用者資料',
  'Add a User' => '新增使用者',
  'confirmed' => '已確認',
  'bl l' => '黑名單',
  'del' => '刪除',
  'key' => '鍵值',
  'msgs' => '信件',
  'rss' => 'rss',
  'rss freq' => 'rss 頻率',
  'bncs' => '退信',
  'No users apply' => '沒有符合的使用者',
  'Your privileges for this page are insufficient' => '您沒有足夠的權限',
  'Delete will delete user from the list' => '這將會刪除所有電子報的使用者',
  'deleting' => '刪除中',
  'Done' => '完成',
  'User added' => '使用者新增了',
  'Add this user' => '新增這個使用者',
  'Click on a link to use the corresponding public subscribe page to add this user:' => '點選一個連結來透過一致的公開訂閱頁面新增使用者：',
  'Click this link to use the public subscribe page to add this user:' => '點選這個連結來使用公開訂閱頁面新增使用者：',
  'Listing user %d to %d' => '列出使用者 %d 到 %d',
  'last sent' => '最後發信日期',

);
?>