<?php
$lan = array (
  'Delete will delete user and all listmemberships' => '這將會刪除使用者與相關的會員關係',
  'No Lists' => '沒有電子報',
  'update page' => '更新頁面',
  'unsubscribe page' => '取消訂閱頁面',
  'History' => '存取記錄',
  'User Details' => '使用者細節',
  'You only have privileges to view this page, not change any of the information' => '您只能夠檢視這個頁面，無法修改任何資料',
  'Delete will delete user from the list' => '這將會從電子報中刪除使用者',
  'User added to group' => '使用者新增到群組',
  'User added to list %s' => '使用者新增到電子報 %s',
  'Changes saved' => '異動儲存了',
  'Deleting' => '刪除中',
  'Done' => '完成',
  'No such User' => '沒有這個使用者',
  'Add a new User' => '新增使用者',
  'encrypted' => '加密',
  'Save Changes' => '儲存異動',
  'User is blacklisted. No emails will be sent to this user' => '使用者在黑名單中，無法寄送信件給他',
  'Mailinglist Membership' => '電子報會員',
  'Group Membership' => '會員群組',
  'Please select the groups this user is a member of' => '請選擇這個使用者要歸類的群組',
  'ID' => '編號',
  'Email' => '信箱',
  'Is this user confirmed' => '已確認？',
  'Is this user blacklisted' => '黑名單？',
  'Number of bounces on this user' => '這個使用者的退信數量',
  'Entered' => '加入',
  'Last Modified' => '最後更新',
  'Unique ID for User' => '這個使用者的唯一代碼',
  'Send this user HTML emails' => '寄送 HTML 信件給這個使用者',
  'Which page was used to subscribe' => '要使用那個頁面來訂閱',
  'RSS Frequency' => 'RSS 頻率',
  'Last time password was changed' => '最後更新密碼時間',
  'Is this account disabled?' => '停用這個帳號？',
  'Additional data' => '其他資訊',
  'Foreign Key' => '外部鍵值',
  'Error adding user, please check that the user exists' => '新增使用者錯誤，請檢查這個使用者是否已經存在',

);
?>