<?php

$lan = array(
  'Your database is out of date, please make sure to upgrade' => 'Uw databaseversie komt niet overeen met de huidige versie van PhpList.<br/>Voer eerst een upgrade van de database uit alvorens verder te gaan!',
  'Your version' => 'Uw versie',
  'Latest version' => 'Laatste versie',
  'phplist version' => '<a href="http://www.phplist.com">phplist</a> versie',
  'Database has not been initialised' => 'de database is niet geïnitialiseerd',
  'go to' => 'ga naar',
  'Initialise Database' => 'Initialiseer Database',
  'to continue' => 'Om verder te gaan',
  'A new version of PHPlist is available!' => 'Een nieuwe versie van PHPlist is beschikbaar!',
  'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => 'De nieuwe versie kan veiligheidszaken hebben opgelost,<br/>Het is dus aangeraden om zo snel mogelijk te upgraden',
  'View what has changed' => 'Bekijk wat er is verandert',
  'Download' => 'Download',
  'System Functions' => 'Systeem opties',
  'Setup ' => 'Setup ',
  'Check Database structure' => 'Controleer Database structuur',
  'View the eventlog' => 'Bekijk het logboek',
  'Configuration functions' => 'Configuratie opties',
  'Configure Attributes' => 'Configureer Attributen',
  'Control values for' => 'Controleer waarden voor',
  'Configure Subscribe pages' => 'Configureer inschrijf pagina&acute;s',
  'List and user functions' => 'Inschrijf- en gebruiksers opties',
  'List the current lists' => 'Overzicht van inschrijflijsten',
  'List all Users' => 'Toevoegen, bewerken en verwijderen van gebruikers',
  'Reconcile the user database' => 'Kuis de gebruikersdatabase op',
  'Import Users' => 'Importeer Gebruikers',
  'Export Users' => 'Exporteer Gebruikers',
  'Administrator functions' => 'Beheerder opties',
  'Add, edit and remove Administrators' => 'Toevoegen, bewerken en verwijderen van beheerders',
  'Configure attributes for administrators' => 'Configureer attributen voor beheerders',
  'Message functions' => 'Bericht opties',
  'Configure Templates' => 'Configureer Sjablonen',
  'List all Messages' => 'Overzicht van alle berichten',
  'Process the Message queue' => 'Verwerk berichten in wachtrij',
  'RSS Functions' => 'RSS opties',
  'Get RSS feeds' => 'Ontvang RSS feeds',
  'View RSS items' => 'Bekijk RSS items',
  'Plugins' => 'Plugins',
  'Upgrade' => 'Upgrade',
'Change your details (e.g. password)' => 'Wijzig uw details (b.v. wachtwoord)',
'You have set TEST in config.php to 1, so it will only show what would be sent' => 'U heeft TEST in config.php op 1 gezet, dus zal er enkel worden getoond wat er zou worden verzonden',

  # added at a later stage
  'setup' => 'Setup',
  'upgrade' => 'Database upgrade',
  'dbcheck' => 'Controleer database',
  'eventlog' => 'Logboek',
  'configure' => 'Algemeen',
  'attributes' => 'Attributen',
  'spage' => 'Inschrijf paginas',
  'list' => 'Lijsten',
  'users' => 'Gebruikers',
  'reconcileusers' => 'Herwerk gebruikers',
  'import' => 'Importeren',
  'export' => 'Exporteren',
  'admins' => 'Beheerders',
  'adminattributes' => 'Beheerder attributen',
  'send' => 'Nieuw bericht',
  'templates' => 'Sjablonen',
  'messages' => 'Overzicht',
  'processqueue' => 'Verwerk wachtrij',
  'processbounces' => 'Verwerk bounces',
  'bounces' => 'Bounces overzicht',
  'getrss' => 'Ontvang rss',
  'viewrss' => 'Bekijk rss',
  'admin' => 'Beheerder',
  'preparesend' => 'Bereid verzenden voor',
  'sendprepared' => 'verzending voorbereid',


);

?>
