<?php
$lan = array(
 'You do not have access to this page' => 'U heeft geen toegang tot deze pagina',
 'You do not have access to this page' => 'U heeft geen toegang tot deze pagina',
 'Select Message to view' => 'Selecter te bekijken bericht',
 'There are currently no messages to view' => 'Er zijn momenteel geen berichten te bekijken',
 'Last few Messages' => 'Laatste berichten',
 'owner' => 'eigenaar',
 'date' => 'datum',
 'sent' => 'verzonden',
 'bounced' => 'bounced',
 'views' => 'bekeken',
 'rate' => 'rate',
 'Comparison to other admins' => 'Vergelijking met andere admins',
 'views' => 'bekeken',
 'rate' => 'rate',
 'View Details for a Message' => 'Bekijk Details voor een Bericht',
 'Subject' => 'Onderwerp',
 'Entered' => 'Ingegaan',
 'Sent' => 'verzonden',
 'Message Open Statistics' => 'Message Open Statistics',
 'Listing user %d to %d' => 'Lijst van gebruikers %d tot %d',
 'Listing user %d to %d' => 'Lijst van gebruikers %d tot %d',
 'Entries' => 'Entries',
 'sent' => 'verzonden',
 'firstview' => 'firstview',
 'lastview' => 'lastview',
 'views' => 'bekeken',
 'firstview' => 'firstview',
 'responsetime' => 'responsetime',
'sec' => 'sec',
);
?>
