<?php 
$lan = array(
  "NoRecord" => "Nenhum registro",
  "BackToBList" => "Voltar para a lista de emails de erro",
  "NotFound" => "N&atilde;o encontrado<br/>",
  "AddedToB" => "Adicionado %s ao contador de emails de erro do usu&aacute;rio  %s<br/>",
  "NotAddedToB" => "N&atilde;o pode adicionar %s ao contador de emails de erro pelo usu&aacute;rio %s<br/>",
  "MadeUnconfirmed" => "Revogar confirma&ccedil;&atilde;o do usu&aacute;rio %s<br/>",
  "MadeUserRText" => "Configurar usu&aacute;rio %s para receber mensagens texto puro<br/>",
  "DelUser" => "Usu&aacute;rio %s apagado<br/>",
  "DeletingB" => "Apagando email de erro %s ...\n",
  "DoneAndLoading" => "... Conclu&iacute;do, carregando pr&oacute;ximo email de erro...",
  "NoSRecord" => "Nenhum Registro",
  "PossibleActions" => "A&ccedil;&otilde;es Poss&iacute;veis:",
  "ForUser" => "Para usu&aacute;rios com email",
  "IncreaseB" => "Incrementar o contador de emails de erro",
  "IncreaseBNote" => "(use n&uacute;meros negativos para decrementar)",
  "MarkAsUnconfirmed" => "Marcar usu&aacute;rio como n&atilde;o confirmado",
  "MarkAsUnconfirmedNote" => "(voc&ecirc; poder&aacute; reenviar o pedido de confirma&ccedil;&atilde;o)",
  "SetReceiveText" => "Definir que o usu&aacute;rio deve receber mensagem tipo texto ao inv&eacute;s de HTML",
  "DelUser1" => "Apagar usu&aacute;rio",
  "DelAndGo" => "Apagar este email de erro e ir para o pr&oacute;ximo",
  "DoAbove" => "Voltar ao anterior",
  "BounceDetails" => "Detalhes do Email com problema:",
  "ID" => "ID",
  "Date" => "Data",
  "Status" => "Status",
  "Comment" => "Coment&aacute;rio",
  "Header" => "Cabe&ccedil;&aacute;lho",
  "Body" => "Corpo da mensagem",
 
  # new in 2.9.5
  'Regular Expression' => 'Express&atilde;o regular',
  'Action' => 'A&ccedil;&atilde;o',
  'Memo for this rule' => 'Memo para esta regra',
  'Add new Rule' => 'Adicionar nova Regra',
  'Create New Rule based on this bounce' => 'Criar Nova Regra baseada neste email de erro',
);
?>
