<?php

$lan = array(
  'warnemailattribute' => 'Email is een systeem attribuut',
  'converting' => 'Omzetten',
  'from' => 'Van',
  'to' => 'Naar',
  'deleting' => 'verwijderen',
  'cannotdelete' => 'Kan attribuut niet verwijderen, het wordt gebruikt door de volgende form:',
  'warninglongtime' => 'Opgelet, Het veranderen van het type van het attribuut kan lang duren',
  'sorrymergingcbgroupnotimplemented' => 'Sorry, het samenvoegen van checkbox groepen wordt nog niet uitgevoerd',
  'cannotmergeone' => 'Kan niet 1 attribuut samenvoegen',
  'merging' => 'Samenvoegen',
  'into' => 'in',
  'notsametype' => 'Enkel attribuuten van hetzelfde typen kunnen worden samengevoegd',
  'existing' => 'Bestaande attributen',
  'noattributesdefined' => 'Er zijn nog geen attributen gedefinieerd',
  'loadfrom' => 'Data laden van',
  'defaults' => 'Vooraf bepaalde standaardwaarden',
  'attribute' => 'Attribuut',
  'usedin' => 'gebruikt in',
  'forms' => 'forms',
  'tag' => 'Markering', # action
  'name' => 'Naam',
  'type' => 'Type', # as in aspect of, type of attribute
  'defaultvalue' => 'Standaard waarde',
  'orderoflisting' => 'Volgorde',
  'isrequired' => 'Is dit attribuut vereist?',
  'textline' => 'tekstlijn',
  'checkbox' => 'checkbox',
  'checkboxgroup' => 'checkboxgroep',
  'radio' => 'radio',
  'select' => 'selecteren',
  'hidden' => 'verborgen',
  'textarea' => 'tekstblok',
  'date' => 'datum',
  'savechanges' => 'Wijzigingen opslaan',
  'withtagged' => 'Met GEMARKEERDE attributen',
  'delete' => 'Werwijder',
  'merge' => 'Voeg samen',
  'addnew' => 'Voeg nieuw attribuut toe',
  'authoritative list' => 'authoritatieve lijst',
);

?>