<?php
$lan = array(
  "NoRecord" => "Geen dergelijk item",
  "BackToBList" => "Terug naar de lijst van bounces",
  "NotFound" => "Niet gevonden<br/>",
  "AddedToB" => "%s toegevoegd aan bouncetelling voor gebruiker %s<br/>",
  "NotAddedToB" => "Kon %s niet toevoegen aan bouncetelling voor gebruiker %s<br/>",
  "MadeUnconfirmed" => "Gebruiker %s niet bevestigd gemaakt<br/>",
  "MadeUserRText" => "Gebruiker %s zal vanaf nu enkel tekst ontvangen<br/>",
  "DelUser" => "Gebruiker %s verwijdert<br/>",
  "DeletingB" => "Verwijderen bounce %s ...",
  "DoneAndLoading" => " Klaar<br/>Laden van volgende bounce...",
  "NoSRecord" => "Geen dergelijk item",
  "PossibleActions" => "Mogelijke acties:",
  "ForUser" => "Voor gebruiker met email",
  "IncreaseB" => "Vergroot bouncetelling met",
  "IncreaseBNote" => "(Gebruik negatieve nummers om te verminderen)",
  "MarkAsUnconfirmed" => "Markeer gebruiker als niet bevestigd",
  "MarkAsUnconfirmedNote" => "(zo kunt u het verzoek om bevestiging opnieuw versturen)",
  "SetReceiveText" => "Wijzig gebruiker's email formaat naar text i.p.v. HTML",
  "DelUser1" => "Verwijder gebruiker",
  "DelAndGo" => "Verwijder dit bouncebericht en ga naar de volgende",
  "DoAbove" => "Doe het bovenstaande",
  "BounceDetails" => "Bounce details:",
  "ID" => "ID",
  "Date" => "Datum",
  "Status" => "Status",
  "Comment" => "Commentaar",
  "Header" => "Header",
  "Body" => "Body",

  # new in 2.9.5
  'Regular Expression' => 'Reguliere Expressie',
  'Action' => 'Actie',
  'Memo for this rule' => 'Memo voor deze regel',
  'Add new Rule' => 'Voeg nieuwe regel toe',
  'Create New Rule based on this bounce' => 'Maak nieuwe regel aan gebaseerd op deze bounce',
);
?>