<?php

$lan = array(
  'Your database is out of date, please make sure to upgrade' => 'Uw database is over datum, zorg ervoor dat je deze upgrade',
  'Your version' => 'Uw versie',
  'Latest version' => 'Laatste versie',
  'phplist version' => '<a href="http://www.phplist.com">phplist</a> versie',
  'Database has not been initialised' => 'de database is niet geïnitialiseerd',
  'go to' => 'ga naar',
  'Initialise Database' => 'Initialiseer Database',
  'to continue' => 'Om verder te gaan',
  'A new version of PHPlist is available!' => 'Een nieuwe versie van PHPlist is beschikbaar!',
  'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => 'De nieuwe versie kan veiligheidszaken hebben opgelost,<br/>Het is dus aangeraden om zo snel mogelijk te upgraden',
  'View what has changed' => 'Bekijk wat er is verandert',
  'Download' => 'Download',
  'System Functions' => 'Systeem opties',
  'Setup ' => 'Setup ',
  'Check Database structure' => 'Controleer Database structuur',
  'View the eventlog' => 'Bekijk het logboek',
  'Configuration functions' => 'Configuratie opties',
  'Configure Attributes' => 'Configureeer Attributen',
  'Control values for' => 'Controleer waarden voor',
  'Control values for' => 'Controleer waarden voor',
  'Control values for' => 'Controleer waarden voor',
  'Configure Subscribe pages' => 'Configureeer inschrijf pagina&acute;s',
  'List and user functions' => 'Lijst en gebruiksers opties',
  'List the current lists' => 'Lijst van lijsten',
  'List all Users' => 'Lijst van alle gebruikers',
  'Reconcile the user database' => 'Breng gebruikersdatabase in gelijkheid',
  'Import Users' => 'Importeer Gebruikers',
  'Export Users' => 'Exporteer Gebruikers',
  'Administrator functions' => 'Administrator opties',
  'Add, edit and remove Administrators' => 'Voeg toe, bewerk en verwijder administrators',
  'Configure attributes for administrators' => 'Configureeer attributen voor administrators',
  'Message functions' => 'Bericht opties',
  'Configure Templates' => 'Configureer Sjablonen',
  'List all Messages' => 'Lijst van alle berichten',
  'Process the Message queue' => 'Verwerk berichten in wachtrij',
  'RSS Functions' => 'RSS opties',
  'Get RSS feeds' => 'Ontvang RSS feeds',
  'View RSS items' => 'Bekijk RSS items',
  'Plugins' => 'Plugins',
  'Upgrade' => 'Upgrade',
'Change your details (e.g. password)' => 'Wijzig uw details (b.v. wachtwoord)',
'You have set TEST in config.php to 1, so it will only show what would be sent' => 'U heeft TEST in config.php op 1 gezet, dus zal er enkel worden getoond wat er zou worden verzonden',

  # added at a later stage
  'setup' => 'setup',
  'upgrade' => 'upgrade',
  'dbcheck' => 'controleer db',
  'eventlog' => 'logboek',
  'attributes' => 'attributen',
  'spage' => 'spagina',
  'list' => 'lijst',
  'reconcileusers' => 'herwerk gebruikers',
  'import' => 'importeer',
  'export' => 'exporteer',
  'admins' => 'administrators',
  'adminattributes' => 'admin attributen',
  'send' => 'verzend',
  'templates' => 'sjablonen',
  'processqueue' => 'verwerk wachtrij',
  'processbounces' => 'verwerk bounces',
  'getrss' => 'ontvang rss',
  'viewrss' => 'bekijk rss',
  'admin' => 'admin',
  'preparesend' => 'bereid verzenden voor',
  'sendprepared' => 'verzend voorbereid',


);

?>