<?php
$lan = array(
  "Import emails from IMAP folders" => "Importeer emails uit IMAP mappen",
  "No lists available" => "Geen lijsten beschikbaar",
  "Add a list" => "Voeg een lijst toe",
  "personal" => "persoonlijk",
  "email" => "email",
  "folder" => "map",
  "date" => "datum",
  "can't connect" => "kan niet verbinden",
  "Processing" => "Verwerken",
  "messages" => "berichten",
  "done" => "klaar",
  "imap_getmailboxes failed" => "imap_getmailboxes mislukt",
  "Please enter details of the IMAP account" => "Geef aub de details voor uw IMAP account",
  "Select the headers fields to search" => "Selecteer de headers velden die moeten worden doorzocht",
  "Select the lists to add the emails to" => "Selecteer de lijsten waar de emails in moeten komen",
  "Adding users to list" => "Gebruikers toevoegen aan lijst",
  "Mark new users as HTML" => "Markeer nieuwe gebruiker als HTML",
/* read lines below as sentences: if you check 'overwrite' information about a user... etc. */
  "If you check" => "Als u het volgende aanvinkt",
  "Overwrite Existing" => "Overschrijf bestaand",
  "information about a user in the database will be replaced by the imported information. Users are matched by email." => "dan zal de info van een gebruiker in de database worden vervangen door de geimporteerde info. Gebruikers komen overeen per email.",
  "Only use complete addresses" => "Gebruik enkel volledige adressen",
  "addresses that do not have a real name will be ignored. Otherwise all emails will be imported." => "adressen die geen echte naam bevatten zullen worden genegeerd. Anders worden alle emails geimporteerd.",
  "If you choose" => "Als u het volgende aanvinkt",
  "send notification email" => "verzend bevestigings mail",
  "the users you are adding will be sent the request for confirmation of subscription to which they will have to reply. This is recommended, because it will identify invalid emails." => "dan zullen de gebruikers die u toevoegd een email ontvangen met verzoek om bevestiging voor inschrijving waarop ze zullen moeten reageren. Dit is aanbevolen omdat het ongeldige emails zal identificeren.",
  "Send&nbsp;Notification&nbsp;email&nbsp;" => "Verzend&nbsp;Bevestigings&nbsp;mail&nbsp;",
  "Make confirmed immediately" => "Bevestig onmiddellijk",
  "import3info" => "Er zijn twee manieren om de namen van gebruikers toe te voegen,
 ofwel 1 attribuut voor de volledige naam of 2 attributen, een voor de voornaam en een voor de achternaam.
Als u kiest voor 'twee attributen', dan zal de naam worden gesplitst na het eerste attribuut.",
  "Use one attribute for name" => "Gebruik 1 attribuut voor de naam",
  'Use two attributes for the name' => 'Gebruik 2 attributen voor de naam',
  "Attribute one" => "Attribuut 1",
  "Create Attribute" => "Maak Attribuut",
  "Attribute two" => "Attribuut 2",
  "Cannot continue" => "Kan niet verder gaan",
  "ok" => "ok",
  "failed" => "mislukt",
  "Processed" => "Verwerkt",
  "folders and" => "mappen en",
  "unique emails found" => "unieke emails gevonden",
  "list" => "lijst",
  "lists" => "lijsten",
  "new email was" => "Nieuwe email was",
  "new emails were" => "Nieuwe emails waren",
  "email was" => "email was",
  "emails were" => "emails waren",
  "All the emails already exist in the database and are members of the" => "Alle emails bestaan al in de database en zijn lid van de",
  "succesfully imported to the database and added to" => "succesfully imported to the database and added to",
  "subscribed to the" => "ingeschreven bij",
  "emails already existed in the database" => "emails bestaan al in de database",
  "Invalid Emails found." => "Ongeldige Emails gevonden.",
  "These records were added, but the email has been made up. You can find them by doing a search on" => "Deze rapporten zijn toegevoegd, maar de email is opgemaakt. Je kan ze vinden door te zoeken naar",
  "These records were deleted. Check your source and reimport the data. Duplicates will be identified." => "Deze rapporten zijn verwijdert. Controleer je bron en importeer de data opnieuw. Dubbelle adressen zullen worden gemeld.",
  "No emails found" => "Geen emails gevonden",
  "Import some more emails" => "Importeer nog enkele emails",
  'Server' => 'Server',
  'User' => 'Gebruiker',
  'Password' => 'Wachtwoord',
  'Continue' => 'Ga verder',
  'Process Selected Folders' => 'Verwerk geselecteerde mappen',
);
?>