<?php
$lan = array(

  'add_list' => 'Lijst toevoegen', //duplicated in import1_text
  'cant_connect' => 'kan geen verbinding maken met de database',
  'no_users_to_copy' => 'Geen gebruikers te kopieren, is de prefix juist?',
  'remote_server' => 'Geef aub de details van de Server',
  'server' => 'Server:',
  'user' => 'Gebruiker:',
  'passwd' => 'Wachtwoord:',
  'database' => 'Database Naam:',
  'table_prefix' => 'Tabel prefix:',
  'usertable_prefix' => 'Gebruikerstabel prefix:',
  'select_lists' => 'Selecteer de lijst waar de email in moeten komen',
  'copy_lists' => 'Kopieer de lijst van de server (lijsten komen overeen per naam)',
  'users_as_html' => 'Markeen nieuwe gebruiker als HTML:',
  'info_overwrite_existing' => 'Als u "Overschrijf Bestaand" aanvinkt, dan zal de info van een gerbuiker worden vervangen door de geimporteerde info. Gebruikers komen overeen per email.',
  'overwrite_existing' => 'Overschrijf Bestaand:',
  'connecting_remote' => 'Maak verbinding met de database op afstand',
  'getting_data' => 'Ontvangen van data van ',
  'remote_version' => 'Versie op afstand is',
  'remote_has' => 'Versie op afstand heeft',
  'users' => 'gebruikers',
  'lists' => 'lijsten',
  'copying_lists' => 'Lijsten Kopieren',
  'list' => 'Lijst',
  'exists_locally' => 'Bestaat al lokaal',
  'created_locally' => 'Lokaal aangemaakt',
  'remote_list' => 'Lijst op afstand',
  'not_created' => 'niet aangemaakt',
  'copying_attribs' => 'Attributen kopieren',
  'attrib' => 'Attribuut',
  'copying_users' => 'Gebruikers Kopieren',
  'overwrite_local' => 'overschrijven van locale data',
  'keep_local' => 'behouden van locale data',
  'new_user' => 'is een nieuwe gebruiker',
  'no_mapped_attrib' => 'Fout, geen in kaart gebrachte attributen voor',
  'no_local_list' => 'Fout, Geen locale lijst gedefinieerd voor',
  'No lists available' => 'Geen lijsten beschikbaar',
  'Done' => 'Klaar',
  'new users' => 'nieuwe gebruikers',
  'and' => 'en',
  'existing users' => 'bestaande gebruikers',
  'continue' => 'Ga verder',

);
?>