<?php
$lan = array(
 'Please select a message to display' => 'Selecteer aub een bericht om te tonen',
 'Attachments for this message' => 'Attachments voor dit bericht',
 'No attachments' => 'Geen attachments',
 'Filename' => 'Bestandsnaam',
 'Size' => 'Grootte',
 'Mime Type' => 'Mime Type',
 'Description' => 'Omschrijving',
 'Lists this message has been sent to' => 'Lijsten naar waar dit bericht reeds is verzonden',
 'None yet' => 'Nog geen',
 'Send this (same) message to (a) new list(s)' => 'Verzend dit (zelfde) bericht naar (een) nieuwe lijst(en)',
 'List is Active' => 'Lijst is actief',
 'List is not Active' => 'Lijst is niet actief',
 'No such message' => 'Geen zulk bericht',
 '<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the "Requeue" function.' => '<b>Notitie:</b> dit bericht is al naar alle lijsten verzonden. Om dit bericht te zenden naar nieuwe gebruikers, gebruik de "Terug in wachtrij" functie.',
 'Resend' => 'Zend Opnieuw',
 'id' => 'id',
 'subject' => 'onderwerp',
 'fromfield' => 'van veld',
 'tofield' => 'naar veld',
 'replyto' => 'antwoord aan',
 'message' => 'bericht',
 'textmessage' => 'tekstbericht',
 'footer' => 'footer',
 'entered' => 'gestart',
 'modified' => 'gewijzigd',
 'embargo' => 'embargo',
 'repeatinterval' => 'herhalingsinterval',
 'repeatuntil' => 'herhaaltot',
 'status' => 'status',
 'userselection' => 'gebruikersselectie',
 'sent' => 'verzonden',
 'htmlformatted' => 'htmlformaat',
 'sendformat' => 'verzendformaat',
 'template' => 'sjabloon',
 'processed' => 'verwerkt',
 'astext' => 'als tekst',
 'ashtml' => 'als html',
 'astextandhtml' => 'als tekst en html',
 'aspdf' => 'als pdf',
 'astextandpdf' => 'als tekst en pdf',
 'viewed' => 'bekeken',
 'bouncecount' => 'bounce telling',
 'sendstart' => 'verzend start',
 'rsstemplate' => 'RSS sjabloon',
 'owner' => 'eigenaar',

 # new in 2.10.1
 'edit this message' => 'Bewerk dit bericht',
);
?>
