<?php

$lan = array(
'Running in testmode, no emails will be sent. Check your config file.' => 'Loopt in testmodus, geen emails zullen worden verzonden. Controleer je config bestand.',
'The following restrictions have been set by your ISP:' => 'De volgende beperkingen zijn geplaatst door jou ISP:',
'Script stage' => 'Stadium van het script',
'Finished, Nothing to do' => 'Klaar, Niets te doen',
'messages sent in' => 'Berichten verzonden in',
'seconds' => 'seconden',
'invalid emails' => 'ongeldige emails',
'emails failed (will retry later)' => 'emails mislukt (zal later opnieuw proberen)',
'emails unconfirmed (not sent)' => 'emails onbevestigd (niet verzonden)',
'Warning: script never reached stage 5' => 'Opgelet: script heeft nooit stage 5 bereikt',
'This may be caused by a too slow or too busy server' => 'Dit kan de veroorzaakt zijn door een te trage of te drukke server',


'In safe mode, batches are set to a maximum of 100' => 'In veilige modus worden partijen op een maximum van 100 geplaatst',
'Running in safe mode' => 'Loopt in veilige modus',
'msgs/hr' => 'berichten/u',
'Reload required' => 'Herladen vereist',
'Finished, All done' => 'Klaar, alles gedaan',
'Script finished, but not all messages have been sent yet.' => 'Script klaar maar niet alle berichten zijn reeds verzonden.',
'Finished this run' => 'Klaar met deze fase',
'(test)' => '(test)',
'Would have sent' => 'Zou verzonden hebben',
'(test)' => '(test)',
'Would have sent' => 'Zou verzonden hebben',
'Started' => 'Gestart',
'Processing has been suspended by your ISP, please try again later' => 'Het verwerken is uitgesteld door uw ISP, probeer het later aub opnieuw',
'Sending in batches of' => 'Verzenden in partijen van',
'emails' => 'emails',
'This batch will be' => 'Deze partij zal',
'emails, because in the last' => 'emails bevatten, omdat in de laatste',
'emails were sent' => 'emails werden verzonden',
'Sending in batches of' => 'Verzenden in partijen van',
'emails' => 'emails',
'In the last' => 'In de laatste',
'seconds more emails were sent' => 'seconden werden er meer mails verzonden',
'than is currently allowed per batch' => 'dan momenteel is toegestaan per partij',
'Sent in last run' => 'Verzonden in laatste fase',
'Skipped in last run' => 'Overgeslaan in laatste fase',
'Processing has started,' => 'Processing has started,',
'message(s) to process.' => 'bericht(en) te verwerken.',
'It is safe to click your stop button now, report will be sent by email to' => 'Nu is het veilig om op je "stop" knop te drukken, een rapport zal per email worden verzonden aan',
'Your webserver is running in safe_mode. Please keep this window open. It may reload several times to make sure all messages are sent.' => 'Uw webserver loop in "veilige modus". Lat dit venster aub open.
Het kan verschillende malen herladen om er zeker van te zijn dat alle berichten verstuurd zijn.',
'Reports will be sent by email to' => 'Rapporten zullen worden verzonden naar',
'Processing message' => 'Verwerken van bericht',
'Message' => 'Bericht',
'is an RSS feed for' => 'is een RSS feed voor',
'Looking for users' => 'Zoeken naar gebruikers',
'users apply for attributes, now checking lists' => 'gebruikers komen overeen met de attributen, nu lijst aan het controleren.',
'No users apply for attributes' => 'Geen gebruikers komen overeen met de attributen',
'looking for users who can be excluded from this mailing' => 'Zoeken naar gebruikers die kunnen worden uitgesloten van deze verwerkingsrij fase',
'Process Killed by other process' => 'Verwerking gestopt door een andere verwerking',
'Found them' => 'Gevonden',
'to process' => 'naar verwerking',
'No users to process for this batch' => 'Geen gebruikers te verwerken voor deze partij',
'batch limit reached' => 'partij limiet bereikt',
'Process Killed by other process' => 'Verwerking gestopt door een andere verwerking',
'Message I was working on has disappeared' => 'Bericht waar ik aan aan het werken was is verdwenen',
'Sending' => 'Verzenden',
'It took' => 'Het duurde',
'seconds to send' => 'seconden om te verzenden',
'Failed sending to' => 'Mislukt om te zenden naar',
'Unconfirmed user' => 'Onbevestigde gebruiker',
'Not sending to' => 'Niet aan het verzenden naar',
'already sent' => 'Reeds verzonden',
'Processed' => 'Verwerkt',
'out of' => 'zonder',
'Hmmm, No users found to send to' => 'Hmmm, Geen gebruikers gevonden om naar te zenden',
'It took' => 'Het duurde',
'to send this message' => 'om dit bericht te zenden',
'waiting for' => 'aan het wachten op',
'to make sure we don\'t exceed our limit of' => 'om zeker te zijn dat we niet over onze limiet gaan',
'messages in' => 'berichten binnen',

### new in 2.9.5
'Message Sending has started' => 'Verzenden van berichten is begonnen',
'phplist has started sending the message with subject %s' => 'phplist is begonnen met het verzenden van het bericht met onderwerp %s',
'to view the progress of this message, go to %s' => 'Om de voortgang van dit bericht te bekijken, ga naar %s',
'There have been more than 10 attempts to send to %s that have been blocked for domain throttling.' => 'Er zijn meer dan 10 pogingen ondernomen om %s te verzeden, deze werden geblokkeerd voor domain throttling.',
'Introducing extra delay to decrease throttle failures' => 'Instellen van extra vertraging om throttle fouten te verminderen',
'%s is currently over throttle limit of %d per %d seconds' => '%s is momenteel over de throttle limiet van %d per %d seconden',
'not sending to ' => 'niet verzenden naar ',
'Message Sending has finished' => 'Verzenden van bericht beindigd',
'phplist has finished sending the message with subject %s' => 'phplist is klaar met het verzenden van het bericht met onderwerp %s',

'Sending of this message has been suspended' => 'Verzenden van dit bericht is uitgesteld',

# new in 2.10.1
'Less than batch size were sent, so reloading imminently' => 'Minder dan de partijgrootte werd verzonden, dus dringend opnieuw laden',
'Waiting for %d seconds before reloading' => 'Wachten voor %d seconden na opnieuw laden',
'Please leave this window open. You have batch processing enabled, so it will reload several times to send the messages. Reports will be sent by email to' => 'Laat dit venster aub open. Je hebt partijverwerking aangeschakeld, dus het zal verschillende malen opnieuw laden om het bericht te zenden. Rapporten zullen worden verzonden per email naar',

);

?>