<?php
$lan = array(
'Invalid Request' => 'Ongeldig verzoek',
'You do not have access to this page' => 'Je hebt geen toegang tot deze pagina',
'User Click Statistics' => 'Gebruiker klik statistieken',
'User Click Details for a URL in a message' => 'Klik Details van Gebruiker voor een URL in een bericht',
'Subject' => 'Onderwerp',
'Entered' => 'Ingegaan',
'Sent' => 'Verzonden',
'User Click Details for a message' => 'Klik Details van Gebruiker voor een bericht',
'User' => 'Gebruiker',
'Subject' => 'Onderwerp',
'Entered' => 'Ingegaan',
'Sent' => 'Verzonden',
'User Click Details for a URL' => 'Klik Details van Gebruiker voor een URL ',
'User Click Details for a Message' => 'Klik Details van Gebruiker voor een bericht',
'Subject' => 'Onderwerp',
'Entered' => 'Ingegaan',
'Sent' => 'Verzonden',
'User Click Details' => 'Klik Details van Gebruiker',
'message' => 'bericht',
'firstclick' => 'eersteklik',
'latestclick' => 'laatsteklik',
'clicks' => 'klikken',
'sent' => 'verzonden',
'clickrate' => 'klikrate',
'clicks' => 'klikken',
);
?>
